### ISSUE TITLE
Less Log Duplication

### ISSUE THREAD

**Issue by chuyskywalker** [RocketMap/RocketMap#1031]
So, this has been bugging me:

```
status['message'] = 'Searching at {:6f},{:6f}'.format(step_location[0], step_location[1])
log.info(status['message'])
```

This reeks of duplicate work to me. So I started investigating the `logging` class -- it's pretty dang powerful, and I'm wondering if we shouldn't just be attaching a secondary handler to fulfill this usecase. 

Something like [this gist which logs regularly](https://gist.github.com/chuyskywalker/74d1c74825b41f6255ede888300b8a8b), but keeps the most recent message per thread and can then dump them out.

You can even attach custom metadata to `LogRecords` (like current user, step location, etc) so that things are a bit more structured.

Tagging @justsomedudeonthenet since this is his specialty ;D

**Comment by chuyskywalker** [comment]
Also, all this:

```
    # Add file logging if enabled
    if args.verbose and args.verbose != 'nofile':
        filelog = logging.FileHandler(args.verbose)
        filelog.setFormatter(logging.Formatter('%(asctime)s [%(threadName)16s][%(module)14s][%(levelname)8s] %(message)s'))
        logging.getLogger('').addHandler(filelog)
    if args.very_verbose and args.very_verbose != 'nofile':
        filelog = logging.FileHandler(args.very_verbose)
        filelog.setFormatter(logging.Formatter('%(asctime)s [%(threadName)16s][%(module)14s][%(levelname)8s] %(message)s'))
        logging.getLogger('').addHandler(filelog)
```

Can apparently be done almost exclusively by [`logging.conf` files](https://docs.python.org/2/library/logging.config.html). 

Doing so would be way more powerful, since changing up which areas are verbose, where the `printscreen` variant hooks in, etc, etc would all be run time configurable, instead of us having to monkey patch code into various areas of the codebase. Could even provide several pre-configured conf files like `contrib/logging/super-verbose.conf` or `contrib/logging/mostly-verbose-but-print-screen.conf` or whatever.

**Comment by justsomedudeonthenet** [comment]
All of the logging can probably use a good refactoring.  I will look into it.

**Comment by sebastienvercammen** [comment]
Closed, this is a very old issue. Any feature requests are now handled via http://vote.devkat.org and if any issue reported in the issue is still related to current code, a new GitHub issue should be opened.
