### ISSUE TITLE
Scans can easily overlap, resulting in suboptimal scanning

### ISSUE THREAD

**Issue by LordMike** [RocketMap/RocketMap#1049]
When moving around the scan location manually, or following the users location, a lot of overlapping can occur. This is a suggestion on how to resolve this.
## Expected Behavior

When scanning areas, it would make sense not to rescan something that has been covered just seconds ago. You will not get any new information out of this area. I would expect the searcher to _not_ re-scan areas until after a certain period of time (say 3 minutes).
## Current Behavior

If placing searches manually (moving the pin in the map) or when using the Follow users location feature, a lot of overlapping will occur. 

![image](https://cloud.githubusercontent.com/assets/1027111/18061626/b21472f2-6e23-11e6-879f-0b8ac13434fa.png)
## Possible Solution

I can envision two ways to fix this.

One. Check the DB for recently scanned areas, and see if the center you want to scan is "close enough" to any center that was scanned during some timeframe. This can be costly in two ways: It's a lot of queries to perform that may cover large sets of data, and if spatial features are not enabled in the underlying DB, it won't be possible to use efficient data structures to find close proximity locations.

Two. Create a grid spanning the entire world, starting from 0,0 and moving out 60 meters pr. point east/west. In the next rows, 52 meters north/south, the same pattern appears, but adjusted slightly so we get the same hex grid as now. Now it is possible, given any location, to calculate the "fixed" center of this location, and use the fixed points instead.

As each point will be deterministically fixed to a location, we can assign a unique id to the location, which can then be used a primary key in a database. Doing so, makes it possible to do instant lookups in the DB to find the previous scan (if any) on a given location.

**Note**
- The grid assumes that each circle east/west is spaced by `60.622` meters
- The grid assumes that each circle north/south is spaced by `52.5002` meters
- To properly cover all, ever second row of circles is shifted `30.311` meters east

Example calculation (i use meters here, as the lat/lon become very small for 70 meters):
1. Have a location (744, 513)
2. Calculate the "row" as `lat / 52.5002` = `14.17`
3. Calculate the "column" as `lon % 60.622` = `8.46`
4. Round the row/col numbers: `(14, 8)`
5. Calculate the fixed coordinate as `(row * 52.5002, col * 60.622)` = `(735, 485)`
6. If the row is odd, add `30.311` to the longitude

And then for the id for each fixed point: As we move approx 60 meters east/west for each column, we can cover the circumference of earth (40.000 km) with 666.666 points. The same should be true for the north/south. These numbers fit well within 32 bit integer, so we can pack them together in a single 64 bit integer by this:

`col << 32 | row`

**Note:**
- The math needs checking. Since the earth isn't perfectly round
- The fixed coordinates can be as far as X meters from the intended point (due to the division). I have tried to account for this by using rounding in step 4.
## Steps to Reproduce (for bugs)
1. Start map
2. Place marker near current location, observe overlaps with Scanned Locations enabled
3. Enable follow user, and roam around. Observe overlaps.
## Your Environment
- Version used: 62904b3e63330d8482d7253e9068e637a5f54f56
- Environment name and version (e.g. Python 2.7): python 2.7.12, pip 8.1.2
- Operating System and version (desktop or mobile): Ubuntu 16.04

**Comment by chuyskywalker** [comment]
The suggestion to force an alignment of all hexes has come up before and I really like the idea. Not only does it solve situations like this, but it also make data much, much easier to share and reason about.

I, personally, just don't know "earth math" well enough to implement it.

It's also questionable whether this would apply to SPS mode; but probably not.

**Comment by jccwright** [comment]
I don't want to send like a total newb or asshole but any reason we don't
consider adding support for the MRGS? I have been envisioning this exact
solution where basically instead of everyone running their own map sets for
personal use... they act as distributed agents working to cover the entire
surface and instead of storing the data only locally either pointing the
Web hooks to a common receiver for loading into a shared database available
for ALL Implementations.

I have some of these pieces already in place...

**Comment by chuyskywalker** [comment]
MRGS?

**Comment by LordMike** [comment]
Centrally gathering Pokemon is not in the scope of this issue. It can also be accomplished regardless of this gets done or not. 

I tried to do this earlier in my own project but got completely skewed when further from the center. Perhaps I got the numbers right this time (now I actually used a cad tool to check my math :P).

**Comment by nothize** [comment]
Is that equivalent to perform a radius search (or just simply square box check) check against the next to be scanned location?

And this logic may be incorporated into the search location generation routine.

For sure, the quiet period (avoid scanning already covered area) is optional and is a configurable argument.

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
