### ISSUE TITLE
Potential Super Speed Point Discovery

### ISSUE THREAD

**Issue by chuyskywalker** [RocketMap/RocketMap#1052]
> What's that? You have 800,000 discovered pokemon in your database and you want to scan a 20 step radius? Well, you're going to need to wait about 3-5 minutes while we figure out which items are in that circle for you, hold on there partner.

Blech!

Now, let's say you have a database with actual GIS functions and data stored in a nice, friendly way:

```
mysql> show create table pokemon_geo \G
*************************** 1. row ***************************
       Table: pokemon_geo
Create Table: CREATE TABLE `pokemon_geo` (
  `encounter_id` varchar(50) NOT NULL,
  `spawnpoint_id` varchar(255) NOT NULL,
  `pokemon_id` int(11) NOT NULL,
  `location` point NOT NULL,
  `disappear_time` datetime NOT NULL,
  PRIMARY KEY (`encounter_id`),
  KEY `pokemon_spawnpoint_id` (`spawnpoint_id`),
  KEY `pokemon_pokemon_id` (`pokemon_id`),
  KEY `pokemon_disappear_time` (`disappear_time`),
  KEY `location` (`location`(25))
) ENGINE=InnoDB DEFAULT CHARSET=latin1
```

And you've loaded "old style" data into it:

```
INSERT INTO pokemon_geo 
SELECT encounter_id, spawnpoint_id, pokemon_id, point(latitude, longitude), disappear_time from pokemon;
```

Well, now things can get interesting:

```
mysql> SELECT
    ->     ST_X(`location`) AS lat,
    ->     ST_Y(`location`) AS lng,
    ->     ((EXTRACT(minute FROM `disappear_time`) * 60) + EXTRACT(second FROM `disappear_time`)) AS time,
    ->     `spawnpoint_id`
    -> FROM `pokemon_geo`
    -> WHERE st_distance_sphere(point(39.9483691,-75.1694445), `location`) < 70*20
    -> GROUP BY lat, lng, time, spawnpoint_id;
+------------------+-------------------+------+---------------+
| lat              | lng               | time | spawnpoint_id |
+------------------+-------------------+------+---------------+
| 39.8995673556408 | -75.1689025008772 |  532 | 89c6c592d4d   |
| 39.8996605171201 | -75.1678081147286 |   96 | 89c6c5ed35b   |
| 39.8997080543536 | -75.1681729109591 | 3488 | 89c6c5ed33b   |
| 39.8998725160732 | -75.1676257162955 | 2448 | 89c6c5ed49d   |
| 39.8998725160732 | -75.1676257162955 | 2449 | 89c6c5ed49d   |
...etc...
+------------------+-------------------+------+---------------+
3295 rows in set (5.86 sec)
```

Nice.

**Comment by chuyskywalker** [comment]
This would hinge on everyone being on mysql though. Which is probably the bigger discussion point.

**Comment by justsomedudeonthenet** [comment]
There is a plugin that does GIS stuff for sqlite though, isn't there?  

Also important, can we do this through peewee?  Might be easier to ditch peewee and write our own query layer.

**Comment by chuyskywalker** [comment]
My brief look into GIS on sqlite is there is ... something out there for it, but requires some custom song-and-dance magic to get it built in.

**Comment by ZeeD26** [comment]
How about ditching Peewee for SQLAlchemy and going for [GeoAlchemy](http://geoalchemy.org/)?

**Comment by LordMike** [comment]
Quick question. Shouldn't you be able to use Googles S2 Geometry, and collapse all coordinates to S2 integers (64-bit longs) at the 30-level precision?

If I read their stuff right, you should be able to do contains checks by doing simple bounds checks. So X is contained in box B if B.Min < X < B.Max... To do the above query (finding points close to somewhere) would be as simple as creating a box around it in S2, and doing a query for points between the box's Min and Max.

**Comment by chuyskywalker** [comment]
Kinda. That would give you a box-bounding area, but we already have that with lat/lng. If there's some fancy method to do radial lookups with s2, I don't know it. Maybe there is.

**Comment by j16sdiz** [comment]
SpatiaLite is the sqlite equivalence. Available as binary on debian/ubuntu/windows. Not sure the support on python side.

S2 have an object type called "Cap", which might do what you want -- but I won't recommend it because it is too primitive.

**Comment by pyr0ball** [comment]
just my two cents: Everyone should be on MySQL anyway

**Comment by LordMike** [comment]
Well that, or some other central database. If your Postgres instance was running independently, it should very well be capable of handling any workload you throw at it. 

When I first set this up, I really liked the idea that it was independently runnable. I didn't have to start up a MySQL server just to run this. 

I've since migrated my data to MySQL, but that was after I thought "huh, I'd like to run this for a while". 

That was easy for me, since I already have a local vm with a MySQL running on it. But for many others, MySQL would be a hindrance. Just see the help channel on discord. Asking people to set up MySQL too wouldn't help at all :P. 

So if Postgres doesn't "cost" anything to have. Keep it. If t becomes a burden, remove it.

**Comment by timdine** [comment]
Simpler version to implement.  46000 spawn points, 125 steps took forever.  Added a simple set of bounding box if statements before using geopy and it cut significant time from the scan.  0.003 degrees of longitude even at extreme latitudes should be plenty for what this is trying to accomplish, I've even left in the 70m check for if it's close.  It'd probably be good enough and worth the time savings to leave it out.



            for idx, sp in enumerate(s):
		if ((sp['lat'] - hl[0] > 0.003) or (sp['lat'] - hl[0] > -0.003)):
		    if ((sp['lng'] - hl[1] > 0.003) or (sp['lng'] - hl[1] > -0.003)):
			if geopy.distance.distance(hl, (sp['lat'], sp['lng'])).meters <= 70:
				filtered.append(s.pop(idx))

**Comment by sebastienvercammen** [comment]
Closed, this is a very old issue. Any feature requests are now handled via http://vote.devkat.org and if any issue reported in the issue is still related to current code, a new GitHub issue should be opened.
