### ISSUE TITLE
`encounter_id` insufficient as primary key.

### ISSUE THREAD

**Issue by j16sdiz** [RocketMap/RocketMap#1055]
Encounter_id can be duplicated, causing a unique key violation.
## Expected Behavior

Another primary key should be used.
## Current Behavior

It keep retrying
## Possible Solution

No idea
## Steps to Reproduce (for bugs)

Note the spawnpoint_id is changed:

```
mysql> select * from pokemon  where encounter_id ='OTI2Nzc5ODYzMDg1MjIwMTAyMQ==';
+------------------------------+---------------+------------+------------------+------------------+---------------------+
| encounter_id                 | spawnpoint_id | pokemon_id | latitude         | longitude        | disappear_time      |
+------------------------------+---------------+------------+------------------+------------------+---------------------+
| OTI2Nzc5ODYzMDg1MjIwMTAyMQ== | 34040618e4d   |        129 | 22.4053446060387 | 114.217734424664 | 2016-08-29 23:42:17 |
+------------------------------+---------------+------------+------------------+------------------+---------------------+
1 row in set (0.00 sec)

mysql> delete from pokemon  where encounter_id ='OTI2Nzc5ODYzMDg1MjIwMTAyMQ==';
Query OK, 1 row affected (0.00 sec)

mysql> select * from pokemon where encounter_id ='OTI2Nzc5ODYzMDg1MjIwMTAyMQ==';
+------------------------------+---------------+------------+------------------+------------------+---------------------+
| encounter_id                 | spawnpoint_id | pokemon_id | latitude         | longitude        | disappear_time      |
+------------------------------+---------------+------------+------------------+------------------+---------------------+
| OTI2Nzc5ODYzMDg1MjIwMTAyMQ== | 340400ca655   |         42 | 22.3280348231229 | 114.168505464265 | 2016-08-30 05:27:21 |
+------------------------------+---------------+------------+------------------+------------------+---------------------+
1 row in set (0.00 sec)
```
## Your Environment

- Version used:
- Environment name and version (e.g. Python 2.7):
- Operating System and version (desktop or mobile):

**Comment by chuyskywalker** [comment]
We'd need something else to go by then. Maybe a `unique` on encounter_id + spawpoint_id? Lat/lng? I dunno.

**Comment by JZ6** [comment]
rngesus be praised, go buy a lottery ticket

**Comment by JZ6** [comment]
real talk tho, encounter_id + time should be sufficient

**Comment by j16sdiz** [comment]
I prefer encounter_id + spawnpoint_id, because the encounter_id *is* time: https://www.reddit.com/r/pokemongodev/comments/4z9a6d/encounter_ids_not_completely_random_some_bits/

**Comment by j16sdiz** [comment]
I am seeing this every other day. Seems to keep happending to these two spawn point

**Comment by sebastienvercammen** [comment]
Closed, this is a very old issue. Any feature requests are now handled via http://vote.devkat.org and if any issue reported in the issue is still related to current code, a new GitHub issue should be opened.
