### ISSUE TITLE
Page Weight

### ISSUE THREAD

**Issue by chuyskywalker** [RocketMap/RocketMap#1071]
So, decided to have a look over the "page weight" of the app:
1. 1.5mb fresh page download. Yike!
2. My god, we load a 70kb woff file so we can have two stupid icons in the menu bar 
3. About 1/3 of the whole page weight is the pokemon icon sprite :)
4. The pokemon.min.json is super-verbose and could easily be trimmed down quite a bit with less object wrapping and more string-to-int replacements

Most of the rest is javascript (there's a LOT of it). Most of that comes from google maps, which is unavoidable, of course. That said, jquery ui is probably a bit heavy for what we're doing, and I'd be willing to bet we could get away with a trimmed down jquery instance as well (selectors and utils only, perhaps?)

There's a lot of modernizer/polyfill stuff that we could take or leave, depending on how much backwards compat support we want to put up with.

**Comment by angrymoose** [comment]
Best short term option is to enable static file caching & compress the javascript. Long term I agree with you & would love to see the file size shrink.

**Comment by sebastienvercammen** [comment]
Closed, this is a very old issue. Any feature requests are now handled via http://vote.devkat.org and if any issue reported in the issue is still related to current code, a new GitHub issue should be opened.
