### ISSUE TITLE
Duplicate spawnpoint scans due to different latitude & longitude roundings

### ISSUE THREAD

**Issue by hagehg** [RocketMap/RocketMap#1075]
I have older entries in my pokemon table where the latitude was stored with 12 decimals (12 numbers after the . in case decimals is not the right word here). 

Since late at night on August 18th (presumably I pulled a new version of the map then) I get 13 decimals instead.

Example:
![decimals](https://cloud.githubusercontent.com/assets/20759246/18128837/0d641580-6f88-11e6-97df-1af84ac65f3d.png)

When doing spawnscanning, my scanners will regard the 12 and 13 decimal entries of the same spawnpoint as two different locations, resulting in two scanners scanning the same location twice simultaniously:

```
2016-08-31 13:43:12,684 [ search-worker-0][        search][    INFO] Early for xx.xxxxx3,xx.xxxxx6; waiting 11s...
2016-08-31 13:43:13,144 [ search-worker-1][        search][    INFO] Early for xx.xxxxx3,xx.xxxxx6; waiting 10s...
2016-08-31 13:43:23,248 [ search-worker-1][        search][    INFO] Searching at xx.xxxxx3,xx.xxxxx6
2016-08-31 13:43:23,788 [ search-worker-0][        search][    INFO] Searching at xx.xxxxx3,xx.xxxxx6
2016-08-31 13:43:35,043 [ search-worker-1][        models][    INFO] Parsing found 4 pokemons, 26 pokestops, and 8 gyms
2016-08-31 13:43:35,387 [ search-worker-0][        models][    INFO] Parsing found 4 pokemons, 26 pokestops, and 8 gyms
```

I have 10 of these cases in my database (8 with latitude, 2 with longitude). Depending on how many one has, this could be a big waste of resources.
## Expected Behavior

The scanners should realize they're scanning the same spawnpoint regardless of decimals.
## Current Behavior

Two scanners scan the same spawnpoint at the same time
## Possible Solution

Maybe use spawnpoint_id in addition to latitude and longitude somehow
## Steps to Reproduce (for bugs)

1. Run this query on your datase :
   `SELECT spawnpoint_id, latitude, char_length(latitude)-3 AS decimals FROM pokemon GROUP BY spawnpoint_id, decimals;`
2. Look for spawnpoint_ids that appear more then once in the results (I did that by copying the data to Excel and used it's 'Highlight duplicate entries' feature)
## Your Environment

- Version used: dev branch from yesterday
- Environment name and version (e.g. Python 2.7): Python 2.7
- Operating System and version (desktop or mobile): Ubuntu

**Comment by justsomedudeonthenet** [comment]
Are the spawnpoint_id fields duplicates?  That ID is how to really tell a unique spawnpoint.

**Comment by hagehg** [comment]
@justsomedudeonthenet 
the spawnpoint_id is the same, you can see it in the WHERE section of my query in the screenshot

**Comment by arivero** [comment]
I got the same issue but I though the rounding error had been generated by an export/import backup from the previous version. Nice to know that it was not my mistake :-)

**Comment by Cartman123** [comment]
Are you using mysql?

I was noticing the same thing today right after I changed to mysql, so I tested something out.

On models.py, I made these alterations:

```
        # Sqlite doesn't support distinct on columns
        if args.db_type == 'mysql':
#            query = query.distinct(Pokemon.spawnpoint_id)
            query = query.group_by(Pokemon.spawnpoint_id)
        else:
            query = query.group_by(Pokemon.spawnpoint_id)
```

And now I don't have any duplicates anymore.

It seems like some kind of bug with distinct on mysql? Or maybe it's the case insensitive collations?

**Comment by rbryson74** [comment]
Distinct is not as distinct as many would really like. But it's much faster. so... tradeoffs.

**Comment by tiagomartines11** [comment]
You could adjust the select query to include `TRUNCATE()`, something like:
`SELECT DISTINCT
    TRUNCATE(latitude,12) AS lat,
    TRUNCATE(longitude,12) AS lng,
    ((EXTRACT(MINUTE FROM t1.disappear_time) * 60) + EXTRACT(SECOND FROM t1.disappear_time)) AS time,
    t1.spawnpoint_id`

**Comment by sebastienvercammen** [comment]
Closed, this is a very old issue. Any feature requests are now handled via http://vote.devkat.org and if any issue reported in the issue is still related to current code, a new GitHub issue should be opened.
