### ISSUE TITLE
Search workers "searching" an area and not parsing anything into the database

### ISSUE THREAD

**Issue by mgoodsell91** [RocketMap/RocketMap#1085]
Randomly during a search the all the workers will search an area but never parse anything in the database. Causing the search to stop but errors happen and DB cleaning still happens
## Expected Behavior

The workers should return a line in the console such as "2016-08-31 23:10:10,569 [ search-worker-1][        models][    INFO] Parsing found 1 pokemons, 16 pokestops, and 5 gyms" after searching the area
## Current Behavior

No return at all I just end up with this in the console

> 2016-08-31 23:10:12,422 [search-worker-11][        search][    INFO] Early for 61.297351,-0.819917; waiting 12s...
> 2016-08-31 23:10:13,876 [ search-worker-6][        search][    INFO] Early for 61.258321,-0.853236; waiting 12s...
> 2016-08-31 23:10:14,171 [search-worker-12][        search][    INFO] Early for 61.278055,-0.816856; waiting 12s...
> 2016-08-31 23:10:14,568 [ search-worker-5][        search][    INFO] Early for 61.256653,-0.846346; waiting 13s...
> 2016-08-31 23:10:14,725 [ search-worker-0][        search][    INFO] Searching at 61.261128,-0.849809
> 2016-08-31 23:10:18,051 [ search-worker-9][        search][    INFO] Early for 61.281420,-0.838773; waiting 14s...
> 2016-08-31 23:10:18,290 [ search-worker-2][        search][    INFO] Early for 61.276868,-0.857132; waiting 15s...
> 2016-08-31 23:10:19,293 [search-worker-10][        search][    INFO] Searching at 61.271826,-0.829889
> 2016-08-31 23:10:20,614 [ search-worker-4][        search][    INFO] Searching at 61.270117,-0.840005
> 2016-08-31 23:10:24,444 [search-worker-11][        search][    INFO] Searching at 61.297351,-0.819917
> 2016-08-31 23:10:24,970 [ search-worker-7][        search][    INFO] Searching at 61.275683,-0.816694
> 2016-08-31 23:10:25,896 [ search-worker-6][        search][    INFO] Searching at 61.258321,-0.853236
> 2016-08-31 23:10:26,197 [search-worker-12][        search][    INFO] Searching at 61.278055,-0.816856
> 2016-08-31 23:10:27,601 [ search-worker-5][        search][    INFO] Searching at 61.256653,-0.846346
> 2016-08-31 23:10:32,079 [ search-worker-9][        search][    INFO] Searching at 61.281420,-0.838773
> 2016-08-31 23:10:33,329 [ search-worker-2][        search][    INFO] Searching at 61.276868,-0.857132
> 2016-08-31 23:10:48,263 [      db-cleaner][        models][    INFO] Regular database cleaning complete
> 2016-08-31 23:11:48,348 [      db-cleaner][        models][    INFO] Regular database cleaning complete
> 2016-08-31 23:12:48,379 [      db-cleaner][        models][    INFO] Regular database cleaning complete
> 2016-08-31 23:13:48,476 [      db-cleaner][        models][    INFO] Regular database cleaning complete
> 2016-08-31 23:14:48,553 [      db-cleaner][        models][    INFO] Regular database cleaning complete
> 2016-08-31 23:15:48,631 [      db-cleaner][        models][    INFO] Regular database cleaning complete
## Possible Solution

Has -SS working fine changed to a larger search area and that seemed to trigger the issue and even moving back to the smaller area it still happens
## Steps to Reproduce (for bugs)

1. Start scan
   2.Wait anywhere from 30 mins to 11 hours for the scans to stop working
## Your Environment

- Version used: Latest Commit - c7fa19a  
- Environment name and version (e.g. Python 2.7): Python 2.7
- Operating System and version (desktop or mobile): Mac OSX 10.11

**Comment by CatsFaninLex** [comment]
I'm having the same issue.  The scanning stops and takes anywhere from 15-30 minutes before it starts again.  This happens once an hour or so.

**Comment by pyr0ball** [comment]
How old is the database? was it migrated from a previous build?

**Comment by mgoodsell91** [comment]
I started with a brand new installation of the map and a new database last night and I'm still having the same issue.

**Comment by mohranger** [comment]
Having the same issue. I updated my map and it keeps spamming "early for [LOCATION], trying again in 15-40 seconds."

**Comment by Morblius** [comment]
I am having this same issue. The scanners will randomly stop scanning and only the db-cleaner messages appear. It happens when I try to use either the default pogom.db database or also happening when I try a mariadb mysql database. The scanners never start working again unless I manually restart them.

**Comment by ChipWolf** [comment]
We had the same issue. Turns out our entire account pool had been banned

**Comment by sebastienvercammen** [comment]
Closed, this is a very old issue. Any feature requests are now handled via http://vote.devkat.org and if any issue reported in the issue is still related to current code, a new GitHub issue should be opened.
