### ISSUE TITLE
Mobile - Options Button may become unresponsive.

### ISSUE THREAD

**Issue by CometX** [RocketMap/RocketMap#1120]
On mobile (IOS and various other browsers) the options menu button may not function properly when clicked. The issue seems to be happen more often when there is a large amount of Pokemon showing; however it will still happen on random with little on map.

Temp fix: Refresh browser several times.

Thanks for checking on this one!

**Comment by sebastienvercammen** [comment]
Issue is no longer related to the current codebase, so we're closing the issue. If anyone still has the problem, please post additional data on latest commit and we'll reopen.
