### ISSUE TITLE
[Feature Request] Add scan-here button 

### ISSUE THREAD

**Issue by jaquer** [RocketMap/RocketMap#1121]
I know you guys got a lot going on, but I'd like to migrate this feature request from [Feathub](http://feathub.com/PokemonGoMap/PokemonGo-Map/+14). It's gotten quite a few votes over there, and the corresponding PR (#16) has gotten a good reaction too. Even @maddhatter likes it, and the guy's a freakin' genius. so you know it's good.

I've been importing it as-is, but I'm worried about it straying too much from the mainline and having @tkSimon be discouraged from keeping it updated.

Thank you for considering it.

**Comment by PhantonQuad** [comment]
Like the sound of this.. One question will it just run through the scan once then stop?

**Comment by cbogithub** [comment]
:+1:  i think good idea

**Comment by tkSimon** [comment]
@phantonquad As of now it will move the scan location to the selected area, which will be scanned until changed using any of the available features to change scan location.

**Comment by PhantonQuad** [comment]
Ok that's for this, it's a great idea!

**Comment by ChipWolf** [comment]
Some more multi-user capabilities would be welcome additions

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
