### ISSUE TITLE
[Feature Request] Toggle 'Hide Pokémon', 'Notify of Pokémon' and 'Notify of Rarity' on/off

### ISSUE THREAD

**Issue by ps-gunkie** [RocketMap/RocketMap#1123]
Hi, just going to copy this here from [Feathub](http://feathub.com/PokemonGoMap/PokemonGo-Map/+19) :

> It would be useful to add an on/off toggle to 'Hide Pokémon', 'Notify of Pokémon' and 'Notify of Rarity'. This would allow you to easily enable or disable the entire lists without having to clear and refill the lists themselves.
> 
> For example, when I'm running around town, I want to be able to see all available pokemon around me, while late at night, when I'm at home, I only want to see the pokemon I might consider leaving the house for (in which case I would hide the more common pokemon). It would be great to just be able to toggle the 'hide' list without having to add/remove 70-odd pokemon from it every day. The toggles can even fit right into the interface as is! :)

Thanks in advance!

Also, someone might want to update the issue submission form to remove the Feathub link. :)

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
