### ISSUE TITLE
[Feature Request] History of Pokemon spawned at a spawnpoint

### ISSUE THREAD

**Issue by mgoodsell91** [RocketMap/RocketMap#1124]
Similar to Pull request 669 but with a chronological history with spawn times of the spawn point.

**Comment by RogueMaster** [comment]
It is already there... check the stats...

**Comment by smithnick** [comment]
How do you check this in the stats?

**Comment by palmercm** [comment]
Seconding this. RogueMaster seems to have misinterpreted the request. 

Unless I'm wrong, it looks like Op is after the ability to click any spawnpoint to view the spawn history. Stats allows you to view where a given pokemon has spawned, but not what else has been spawned from that point/

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
