### ISSUE TITLE
[Feature Request] Advanced Gym Filter on Map Interface (by team, by level, open slot)

### ISSUE THREAD

**Issue by foltincsaba** [RocketMap/RocketMap#1126]
**Description:**

It would be handy if we had these filters on the interface:
- filter gyms by team
- filter gyms by level
- filter gyms by having an open slot

**Purpuse:**

I scan a big area with about 500 Gyms. The are only a few types of gyms that I'm interested in:
- lvl8-9 gyms of my team that is worth training (for long time retainment)
- lvl1-3 gyms of the other teams that are worth capturing (for quick gym count boost)
- gyms that have an open slot already

**Comment by allenpiscitello** [comment]
Another useful filter would be last scan.  Knowing there are empty spots is useless if it's from data that's 8 hours ago.

**Comment by alp-bitcoin** [comment]
I have a PR on this.  Please review if you were interested in this feature.

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
