### ISSUE TITLE
[Feature Request] Add settings management from JSON API.

### ISSUE THREAD

**Issue by lnx85** [RocketMap/RocketMap#1127]
When using PokemonGo-Map from third parts frontends (like iOS apps, etc..) it would be nice to be able to change server settings like **--spawnpoint-scanning** or **--spawnpoints-only** from JSON API as it can be done for Scan Location.

It would be also great to have some settings printed on /status JSON page, in particular **--step-limit** than can be useful to identify if a user is outside the scan range.

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
