### ISSUE TITLE
Starting the server with -u and -p parameters causes an exception

### ISSUE THREAD

**Issue by ilendemli** [RocketMap/RocketMap#1128]
Issuetitle.
## Expected Behavior

Start server with passed username and password
## Current Behavior

Throws an exception:

```
    args.accounts.append({'username': username, 'password': args.password[i], 'auth_service': args.auth_service[i]})
IndexError: list index out of range
```
## Steps to Reproduce (for bugs)
1. Pull develop branch till d92e8eedadf46cf25eeea0e4ca88313ed99918c2
2. Try starting the server with -u and -p arguments
## Your Environment
- Version used: develop branch where last commit was d92e8eedadf46cf25eeea0e4ca88313ed99918c2
- Environment name and version (e.g. Python 2.7): Python 2.7.12
- Operating System and version (desktop or mobile): Windows 10 x64

**Comment by ntzz1337** [comment]
I've encountered this as well, but managed to fix it by specifying authentication method by adding `-a ptc` or `-a google`.

It seems to me that commit #1067 is at fault here. Currently, at line 224 we can see:
```
if len(args.auth_service) is None:
            args.auth_service = ['ptc']
```
The `len()` function returns value which cannot be `None`. Originally, the line looked like this:
```
if args.auth_service is None:
            args.auth_service = ['ptc']
```
The coder decided on checking the lengths instead:
```
if (len(args.username) == 0):
            errors.append('Missing `username` either as -u/--username, csv file using -ac, or in config')
```
```
if (len(args.password) == 0):
            errors.append('Missing `password` either as -p/--password, csv file, or in config')
```

To fix this and keep the code consistent, line 224 of `pogom/utils.py` should be changed to:
```
if (len(args.auth_service) == 0):
            args.auth_service = ['ptc']
```

**Comment by sebastienvercammen** [comment]
Issue is no longer related to the current codebase, so we're closing the issue. If anyone still has the problem, please post additional data on latest commit and we'll reopen.
