### ISSUE TITLE
[Feature Request] Download photo pokestop

### ISSUE THREAD

**Issue by Susosvk** [RocketMap/RocketMap#1130]
Can add download pokestop photo and show info on pokestop ?

**Comment by Becold** [comment]
This would take a lot more data mobile for the users.
This need an enable-disable switch if implemented.

**Comment by Susosvk** [comment]
PC screen enabled on mobile default off and button for ON

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
