### ISSUE TITLE
[Feature Request] Scan only when client connects

### ISSUE THREAD

**Issue by cbogithub** [RocketMap/RocketMap#1132]
http://feathub.com/PokemonGoMap/PokemonGo-Map/+30

It would be good to host a scanner that is on standby 24/7 without being ip banned. If the scanner only scans when a client connects this may be possible.

**Comment by DiscoTim** [comment]
I've been thinking about doing a PR for this, and it would be very useful for me and a lot of others running small maps for few a people. 

I can't envision all use cases. but for this simple scenario, i was thinking that it basically toggles the scan switch when a user connects and keeps it on for 30 minutes or hour or so past the last request.

of course the drawback is that when a user connects they'd need to wait for results, but that is a given. it just forgoes the need to have to start and stop the server when its not being used.

**Comment by KyleBoyer** [comment]
> I've been thinking about doing a PR for this, and it would be very useful for me and a lot of others running small maps for few a people.
> 
> I can't envision all use cases. but for this simple scenario, i was thinking that it basically toggles the scan switch when a user connects and keeps it on for 30 minutes or hour or so past the last request.
> 
> of course the drawback is that when a user connects they'd need to wait for results, but that is a given. it just forgoes the need to have to start and stop the server when its not being used.
> 
> obviously it would be triggered by a command option and not be the default behavior.

Do you have a status on this?

**Comment by KyleBoyer** [comment]
This issue can be closed, as it was added with PR #1271

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
