### ISSUE TITLE
[Feature Request] Display all probable nests

### ISSUE THREAD

**Issue by vtime42** [RocketMap/RocketMap#1138]
Instead of clicking on a particular pokémon to look for a possible nest (and cycling on several pokémons), it would be great if all possible nearby nest were displayed at the same time on the map.

**Comment by kiraacorsac** [comment]
I believe there was a tool that looked in PoGo-Map database and would output probable nests. Is it still around? It might be worth it to add it in the /Tools.

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
