### ISSUE TITLE
Removing excluded pokemon is slow

### ISSUE THREAD

**Issue by justsomedudeonthenet** [RocketMap/RocketMap#1139]
## Expected Behavior

Clicking the x to remove hidden pokemon should happen quickly.
## Current Behavior

Clicking the x freezes the map for 5-10 seconds in chrome on mobile.  This makes removing a lot of hidden pokemon take several minutes.
## Possible Solution

Find what slows it down.  Add a clear all button to the hide pokemon and notify pokemon lists.
## Steps to Reproduce (for bugs)

1. Open map in chrome on android
2. Hide 50 types of pokemon
3. Try to unhide them
4. Throw phone in fustration.
## Your Environment

- Version used:
- Environment name and version (e.g. Python 2.7):
- Operating System and version (desktop or mobile):

**Comment by aldarund** [comment]
Obviously time it take to delete one pokemon is so long because the hidden pokemon now need to be rendered on the map. So if you zoom in small area where only a few pokemons it should be fast. Or its still slow for you even zoomed in to few pokemons?

**Comment by justsomedudeonthenet** [comment]
I thought of that.  Zooomed in as far as possible, only one building visible on the map.  Still takes just as long.

**Comment by Xcelled** [comment]
Without checking, my suspicion is this has to do with the rendering setup of the map. The same delay issues can be seen with eg toggling spawnpoints or scan areas. I *think* the re-rendering only happens when the map updates from the server, so the delay is caused by waiting for that.

This is another thing to lump under #1141

**Comment by DiscoTim** [comment]
i think updateMap is called every 5 seconds, and all markers are setup then. How many markers are you talking about where the delay is large?

**Comment by Darkknightz** [comment]
@justsomedudeonthenet the way filtered pokemon are rerendered is now different, they are send from scratch now. Wonder if this helps  see: #1303

**Comment by sebastienvercammen** [comment]
Closed, this is a very old issue. Any feature requests are now handled via http://vote.devkat.org and if any issue reported in the issue is still related to current code, a new GitHub issue should be opened.
