### ISSUE TITLE
[Feature Request] Account Pooling Service

### ISSUE THREAD

**Issue by huanga** [RocketMap/RocketMap#1147]
It would be great if we can have some sort of centralized account pooling service, where workers can pull for account(s) to use for the instance. This is a summary from [feathub +49](http://feathub.com/PokemonGoMap/PokemonGo-Map/+49) and [feathub +110](http://feathub.com/PokemonGoMap/PokemonGo-Map/+110).
## Expected Behavior
- Each worker instance can launch with a request for certain amount of account(s), which gets pulled from the Account Pooling Service.
- Worker/thread requests for a new account from the Account Pooling Service after some configurable failed requests.
## Current Behavior
- Each worker must launch with a list of hard coded accounts, be it via configuration file or launch parameter.
- Worker/thread dies when account(s) are banned.
## Possible Solution
- An interface where the operator/admin can enter a list of accounts and platforms into a repository
- Add launch parameter `--aps-host` (**A**ccount **P**ooling **S**ervice **Host**) and  matching configuration variable to set the Account Pooling Service Host
- Add launch parameter `--aps-token` (**A**ccount **P**ooling **S**ervice **Token**) and  matching configuration variable to set the shared token for the service
- Add launch parameter `--aps-accounts` (**A**ccount **P**ooling **S**ervice **Accounts**) and matching configuration variable to set number of accounts to request from the pooling service
- When requested, APS registers the account being signed out to the specific named instance (can re-use `-sn` name from status page, or a uniquely generated name a-la ElasticSearch if unavailable).
- Worker instance reports back account health (hard banned? soft banned? active?) every few minutes, so the operator/admin can see account health across all workers.
- When account is banned, a new one is requested from the APS if available.
## Context
- Trying to deploy a large cluster using Docker Swarm is complicated, as each instance must be configured with their own account(s) and then managed manually. With an Account Pooling Service in place, we can deploy such a system easier, as well as manage the accounts used easier.
## Your Environment
- Docker

**Comment by FrostTheFox** [comment]
Is this not something like what #996 does?

**Comment by huanga** [comment]
Similar, but not quite. From what I can see, #996 offers some account cycling feature, but is limited to a single machine. That is, if I have 10 servers, orchestrated with Docker Swarm, I'd still need to provide each server with its own list of accounts for the instances.

This request would take it a step further by allowing the operator to run a single centralized repository of accounts, and surface them for workers (could be on any machine even across the net in different countries) to use.

**Comment by azd2** [comment]
This does what you want: #1037
I tried the live branch (https://github.com/Shibby7986/PokemonGo-Map , had drob and recreate mysql db for it to work though) Shibby7986 posted there, it works really well.

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
