### ISSUE TITLE
[Feature Request] Display the names of the trainers in a gym

### ISSUE THREAD

**Issue by gatomiaurex** [RocketMap/RocketMap#1148]
I am loving the gym scanning feature and I would like to know if there is a way to do this.

**Comment by mbg032373** [comment]
Just turn on gym info.

gym-info: True

**Comment by gatomiaurex** [comment]
@mbg032373: afaik that doesn't display the names of the trainers in that gym, this is a picture of the map i set up to scan gyms only and no gym showed trainers names

![untitled2](https://cloud.githubusercontent.com/assets/20795984/18236913/83dfb936-72e8-11e6-8e2b-e6878b98792e.jpg)

**Comment by mbg032373** [comment]
Yes, I just noticed that.  I've noticed the trainer names in the database, so I figured that it was it was for.  Why are we bothering to even store the trainer names if they aren't being used for anything?  Odd.

In any event, they are already pulling and storing that information in the database, so the info window would just need to be edited to show them.

**Comment by WhitedragonBC** [comment]
Mouseover the pokemon.

**Comment by gatomiaurex** [comment]
@WhitedragonBC Oh, I am dumb. ._.

But how can I see them in a mobile device? I can see them by hovering the mouse on my PC but when seeing the map on my phone the names don't appear.

Thanks in advance.

**Comment by nhumber** [comment]
at this time you cant @maddhatter is possibly looking to implement something along the lines of a gym details page where this information is viewable on a mobile device also, 

Side note, Samsung galaxy phones can do "hover" and "mouse over" you need to enable it in the hidden chrome browser settings and make sure its enabled in the phone settings, even tho the mouse over or hover then works, you still get no information on mobile,

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
