### ISSUE TITLE
[Feature Request] Exportable, importable notification settings

### ISSUE THREAD

**Issue by SoonDead** [RocketMap/RocketMap#1160]
Everyone has custom preferences about this and setting up the perfect notifications just take over 10 minutes on a mobile device, where it is painful to type in and select items from that custom dropdown list which is already taller than my whole screen when 15 pokemons are selected.
## Solution1

Add a button to export notification settings in json, this downloads it as a json file. Add a button to import the same settings. Everything happens on client side, server is not bothered by this.
## Solution2

Notification profiles. The server could store a notification profile. The clients can save a profile (which uploads it on the server). Clients can select any profile from a dropdown. Selecting a profile which you have set up earlier on an other machine is easy, no need to copy files to your phone and whatnot.

Either of these 2 solutions can be generalized to all client side settings or combined.

Theses would save me a lot of time when I visit a map from a new browser.

Discuss.

**Comment by DiscoTim** [comment]
Maybe something along the lines of this might work as a basis? I'll have to test it out

Export:
`JSON.stringify(localStorage)`

Import:
```
 $.each(JSON.parse(exported_string), function (key, value) {
  localstorage[key] = value
}
```

**Comment by Gallifery** [comment]
It also happened to me that each time I invoke runserver.py on my raspberry pi. The hide and notification settings need to be set again.

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
