### ISSUE TITLE
Not working with SSL

### ISSUE THREAD

**Issue by Zerotask** [RocketMap/RocketMap#1166]
Site / google map ends with an timed out error
## Expected Behavior

running as it did without ssl
## Current Behavior

From 5 starts it only works in 1-2 tries. the other times I see the log is running without errors but when I access the website, then the page is loading and loading and ends up in a timed out error.
And when it's working then max. for 5 mins.
My other sites on the server (running with nginx) are running properly
## Steps to Reproduce (for bugs)

1. added cert and key to config/config.ini
2. add 20 accounts with 1 password to config.ini
3. run (a single) python runserver.py -fl &
## Context

Map isn't working at all.
## Your Environment

ubuntu 16.04, python 2.7, mariadb, activated ssl with http 2 and hsts
newest commit

**Comment by Zerotask** [comment]
Regarding to https://docs.python.org/2/library/ssl.html#socket-creation I've changed in line 250 of runserver.py
`ssl_context = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)` 
to
`ssl_context = ssl.SSLContext(ssl.PROTOCOL_SSLv23)`

and it seems working for me.
Another thing I saw in the chrome dev tools is that the default document has the http 1.0 protocol. I'm using http 2.0 with nginx, so it would be nice to enable that if you choose ssl.

**Comment by Demokdawa** [comment]
I have this problem too !

I'm not alone ;p

**Comment by justsomedudeonthenet** [comment]
To be honest, I don't know why we deal with SSL at all.  It's much better handled by an nginx or apache frontend doing reverse proxy.

I'd rather ditch SSL support in the app, and maybe include some example config files for using it behind nginx and apache.

**Comment by ChipWolf** [comment]
+1 @justsomedudeonthenet

**Comment by neskk** [comment]
SSL doesn't seem to work, this problem also happens to me.
Setup cert and key and everything seems ok for 20min or so and then:

> This site can’t be reached
> xxxxxxx.com took too long to respond.

**Comment by neskk** [comment]
Anyone found a solution for this problem?
This sh*t broken but no one seems to care. Also, why on hell I receive crappy https requests on my "only-server" instances when I'm not using SSL?

**Comment by sebastienvercammen** [comment]
Closed, this is a very old issue. Any feature requests are now handled via http://vote.devkat.org and if any issue reported in the issue is still related to current code, a new GitHub issue should be opened.
