### ISSUE TITLE
[Feature Request] Implementing i18next for translate the gui

### ISSUE THREAD

**Issue by gtuxyco** [RocketMap/RocketMap#1169]
The texts could be translated with just edit a file and would not have to search and edit each text in js

**Comment by DiscoTim** [comment]
there is il8n, in map.js, local files in /static/locales, and you can set your local in the config, but I think at minimum though that should be brought out of map.js and il8n loaded in a global scope.

**Comment by gtuxyco** [comment]
from what I've seen the file in /static/locales is only for the name of the pokemons. 
 I mean the UI messages that are in maps.js and in the html /templates files.
I try to translate to spanish but if i update, I will lose the entire translation

**Comment by DiscoTim** [comment]
well the /static/locales are for anything you see wrapped in il8n() , but a lot of things are not.
the main template files are not localized and definitely should be, and every other text string in the project for that matter :) . i don't think they should be merged that's not localizable, its not really hard and sucks for a lot of people. at least there is some localization.

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
