### ISSUE TITLE
[Feature Request] add repeat appearances filter to stats

### ISSUE THREAD

**Issue by fakemustache12** [RocketMap/RocketMap#1172]
It would be useful to add an appearances filter to the stats page to help in identifying possible nests with repeat spawns of the same pokemon at a given spawn point.

 For example in a given scan area 200 charmanders may have spawned during the selected date range but spread around the entire area without any specific concentration or repeat spawns.

Adding a filter that we could use to only show pokemon with n repeat appearances would help to more easily identify nests.

ie: Repeat Apparances: 5 would only show spawns with 5 or more repeat appearances during the selected date range.

**Comment by darkelement1987** [comment]
It's a bit devious but im using PokeAlarms with Telegram and just search for the specific pokemon and look for duplicate adresses. If it shows (ilke) 2/3 times on the same spot i consider it a nest, but i like your idea.

**Comment by justsomedudeonthenet** [comment]
Isn't this exactly what heatmaps are for?

**Comment by fakemustache12** [comment]
Not exactly, the heatmaps will show red if there is a high concentration of spawns depending on your zoomed in scale. The idea with this request is an option to filter out single spawns and show only spanws with multiple appearances in the selected date range.

Example usage would be: Scan area for one day, check stats for last day set filter to only show spawns with 8 or more appearances at the same point. Check All locations for a given pokemon "charmander" the heatmap would show only the spawns with 8 or more appearances.

This would make it easier to identify nests. Without this doing the same check for All locations could show hundreds of single charmander spawns on the heatmap but spread out over a large area which aren't that useful for research.

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
