### ISSUE TITLE
[Feature Request] / [Design Draft] Scanner algorithum for Spawnpoint Scanning

### ISSUE THREAD

**Issue by evenly-epic-mule** [RocketMap/RocketMap#1175]
Hi there,

I've been thinking about how to make bots hold longer (until they are banned)
and I came up with a small design draft:

Steps:
- Account queue is extended with a last location and last scanned attribute
- Workers aren't bound to a single account
- The worker will select the nearest free account
- update the last location and the last scanned information (to the upcoming location)

Additionally there would be the following extensions for later implementation:
- settable speed (instead of scan delay)
- path finding over google api? (this should be cached! or pre-calculated for the hour)
- scannes between locations (just like the real app does if you run from A to B)

**Comment by sebastienvercammen** [comment]
Closed, this is a very old issue. Any feature requests are now handled via http://vote.devkat.org and if any issue reported in the issue is still related to current code, a new GitHub issue should be opened.
