### ISSUE TITLE
[Feature Request] Spawn point color legend

### ISSUE THREAD

**Issue by Braini01** [RocketMap/RocketMap#1177]
It would be nice to have some explainations of the colors of spawn points that could be toggled on/off so users don't have to learn and guess what they mean.
## Expected Behavior

A little window/pane in the frontend listing the colors and their meaning
## Current Behavior

Users are expected to know or guess the meaning of spawn point colors

**Comment by qpowell** [comment]
I would be happy to help implement this, but I don't actually know what the spawn colors mean :) Are they just representative of the timeframes or is there more to it, like rarity or spawn type?

**Comment by beccasafan** [comment]
@qpowell 

Purple = default
Light blue to dark blue in the 5m before spawn
Green to yellow to red in the 15m of the spawn (same as the scanned circle colors)

**Comment by ChipWolf** [comment]
If you're going to implement that @qpowell, add the legends for range colors and scanned region colors while you're at it ;)

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
