### ISSUE TITLE
[Feature Request] Custom search grid

### ISSUE THREAD

**Issue by Braini01** [RocketMap/RocketMap#1178]
It would be nice to be able to setup a custom search grid, e.g. in a file, that tells at what positions the workers should search. 
## Expected Behavior

A user could create in a seperate tool a set of search locations he is interested in. This gives him the opportunity to just scan his way to work for example or to leave out unreachable areas. In combination with the list of spawn points the user could also use some brain to cover as many spawn points with as less search locations as possible. A computational solution to this would be also very nice but to find the optimal solution is an NP-hard problem, so maybe not very easy and efficient. 
## Current Behavior

Currently users are limited to either hex shape search locations or spawn point based search locations that search in areas that might be unreachable or not of interest and hence are worth to discard.
## Possible Solution

Allow custom search locations that are described in a file.

**Comment by justsomedudeonthenet** [comment]
While this isn't helpful for people without much programming skills, it is certainly possible to do this - make your own spawns.json files containing the areas you want scanned.

**Comment by lisandro52** [comment]
@justsomedudeonthenet Question about the `spawns.json` file: Is it a way to mark new spawns, or simply individual scan areas? Adding spawn with the file would add the spawns to the database, even though they aren't actual spawns?

**Comment by justsomedudeonthenet** [comment]
@lisandro52 a spawns.json file contains the spawnpoints and time they spawn.  When it is used the database is not used for spawnpoints.

**Comment by averylarry** [comment]
. . . effectively making the spawns.json file a list of locations to scan at certain times.  It does not have to be actual spawnpoints.  #990 will do clustering/compression (whatever we call it).
So you could dump the .json file with all spawnpoints, edit it to include or exclude whatever you want (which isn't necessarily easy), run the compression and then enjoy.

**Comment by ChipWolf** [comment]
To all the above comments, it's all well and good generating a spawns.json with the area you'd like to scan. But if you'd like to specify a scan area for your **initial** scan, the @Braini01 has a very decent suggestion.

The area we'd like to scan is very... horizontal? Scanning a large radius, or several radii to generate spawnpoint data is incredibly inconvenient.

**Comment by averylarry** [comment]
@ChipWolf PR #393

**Comment by korlcek** [comment]
A worker could follow a GPX file. These are easy to make with already made tools.

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
