### ISSUE TITLE
[FEATURE REQUEST]  Time or multi-species filtered heatmaps (active spawn density heatmaps)

### ISSUE THREAD

**Issue by EvilLost** [RocketMap/RocketMap#1190]
## Expected Behavior

Heatmap displays all or multiple species simultaneously in the heatmap.
User inputs a time and heatmap only displays all points valid during that time (ToD minus 15 as a general solution)
## Current Behavior

Heatmap displays only 1 species at a time.
Heatmap displays all sightings of a specific species, regardless of the time of the sighting
## Possible Solution

Implement the heatmap before selecting a particular species (allow the species filtration to occur after heatmap creation).
Implement a slider bar that allows the user to select a time. Display all known sightings (based on the species filter above)  that have an active time period (ToD minus 15) during the selected time. 

NOTE: This implementation is definitely not ideal.
## Context

OBJECTIVE:  To be able to see the densest areas of spawn activity at any given time on the hour. For example, what area in my town has the most pokemon (of any kind or of certain kinds) active at xx:31 on the hour?

**Comment by justsomedudeonthenet** [comment]
This is an excellent idea.

**Comment by Spiritvn** [comment]
This should be one page 1 ... very useful  if exist!

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
