### ISSUE TITLE
[FEATURE REQUEST] Visualize spawnrate % of spawnpoints in heatmaps

### ISSUE THREAD

**Issue by duckness** [RocketMap/RocketMap#1191]
## Expected Behavior

Heatmaps should show the spawn percentages (of the spawnpoint) in relation to the color on the heatmap. 
## Current Behavior

Currently the heatmap does not offer much useful infomation especially in a smaller map: a rare pokemon A with a single-spawnpoint nest and a single spawn of an ultra rare pokemon B would both show a similar or identical heatmap, one would need to dig a little bit into the data in order to realise that pokemon A has a nest.
## Possible Solution

For our current varying scale (peg 0% to a color X, and the max spawn % to a color Y), we can simply indicate the maximum spawn% somewhere.
Alternatively, we can have a fixed scale (peg 0% to a color X, and 100% to a color Y), then put a bar in to indicate the gradient(like in this example below); this may be more useful if one wants to compare heatmaps of different pokemon, or across different time periods.
![](https://i.sli.mg/90erE8.png)
## Context

This data would allow one to very easily identify nests, find out the spawnrate of pokemon in a nest, as well as identify other anomalous patterns of spawns.

**Comment by EvilLost** [comment]
and time! yes!

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
