### ISSUE TITLE
Can't scroll stats on multiple browsers after changing "duration"

### ISSUE THREAD

**Issue by leolobato** [RocketMap/RocketMap#1192]
## Expected Behavior

To always be able to scroll the full stats page when using Safari.
## Current Behavior

After changing "Duration", the stats page will be stuck on the top when trying to scroll.
## Steps to Reproduce (for bugs)
1. Launch pokemongo-map on Safari
2. Click on stats
3. Click on full stats
4. Try to scroll the page -- it works.
5. Click on Options
6. Change "Duration" from "Last Day" to "Last 6 Hours"
7. Try again to scroll the page -- it keeps immediately resetting to the top. <<<
## Your Environment
- Latest revision on develop (e92fa83), but it has been happening for a few days.
- Testing on OS X 10.11.6,  Safari 9.3
- Also an issue on latest iOS Safari.

This does not seem to affect Chrome (Version 53.0.2785.89 (64-bit))

**Comment by Saprophator** [comment]
Occasionaly happens on Firefox 48.0.2 too. Doesn't happen with Microsoft Edge.

**Comment by 123456abcdef** [comment]
I can confirm tested on OSX FF 48.0.1 and Linux FF 45.3.0.

**Comment by averylarry** [comment]
Happening for me with Internet Explorer 11.

**Comment by justsomedudeonthenet** [comment]
My testing:

All on windows 10.
No issues with Chrome
No issues with Edge
Easily replicated with IE11

**Comment by spnatinoobprogrammer** [comment]
It seems to me that changing _any_ option in the full stats page prevents scrolling on Safari 10 on macOS Sierra. Not just the duration option. Testing in Chrome, the issue did not present itself.

**Comment by gamemasta0** [comment]
It seems to me that changing any option in the full stats page prevents scrolling on Safari 10 on macOS Sierra. Not just the duration option. Testing in Chrome, the issue did not present itself.

**Comment by tedtim** [comment]
same issue with iOS 10 Chrome and Safari
