### ISSUE TITLE
[Feature Request] Send errors to webhook

### ISSUE THREAD

**Issue by joberembt** [RocketMap/RocketMap#1206]
It would be nice to be able to get errors sent to the webhook and get notified when you have accounts start dropping so that you can do something about it.

## Context

When you get IP banned, or have accounts banned, rather that just hammering away at it, it would be nice if those errors could be sent to the webhook so you could set up notifications that something is awry and attend to it.

**Comment by justsomedudeonthenet** [comment]
That's not a bad idea, and definitely something to look into when improving webhooks

**Comment by Becold** [comment]
Make an argument please.
I dont want to increase the wh-threads for something I dont use :)

**Comment by jorgebsa** [comment]
I had suggested this back on feathub, would find it incredibly useful as well. Receiving notifications of accounts failing would help me a lot when managing workers. Using the new CSV file method already improved this, but sometimes one of the accounts might be banned and the others are on cooldown, resulting in hour gaps for an area. Being actively notified about this would allow us to remedy the situation much much quicker

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
