### ISSUE TITLE
[Bug]Loc/Hex calculator is wrong

### ISSUE THREAD

**Issue by djgreg13** [RocketMap/RocketMap#1216]
## Expected Behavior

`python ./runserver.py -ns -ac ../accounts/strasbourg.csv -l 48.580032,7.737381 -st 4 -w 10 -j -sn worker1
` is the center of beehive

If i put step = 4  hex calc, this is the result (green)

If i want to have polygons tangeant, i need to put step = 8 on my server or step=2 on hex calculator (red polygon is result with step=2)

![pokemon_go_map_-_2016-09-08_18 18 19](https://cloud.githubusercontent.com/assets/3840229/18357339/edfb2c14-75f0-11e6-8155-c6d7dc119862.jpg)

![copie_de_lat_long_hex_calculator_-_google_sheets_-_2016-09-08_18 22 24](https://cloud.githubusercontent.com/assets/3840229/18357411/37088f32-75f1-11e6-8359-503567e52a15.jpg)

**Comment by beccasafan** [comment]
Can you try using the location generator without the spreadsheet?

https://github.com/beccasafan/PokemonGo-Map/blob/beehive-doc-update/docs/extras/beehive.md

Working on getting the documentation updated with #1221...

**Comment by djgreg13** [comment]
I want to cover only 3 hexagon top right and 2 hexagon bottom and 3 hexagon top left

**Comment by ultrafunkamsterdam** [comment]
why not go to latlong.net. choose positions, and ready to go?

**Comment by sebastienvercammen** [comment]
Closed, this is a very old issue. Any feature requests are now handled via http://vote.devkat.org and if any issue reported in the issue is still related to current code, a new GitHub issue should be opened.
