### ISSUE TITLE
[Feature Request] Extra parameter in accounts.csv for 'preferred proxy'

### ISSUE THREAD

**Issue by ChipWolf** [RocketMap/RocketMap#1223]
@FrostTheFox suggested I post this.

Currently, we format the accounts.csv as follows;
`auth,username,password`

If we had an _optional_ parameter at the end for a 'preferred proxy', that would help fool the API into believing the account is logging in from the same location and would inevitably reduce bans.
The new format would be something along the lines of;
`ptc,someuser,somepassword,http://127.0.0.1:80`

This would prompt the worker to use the specified proxy for that account as a preference, until the account or the proxy fails and they go back into the queue.

I'm currently in the process of generating accounts with individual proxies to reduce bans. People would be able to introduce lists of proxies into their account generation workflow. They would be able to output a list of generated accounts with the proxies used to generate those accounts. That list could then be used as an accounts.csv for PokemonGo-Map to keep everything consistent.

---

Another viable addition post the above would be to have a live output to file of all the in-use accounts and the proxies tied to them. This would allow the user to restart the worker where it left off with the same proxy-account arrangement.

If I've been unclear or anyone has a question, please feel free to comment.

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
