### ISSUE TITLE
[Bug] Times Shown in 'Full Stats' Section Are Disappear Times

### ISSUE THREAD

**Issue by pbtura** [RocketMap/RocketMap#1227]
When viewing pokemon in the 'full stats' view, the times listed as 'last seen', and the 'appearances' popover on the 'all locations map', show the time the the pokemon disappeared rather than when it appeared.
## Expected Behavior

Should show the 'appear' time to match the time listed on the spawnpoint.
## Current Behavior

When viewing pokemon in the 'full stats' view, the times listed as 'last seen', and the 'appearances' popover on the 'all locations map', show the time the the pokemon disappeared rather than when it appeared.
## Steps to Reproduce (for bugs)
1. Run a scan of a known single point nest for long enough to record multiple spawns. As an example, there is a nest that spawns Mankey once an hour at coordinates 41.239540,-77.019788
2. Open the stats menu and click on 'full stats'.
3. If the scan is being run with a fresh database, the 'last seen' field for Mankey will display 'X:53:24'. The correct time, as listed on the spawn point should be 'X:24:X'.
4. The same behaviour can be seen in the 'Times' list of the pop-over that displays when mousing over a pokemon in the 'all locations' maps.
## Your Environment
- Version used: 3.1.0 (dev branch)
- Environment name and version: Python 2.7
- Operating System and version: Windows 10 (x64).

**Comment by hkuiyo** [comment]
I've encountered this too. :) Missed quite some pokemon due to this, until I finally found out the time shown is indeed the despawn time.

**Comment by sebastienvercammen** [comment]
Closed, this is a very old issue. Any feature requests are now handled via http://vote.devkat.org and if any issue reported in the issue is still related to current code, a new GitHub issue should be opened.
