### ISSUE TITLE
[Feature request] Start with search paused

### ISSUE THREAD

**Issue by Slivo-fr** [RocketMap/RocketMap#1233]
Add some params to start the map with search paused.
## Expected Behavior

The map start, and wait for search control switch to enable scan before
## Current Behavior

I cannot start the map without starting the workers

**Comment by KoffeinKaio** [comment]
Run a python process with -os? It will just be the map without any scan workers.

**Comment by Slivo-fr** [comment]
I tried, unfortunately, the search control switch has no effect in this case.

**Comment by itayo** [comment]
do you mean like #1188 ?

**Comment by Slivo-fr** [comment]
Yeah :)

**Comment by Cartman123** [comment]
In the meantime, here's how I'm doing it:
On runserver,py find:
```
    if not args.only_server:

        # Check all proxies before continue so we know they are good
        if args.proxy:

            # Overwrite old args.proxy with new working list
            args.proxy = check_proxies(args)
```

replace with:
```
    if not args.only_server:

        # Check all proxies before continue so we know they are good
        if args.proxy:

            # Overwrite old args.proxy with new working list
            args.proxy = check_proxies(args)

        if not args.no_server:
            pause_bit.set()
```


The correct way is creating a command line argument, but this does the trick if you need a simple fix.

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
