### ISSUE TITLE
[Feature Request] Close InfoWindow with second click on item

### ISSUE THREAD

**Issue by FabianSperrle** [RocketMap/RocketMap#1237]
I scan a larger area than I have typically open in my map, which is panned to the area that I can comfortably reach within 15 minutes by foot. When I click on an object close to the border of the screen (mostly to disable the bounce notification) the info window opens. With autoPan disabled, the close button is off-screen quite often. As a result I have to pan the map or zoom out to be able to click the close button. This is tedious, and leads to notification spam from neighboring spawns. 
## Expected Behavior

A second click on the item should close the info window again
## Current Behavior

Info window stays open until closed by clicking the little x
## Possible Solution

Save the current state in the marker, and adapt the click handler appropriately
## Steps to Reproduce (for bugs)

1. Open the map
2. Click a Pokémon close to the border
3. Impossible to close the info window without zooming or panning
## Your Environment

- Version used: 73c68b2902a628483340b165378b2f6f167c3956
- Environment name and version (e.g. Python 2.7): python 2.7
- Operating System and version (desktop or mobile): Chrome on OS X/Android 6.0

**Comment by Mr-Groch** [comment]
PR #15

**Comment by FabianSperrle** [comment]
Any info on why that didn't get merged? Did it just get lost in the amount of issues and PRs, or was there any opposition?

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
