### ISSUE TITLE
[Feature Request] Request notification permission only when needed - not upon page load

### ISSUE THREAD

**Issue by CoolCanuck** [RocketMap/RocketMap#1242]
(not using template, as isn't usable for requests) 

It would be nice to request permission ONLY after setting up the first notification. There is no point in displaying a prompt for notification if the user has never set up a notification. ;)

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
