### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by Gallifery** [RocketMap/RocketMap#1248]
## Expected Behavior

I think it would be nice to add the sorting function to the 'stats' bar. So that when you click on 'Name', then the pokemons are sorted from A-Z. When you click on it again, the pokemons are sorted from Z-A. Likewise, when you click on 'Count' or '%' the pokemons are sorted from small to large in terms of 'Count' or '%' and when you click on 'Count' or '%' again, they are sorted from large to small.
## Current Behavior

Current behavior is that there is no action assigned when clicking 'Name', 'Count' and '%', therefore no sorting functio n.
## Steps to Reproduce (for bugs)

1.
2.
3.
4.
## Your Environment

- Version used:
- Environment name and version (e.g. Python 2.7):
- Operating System and version (desktop or mobile):

**Comment by averylarry** [comment]
Just double checking -- you are aware that you can sort them, right?  In the options?  Noting that sort by name has ascending/descending reversed.

**Comment by Gallifery** [comment]
@averylarry  I am not aware they can be sorted in the 'Options' bar on the left of the screen, not can I find them. Can you be a bit more specific where that Option is? Is it under 'Marker settings', 'Location and Search settings' or what?

**Comment by averylarry** [comment]
Oh sorry - you said full stats so I thought you were talking about after you click the full stats link instead of the slide out small stats.
In the stats small window, click full stats. Then there are options in the options tab.

**Comment by Gallifery** [comment]
@averylarry  Ah, I see what you mean as well. I never pressed that 'full stats' button. I thought it was something like you see on a websire 'press this link to downlaod if the download doesn't happen automatically in 15s'. So I thought it was there if the information in the slider does not come out after you press stats. Anyway, I still think it's a good idea to add the feature at the beginning of this post.

**Comment by averylarry** [comment]
I'd like to try and piggy back onto this feature request.  I'd like the full stats page to have a table/chart option which (like the original request) could be sorted by column.

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
