### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by ameel** [RocketMap/RocketMap#1251]
Search (through a search bar) scanned area for pokemon (by name) that has spawned.

List of current appearances on a side bar will show where the pokemon has currently spawned

User can navigate between the instances by clicking through the list which then jumps around the map to the location of the selected instance.

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
