### ISSUE TITLE
Wrong despawn time for pokemon which stays more than 15 minutes

### ISSUE THREAD

**Issue by cecca00** [RocketMap/RocketMap#1258]
## Expected Behavior

If we have the spawnpoint in database and know the expected despawn time for that specific spawn point, correct disappear time should be shown on map and sent to webhooks.
Unknown disappear time should be reported if we don't have the information yet.

## Current Behavior

Disappear time is assumed to be now+15 minutes. This is also sent to webhooks which makes pokealarm send notifications with wrong disappear time, which repeats if the location get scanned again after the reported disappear time.

Example:
![example](https://cloud.githubusercontent.com/assets/11209870/18411031/45ec5af4-776f-11e6-93dc-f9d9c2ed4a84.png)
notifications from slack on the left, screenshot of map taken at 12:28 on the right
## Your Environment

- Version used:
- Environment name and version (e.g. Python 2.7):
- Operating System and version (desktop or mobile):

**Comment by tjhuff** [comment]
This post on pokemongodev discusses the different spawn point types.  PokemonGo-Map doesn't handle them all correctly as of now.

https://www.reddit.com/r/pokemongodev/comments/4yzqc2/spawn_point_types_clearing_confusion/

**Comment by sebastienvercammen** [comment]
Closed, this is a very old issue. Any feature requests are now handled via http://vote.devkat.org and if any issue reported in the issue is still related to current code, a new GitHub issue should be opened.
