### ISSUE TITLE
[Feature Request] -- Disable or alter zooming on 'Click to load' web notifications.

### ISSUE THREAD

**Issue by kbtbc** [RocketMap/RocketMap#1263]
The request concerns the built-in map web notifications (the ones that are user defined).

My map is usually always scaled so that I can see the entire area I'm scanning.  If I get a web notification and 'click to load' the map zooms in so tight it is actually a problem and not a help.

I would prefer to have the map remain to my current scale, and some other type of action occur (such as a red circle).   They are already 'hopping' for quick spotting, the zooming feature just disrupts the entire map, and is usally so close, that I can't immediately recognize the area w/out zooming out again anyway. 

Thank you!
p.s. I know this has been requested before, but also being able to pre-load notification settings would be another great feature.  :-)

**Comment by CtrlAltDefeat94** [comment]
how to people still not know that there's feathub...

**Comment by kbtbc** [comment]
the feathub was killed ... how do people not know that?

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
