### ISSUE TITLE
No keyboard pop out in Options Setting on Mobile device

### ISSUE THREAD

**Issue by alexcan97** [RocketMap/RocketMap#1273]
When setting hide pokemon or notify pokemon, after click hide pokemon box, there is no keyboard pop out on mobile device, only pop out the pokemon list for select. 

this is happened on version 3.2
## Expected Behavior

on Version 3.1, after click the box, a keyboard will pop out, after typing, the filter pokemon list will show for selection.
## Steps to Reproduce (for bugs)

1. Click Options
2. Click Marker Settings
3. Click Hide Pokemon
   4.
## Your Environment

- Version used: 3.2.0
- Environment name and version (e.g. Python 2.7):
- Operating System and version (desktop or mobile): mobile

**Comment by sebastienvercammen** [comment]
Closed, this is a very old issue. Any feature requests are now handled via http://vote.devkat.org and if any issue reported in the issue is still related to current code, a new GitHub issue should be opened.
