### ISSUE TITLE
[Feature Request] - Include Gym Info in Webhook posts

### ISSUE THREAD

**Issue by ashleykleynhans** [RocketMap/RocketMap#1286]
Thanks very much for creating this awesome tool, I'm finding it very useful.

The webhooks work really nicely, but I notice that the feature that you recently added to display gym info in the web frontend, doesn't send the detailed gym info (list of Pokemon, CPs, trainer names, etc) to the webhook.

It would be awesome if you could include these details in the webhook please.

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
