### ISSUE TITLE
[Feature Request] Pokemon details in gyms

### ISSUE THREAD

**Issue by SoonDead** [RocketMap/RocketMap#1290]
The data is already pulled into the gympokemon table. It would be great if the web UI could show it somehow.

The things I'm interested in are: Pokemon IVs and Movesets. It would be very helpful to prepare against certain movesets and checking out pokemon stat-by-stat would be great to compare our ~~dic...~~ pokemons.

![gympokemon](https://cloud.githubusercontent.com/assets/988167/18463208/94c8992e-7988-11e6-870e-941261c47d43.png)

This layout is obviously just a mockup, but the important details:
- The huge logo, and the long (Gym owned by: \n Team Valor) is a little long and takes up unnecessary space.
- The red boder indicates hover or explicit click toggle. Click is much more usable on mobile.
- The pokemons' tooltips are unusable for mobile, so trainer name is moved under pokemon.
- No weight/size.

The gym details popup should have a fixed size, so clicking mons with longer trainer name or longer move name does not resize it and make it scroll on a small screen. If no pokemon is selected, the team logo, or a placeholder of similar size could be shown.

**Comment by nhumber** [comment]
![screenshot_20160913-225229](https://cloud.githubusercontent.com/assets/9411415/18498542/31d6eeba-7a05-11e6-943e-74c135ffb5d1.png)

**Comment by delenca** [comment]
Id love to get a copy of that modification you did.

**Comment by nhumber** [comment]
I submitted a pull already, #1302

**Comment by delenca** [comment]
well doesn't work for me.

**Comment by nhumber** [comment]
what doesnt? did you pull the changes? and rebuild with npm install,
because you need to, this was just a minor text fix, it should work for everyone.

**Comment by delenca** [comment]
Pulled it then merged it the did install and all gyms still look the same I have to mouse over to view pokemon in the gym.

**Comment by SoonDead** [comment]
@nhumber check out my pull request

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
