### ISSUE TITLE
Spawn point scans don't show Pokemon after scanning active spawn point

### ISSUE THREAD

**Issue by baottousai** [RocketMap/RocketMap#1291]
Expected Behavior

Pokemon should show up on map after it scans a spawn point after it turns green

Current Behavior
Spawn point turns green, which means a Pokemon should be there now. Spawn point is scanned after it turns green but it doesn't show a Pokemon even though a Pokemon should be there. Pokemon only show up if scan overlaps with previously spawned pokemon.

Python 2.7
Windows 10

**Comment by SoonDead** [comment]
This seems to be an issue on your end as spawnpoint scanning works fine.

My best guess it that your clock is early so it scans before actual pokemon spawn. Or the machine that collected the spawnpoints had it's clock late. Happened to me once. Try to adjust your clock by setting it back a minute to test it out. If it is the case, try to adjust the time of the spawnpoints. I'm sure people on the discord will help you on that.

**Comment by DiscoTim** [comment]
as @SoonDead says, probably your computer clock is off a bit. synchronize the time in the control panel -> date and time -> internet time

**Comment by jtp10181** [comment]
I highly recommend eccomend this for Windows http://www.timesynctool.com/

**Comment by sebastienvercammen** [comment]
Closed, this is a very old issue. Any feature requests are now handled via http://vote.devkat.org and if any issue reported in the issue is still related to current code, a new GitHub issue should be opened.
