### ISSUE TITLE
[Feature Request] Rescan location that returned an error

### ISSUE THREAD

**Issue by Slivo-fr** [RocketMap/RocketMap#1294]
Using SS, requeue and rescan spawn after a short while if it failed at first
## Expected Behavior

Map should not give up on any spawn
## Current Behavior

If an error occur, the spawn is ignored and remain unscanned
## Context

Running SS with enough account to make sd useless on a small area

**Comment by filippounitn** [comment]
+1

**Comment by Samael27** [comment]
+1

**Comment by Slivo-fr** [comment]
Bump, we miss pokemons so often because of this, even more with clustered spawnfile :/

**Comment by Samael27** [comment]
Still the same issue for me too :(

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
