### ISSUE TITLE
Mobile Browsers Pokemon filter selection window migrates to the top.

### ISSUE THREAD

**Issue by CometX** [RocketMap/RocketMap#1304]
## Current Behavior

On mobile browsers: adding pokemon to the exclusion list one after another migrates the window that remains up towards the top. Slowly but surely, it ends up off the screen. Seen on Chrome/Safari on IOS.
## Possible Solution

Not sure, this menu seems to be causing issues for a long time now.
## Steps to Reproduce (for bugs)
1. Open Browser
2. Open Options
3. Add Pokemon to filter
4. Watch remaining Pokemon selection window rise as you do this over and over.

Thanks!

**Comment by mew905** [comment]
I've had a couple users complain about this as well, no idea what's causing it, but they said shrinking the text size helped on a Galaxy S6.

**Comment by sebastienvercammen** [comment]
Closed, this is a very old issue. Any feature requests are now handled via http://vote.devkat.org and if any issue reported in the issue is still related to current code, a new GitHub issue should be opened.
