### ISSUE TITLE
[FEATURE REQUEST] Pull accounts from Database

### ISSUE THREAD

**Issue by KoffeinKaio** [RocketMap/RocketMap#1310]
I think it would be nice to have the accounts in the Database.
Running multiple processes with 5-25 workers you'll need an extra csv for each one. (and you cant share them because the process would always pull the first accounts)
## Expected Behavior

My Idea is some sort of Table with all accounts and a pool_id column. This way it's possible to restrict $num accounts to $worker_with_poolid. If no id is given, the worker is free to choose as many as he wants. 
Used accounts could get flagged with a "in_use=1" status and some other informations.
The -ac argument could be used to load the db with accounts. This won't implement a new account handling system, just sit on top of the current one.

Your opinions? Maybe if I find time I could do it myself, but not sure.
## Current Behavior

Need a csv for each process and no information is saved after process restart (like $account is banned for sure).
## Possible Solution

Move to DB.
## Your Environment

- Version used:
- Environment name and version (e.g. Python 2.7):
- Operating System and version (desktop or mobile):

**Comment by crckdns** [comment]
The idea isn't new, but nice...
yet there is a flaw in it.
The risk of getting a ban will jump up if you pull an account, use it... then stop the search process (for some reason like changing settings) and start again~ there is a chance that the process will now pull other set of accounts.
Now another process pulls the just-used accounts and uses them ~100km away (widespread scan) ..voila, the accounts made a huge jump in short time, triggered.

**Comment by KoffeinKaio** [comment]
If you order Thema by (for examples) an id, the behaviour to csv Accounts wouldnt Change. You could implementiert something like 'last Position' and use One frer acc near your current searching pos.

**Comment by jorgebsa** [comment]
There's a PR already for this: #1037, but like i commented there, do not expect this to be merged unless a fix for the teleporting is implemented along

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
