### ISSUE TITLE
[FEATURE REQUEST] Add CP of scanned Pokemon

### ISSUE THREAD

**Issue by Shentang** [RocketMap/RocketMap#1311]
Since #1272 I tought it would be awesome to know what is the CP of a specific pokemon, for at least your level (most of us will be 30 in no time, and above 30lvl all mons are the same).

Thus, instead of scanning IV and moveset with random accounts, let us choose specific accounts for that job and add a CP field when clicking on a found pokemon. Having specific iv-scanning accounts would also reduce eventual bans on the rest that are just jumping around.

**Comment by jorgebsa** [comment]
May be completely wrong, but wouldn't the requester account need to be at the same level of your interest, such as lvl 30? I'm assuming IVs and Move set scanning works simply because they are the same for every trainer that encounters that pokemon, no matter their leve. But afaik the cp is completely dependent on the lvl of the trainer who encounters the pokemon, and thus a lvl 1 scanner would find ridiculously low CP pokemon every time.

**Comment by Shentang** [comment]
>wouldn't the requester account need to be at the same level of your interest, such as lvl 30

Yes, but you can already get your hand on 30lvl for low cost (1$ as far as I remember?) or just create one yourself.

**Comment by ottowayne** [comment]
I don't like this idea.
While I'm convinced adding IV information is a good idea, I draw the line at encouraging people to buy bot accounts or use bots themselves.

**Comment by Badiboy** [comment]
CP depends on player level and is not equal to everyone, including scanner. Only IV can be shown and there are set of such PRs.

**Comment by davidhouweling** [comment]
Do we know how the IVs are calculated at all? I haven't dipped into the code at all so thought I'd just ask anyways.

Does the server tell you the IV or does it tell you a percentage? If the server tells you the IV then yea its pretty much impossible to know, but if it's a percentage (or some number that helps the app determine the IV) then that would be a good starting point?

**Comment by MJ869** [comment]
PokeAlert's latest release claims to have the feature: https://github.com/PokeAlert/PokeAlert/releases

**Comment by neutron666** [comment]
It could just be a option to have extra accounts that are used for encounter only, this would be a nice addition.

**Comment by CL04k3R** [comment]
Pointless...

**Comment by davidhouweling** [comment]
@CL04k3R why do you think its pointless? For me personally, if i saw on the radar that there was a pokemon i'd caught before, but this one was higher CP than any I had, i would definitely make the effort to go catch it. If it was pretty weak, i'd not bother. Definitely not pointless.

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
