### ISSUE TITLE
Notification via Android

### ISSUE THREAD

**Issue by irus99** [RocketMap/RocketMap#1313]
When I add pokemon to the notification queue, it not only doesn't notify me it also doesn't show all the pokemon on the screen. Am I doing something wrong or is this a known bug?

**Comment by DiscoTim** [comment]
notifications don't work at all on android chrome, its a known long standing bug, you have to leave them disabled or they break they app... you could try pokealarm.

**Comment by irus99** [comment]
I will look into that. Thanks

**Comment by AddisonG** [comment]
I modified my server to send me an email when something good spawns. It works pretty good (though I sometimes get 2 or 3 emails about the same Dragonite - who cares? It's a Dragonite!). You could try the same?

**Comment by jorgebsa** [comment]
Why don't you guys use something already tested and proved like [PokéAlarm](https://github.com/kvangent/PokeAlarm) to get you notifications?

**Comment by DiscoTim** [comment]
@irus99 is this your map, or you are using someone else's? i just assumed it was  your own, in which case you'll be able to set pokealarm up. if you are using someone's else's they'd need to set it up so pokealarm can work for you. if you're sharing with anyone, you'll need to set things up so it works for them..

**Comment by irus99** [comment]
no I'm using my own map so I can use pokealarm. I have not looked to much into it but it doesn't seem like you can set it up to notify you based on IVs I would love if it could do that.

**Comment by DiscoTim** [comment]
it doesn't, it would need this project to provide the iv's which it doesn't currently.

**Comment by nhumber** [comment]
it definitally does, im using it myself, check the IV pr and go over to pokealarm and look at pull req. its there and working perfect

**Comment by DiscoTim** [comment]
@nhumber your right.  if he merges a pr in this project and merges a pr in pokealarm, it definitely will support it :)

**Comment by Mr-Groch** [comment]
PR #623 fixes that, I'm using this few weeks and is working fine on my Android Chrome. It has some conflicts with develop branch, but it's not that hard to resolve manually

**Comment by irus99** [comment]
But it doesn't seem that PR #632 works with getting the IVs so I guess i'll just wait until they merge them.

**Comment by sebastienvercammen** [comment]
Closing this issue because it's very old and no longer relevant to the current codebase. If the issue still persists for you today, comment on this issue to reopen it with new details (logs, screenshots).
