### ISSUE TITLE
FEATURE REQUEST: Add option to scan lured modules every 3 minutes in Spawn Scan mode

### ISSUE THREAD

**Issue by Shentang** [RocketMap/RocketMap#1320]
There's a nice PR #1079 that allows to finally see what's on a lured pokestop. But since most of us now use spawnscan, it's totally useless - we can't really make a use of it unless we scan the lure constantly with the old algorithm and step 2.

My feature request here is to scan every lured pokestop every 3 minutes to show it pokemons that #1079 is now showing.

**Comment by StickyRoad** [comment]
I think this should be done by when the spawn scan recognizes the pokestop is lured (which it will do with or without  scan close the pokestop) it will allocate  worker for that pokestop for the remainder of its lure and scan at 30 second intervals. Thats how i would go about it. this way you would not use so many workers scanning pokestops for no reason.  Plus you can guarantee scanning every pokemon thats lured.

**Comment by Shentang** [comment]
Why waste 6 scans if new pokemons are showing up every 3 minutes?

**Comment by StickyRoad** [comment]
Edited* I realized as soon as i posted! none the less this is a better method.

**Comment by Shentang** [comment]
No worries :)

**Comment by StickyRoad** [comment]
this needs to be sorted ASAP in my opinion. The Lured pokemon issue has set so many things back in regards to this development. -ss being one of them.

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
