### ISSUE TITLE
[Feature Request] Show gym scan radius

### ISSUE THREAD

**Issue by SoonDead** [RocketMap/RocketMap#1321]
Would be great to see how far a scan is from specific gym. Would be easier to spread out scanners just for gyms.

**Comment by beccasafan** [comment]
Is this what you're going for? #861

**Comment by SoonDead** [comment]
Yep

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
