### ISSUE TITLE
[Feature Request] Clicking Spawn Point Shows Spawn History

### ISSUE THREAD

**Issue by dloew** [RocketMap/RocketMap#1324]
Provide a way to show what and when mons spawned on a certain spawn point.  Potentially show History under the "Every hour from..." text or maybe a History link to a new popup that shows history for the spawn point.  Similar when viewing Stats>All Location for a specific mon.

**Comment by ottowayne** [comment]
#669

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
