### ISSUE TITLE
Suggestion: -gi flag playername visable as mobile browser has no image mouse/over label

### ISSUE THREAD

**Issue by edevnull** [RocketMap/RocketMap#1325]
When using the -gi flag the gym information is pulled for a gym. In a web-browser on PC you can "mouse over" the pokemon and get the playername + level. However on a mobile device it is not possible to get this information.
## Expected Behavior

Show the playername by default also or make it mobile accessible as it is more easy to see in which gyms you already are by checking your name in the list. With 10+ gyms owned it is hard to keep track of this.
## Current Behavior

Shows only pokemons and it's CP, not the playernames only when you mouse-over on the pokemon icons.
## Possible Solution

Show the playername after the CP value (yes the string of text might be too long and not an elegant solution).
## Steps to Reproduce (for bugs)

See above.
## Context

Keep more easy track of which gyms you are currently in.
## Your Environment
- Version used: latest git pull
- Environment name and version (e.g. Python 2.7): python 2.7
- Operating System and version (desktop or mobile): raspberry

**Comment by Dagothur** [comment]
#1316 ?

**Comment by drallieiv** [comment]
I think this implementation is better then full side bar.

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
