### ISSUE TITLE
[FEATURE REQUEST] Hide Pokémon by < IV

### ISSUE THREAD

**Issue by darkelement1987** [RocketMap/RocketMap#1337]
## Expected Behavior

In addition to PR #1272 it would be nice if we had a IV filter to hide specific pokemon that meet the IV you entered.

Fill in a number (in % of IV) to hide specific pokemon, example, fill in '90' and all pokemon below 90% IV will be hidden on the map.
## Current Behavior

Map doesn't have this filter yes
## Possible Solution

Map needs changes in map.js and template/map.html
## Steps to Reproduce (for bugs)

1. Edit .js files
2. Edit the templates/map.html file to include the filter
## Your Environment

Python 2.7 / #1272 / Win 7

It should look like the screen i attached:
![marksettings](https://cloud.githubusercontent.com/assets/21128187/18635300/d70fca0e-7e84-11e6-889b-942f2de647fa.png)

**Comment by springjools** [comment]
It should say "Hide Pokémon with IV lower THAN". Then refers to time.

Also PR1272 isn't official yet.

**Comment by darkelement1987** [comment]
Im Sorry for the typo. Im from the Netherlands

Op 20 sep. 2016 12:07 schreef "Jools" <notifications@github.com>:

**Comment by darkelement1987** [comment]
Well, now that it's merged, it might be interesting :)?

**Comment by hkuiyo** [comment]
I would say this goes a bit further than just hiding any < 70 IV? I think you would really like to specify these filters per Pokemon.

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
