### ISSUE TITLE
Getting 403 random responses from niantic server for one specific worker at a time

### ISSUE THREAD

**Issue by vyruz1986** [RocketMap/RocketMap#1338]
I'm not sure this is a bug/issue, but at least something which requires a thorough investigation. I tried putting this on the discord help channel, but got no response. Also given the complexity of this I don't think a scrolling chat where 15 other issues are being handled by various people is the correct place to research this. I will try to explain the issue I am having as best as possible below.  
I am not creating this issue just to solve my own problems, but because I believe there is a potential room for improvement in the way PGM (or pgoapi, not really sure...) handles 403 responses from the niantic server.

I run a relatively small PGM service for the small town I live in. We're talking 1671 spawn points being scanned (using `-ss`) from MySQL database over a `-st 21` radius (actually gathered using `-st 20` hex scanning).  
I run scan this area with an accounts.csv file containing 20 accounts, and give the search process 10 available workers (`--workers 10`).
The search process is told to use the tor service I have running as a proxy, using `-proxy socks5://127.0.0.1:9050`. I do this to prevent coming from the same IP address and getting banned.
I have been getting random occurrences of the following line in my logs:
`Exception while downloading map: Seems your IP Address is banned or something else went badly wrong...`
This will start with just one of my 10 workers, it will retry 5 times using the same account, then switch to one of the other free 10 accounts that remain. The previous account will be flagged as bad and have a cool off timer put on them, causing the following log lines to appear:  
`[account-recycler][        search][    INFO] Account <account name> needs to cool off for 7173 seconds due to failures`
However even with the new account the same error will keep happening. Sooner or later one of the other workers will run into the same problem. This keeps accumulating until all accounts have been flagged as bad and have cool down timers on them, rendering the scanner out of order. When the cool down timers of the first accounts start to expire, the connections are retried and at this point everything slowly starts working again. However if I don't wait for the cooldown timers, and just kill the searcher process and restart it, everything works again right away.

I certainly don't know all there is to know about networking, pgo API servers and HTTP requests/responses, but at least I know a fair share, and given this knowledge, this behavior didn't sit right with me.
As I see it, the Niantic PGO API server can only use 2 kinds of counter measures to block scanners:
- Block/ban based on IP being used
- Block/ban based on account being used

If I were to be banned based on my IP (which is a tor IP), I would expect the other workers to stop working around the same time, but they remain working even several hours after the first worker started reporting it's banned.
If I were to be banned based on my account, I would expect the same worker which had problems with account x, to work fine again after switching to account y.
If I were to be banned on either of the above, or even both at the same time, I would **not** expect for things to start working again after killing and restarting the search process.

Because I had these doubts I asked on the discord help channel, and was told to enable debug logging (`-vv`), which I did and waited for the problem to occur again, which it did after just over 3 hours.

The problem only showed for a couple of minutes, which to me fortifies the point that this is not a ban on niantic's side, why would they only ban for a couple of minutes? Could it be the tor proxy which is acting up? Still the PGM script should not treat this as a niantic ban (because other workers are still doing fine) and set accounts to cooldown mode.
I have now enabled tor debug logs and will report back when the issue occurs again. In the normal tor logs nothing strange could be seen around the time the errors happened.

5 hours of debug logs are quite big (230MB), but I feel they should be available to anyone investigating this issue, so I've put them on a shared onedrive folder: [link](https://1drv.ms/t/s!AvhWSkEmBKJHwXvAzQKpOmOsww5h)
You'll find 3 files in this folder:
- pgm.txt: complete logfile starting at 13.10h running until 17.33h
- search-5.txt: Snippet of all search-worker-5 logs of the first problem occurance at 15.53h.
- search-9.txt: snippet of search-worker-9 logs around the same time, showing this worker has no problem searching

I'll provide a list of noteworthy points (line numbers) in the big logfile:

```
- 972475: Start of search at coords which result in first error occurance (search-worker-5)
- 972678: HTTP 403 response on POST request for search-worker-5
- 972680: Logging indicating IP might be banned or ...
- 974716: 2nd HTTP 403 response on POST request for search-worker-5
- ...
- 981532: search-worker-5 reports account thezw4nd3r3r326 failed scan more than 5 times, switching accounts
- 981534: search-worker-5 starts using account thezw4nd3r3r331 (unused so far!!)
- 983438: search-worker-5 does successful login with account thezw4nd3r3r331
- 984242: search-worker-5 gets again HTTP 403 response on first POST request attempted with account thezw4nd3r3r331
- 1002140: search-worker-5 again switches accounts after 5+ failed scans
... search-worker-8 and 9 also start having problems
- 1051184: search-worker-5 works again! HTTP 200 response on POST request
```

After analyzing the log files it seems what triggers the error is a HTTP 403 (forbidden) response from niantic servers. This keeps going on until either search process is killed/restarted or cooldown timers of accounts expire. Other workers can be seen getting valid HTTP 200 (OK) responses around the same time and later on in the logfile.
## Expected Behavior

Workers reset themselves after 403 errors to successfully resume communications with niantic server.
## Current Behavior

Worker encounters problem, retries 5 times with same account, this fails.
Worker then uses next available account, which also fails 5 times.
This continues until all available accounts are in cool down mode.
## Possible Solution

Since killing/restarting the search process seems to fix the issue, it should be possible to reset individual workers in such a way that they work correctly again, without waiting for the account cooldown timers to expire
## Steps to Reproduce (for bugs)

Leave search process running for several hours
## Context

See explanation/description on top of page
## Your Environment
- Ubuntu 16.04 server
- VPS rented server with 300GB SSD storage, quad core CPU and 12GB of RAM
- 100Mbit down/up link
- PGM installed as per wiki instructions
- Using tor socks5 proxy on 127.0.0.1:9050 for all PGM traffic (proxy configured in `config.ini`)

**Comment by crckdns** [comment]
it seems that they turned the SafetyNet checks on serverside~

**Comment by FrostTheFox** [comment]
Here's the thing: The account is sleeping because it's receiving a 403 unauthorized from Niantic's servers. Why you're getting this? Well, that's usually due to an IP ban as the error indicates. The accounts sleep because subsequent logins from an account that has appeared on a 403d IP address usually is quite suspicious and could end up with an account flag. What could be happening is something with the Tor protocol, when all the accounts are sleeping, you're eventually routed through a different exit node, therefor giving you a new IP and allowing scanning to continue. You can change the time for an account to sleep using -ari 

Resetting workers manually I suppose could be a function done via the status page potentially, but if the accounts are sleeping they're usually sleeping for a good reason (other than that integer, not 'str' error or whatever >:( )

**Comment by vyruz1986** [comment]
I forgot to mention, but I kept an eye on my 'public' tor IP by doing these calls regularly:
`curl -x socks5://127.0.0.1:9050 http://ipecho.net/plain'
into a separate log file, before, during and after the errors are happening, my public tor IP does not change.
In fact my tor IP only seems to change when I restart the tor service (`service tor restart` in ubuntu)

Would you agree it is strange that an account and/or IP seems to banned for only a couple of minutes, or starts working again right after I kill/restart the process? Or am I missing something that might explain this behaviour?

**Comment by FrostTheFox** [comment]
We're just reacting to what Niantic returns, we have no control over their response, I'm not sure if this is some sort of new temp hard ban of some sort, or something weird in the requests. Maybe changing ari to a shorter time (something you'd have to experiment with), would allow enough time for the 403 to clear and let everything continue.

**Comment by aduljr** [comment]
Is ten accounts enough to scan an st 20? I got 40 accounts for my st 16 area with -SS option turned on. Granted the accounts sit for 3 to 5 minutes before scanning. I am also going through 5 proxies servers. I have not had a single issue with what ou are seeing.

**Comment by vyruz1986** [comment]
@FrostTheFox I've been getting this error since the very beginning I started running PGM (7th September), It's just that I had other issues (and was getting to know PGM) until 2 days ago when everything was working smooth and I had only this problem remaining.
So I don't believe it's something new Niantic is doing.

I know we can't control what Niantic returns (duh..) but we can control how PGM reacts to it.
I believe there is a difference between a 'real' 403 returned by Niantic vs the 403 I'm seeing.
Would be great to see some `-vv` logs from IP's and/or accounts which we known are banned to compare the two.

BTW in the beginning I had PGM running on a raspberry pi at home (from my home ISP IP address) also over tor.
Since last Friday (16th) PGM is running on the rented server (coming from a totally different public IP than my home ISP IP), but also over tor.

Am I the only one using tor? And am I the only one having this issue? I've been searching but couldn't come across a lot of other topics about this logging.

Did some further testing, after reading @aduljr's comment I though I'd setup multiple tor cirtcuits. This was quite easy on ubuntu, just add some extra SOCKSPort xxxx lines to your config and that's it.
So I configured 5 proxies on ports 9050 - 9054. I configured these five proxies as well in config.ini using brackes and comma separators (As in comment in ini file).
This resulted in almost every time I tried to start my scanner process to fail to start because one of the proxies reported a 403 error. Well it didn't really stop either but also didn't continue to log on through any of the other proxies

Question: Why does runserver.py 'stop' when one of multiple proxies seems not working? It should continue using the other ones I think, no?

Then I did some more tests. I looked at the `proxy.py` code and saw what it is doing to test its proxy, apparently an empty `POST` request to `https://pgorelease.nianticlabs.com/plfe/rpc` through each proxy. (please correct if wrong, my python-fu is not that strong...)
I thought let's see what a `cURL` test reports on the proxies that `runserver.py` reports as 'broken':
```
#first call ipecho.net to get public Tor IP
root@ubuntu01:/etc/tor# curl -x socks5://127.0.0.1:9053 http://ipecho.net/plain ; echo
37.187.129.166
root@ubuntu01:/etc/tor# curl -x socks5://127.0.0.1:9053 -v --data '' https://pgorelease.nianticlabs.com/plfe/rpc
*   Trying 127.0.0.1...
* 130
* 211
* 14
* 80
* Connected to 127.0.0.1 (127.0.0.1) port 9053 (#0)
* found 173 certificates in /etc/ssl/certs/ca-certificates.crt
* found 694 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
*        server certificate verification OK
*        server certificate status verification SKIPPED
*        common name: *.nianticlabs.com (matched)
*        server certificate expiration date OK
*        server certificate activation date OK
*        certificate public key: RSA
*        certificate version: #3
*        subject: C=US,ST=California,L=San Francisco,O=Niantic\, Inc.,CN=*.nianticlabs.com
*        start date: Fri, 22 Jan 2016 00:00:00 GMT
*        expire date: Sat, 21 Jan 2017 23:59:59 GMT
*        issuer: C=US,O=GeoTrust Inc.,CN=GeoTrust SSL CA - G3
*        compression: NULL
* ALPN, server accepted to use http/1.1
> POST /plfe/rpc HTTP/1.1
> Host: pgorelease.nianticlabs.com
> User-Agent: curl/7.47.0
> Accept: */*
> Content-Length: 0
> Content-Type: application/x-www-form-urlencoded
>
< HTTP/1.1 403 Forbidden
< Server: nginx/1.11.1
< Date: Mon, 19 Sep 2016 23:19:36 GMT
< Content-Type: text/html
< Content-Length: 169
< Via: 1.1 google
< Alt-Svc: clear
* HTTP error before end of send, stop sending
<
<html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx/1.11.1</center>
</body>
</html>
* Closing connection 0
```
Reading up on the `HTTP error before end of send, stop sending` error, it seems this is what curl reports when it receives and erroneous response (in this case 403) before it event sent all its data.
So it seems in this case I really caught a tor IP which is banned by Niantic. Ironically configuring extra proxies will increase your change to catch one. When I was just running one proxy I had this problem every 4-5 times I reloaded Tor, now with 5 proxies almost every time.

Note that the same cURL command with just another proxy port (9051 instead of 9053) produced a valid 200 response, so why does runserver.py not continue with this and other working proxies?
```
#first call ipecho.net to get public Tor IP
root@ubuntu01:/etc/tor# curl -x socks5://127.0.0.1:9051 http://ipecho.net/plain ; echo
62.210.129.246
root@ubuntu01:/etc/tor# curl -x socks5://127.0.0.1:9051 -v --data '' https://pgorelease.nianticlabs.com/plfe/rpc
*   Trying 127.0.0.1...
* 130
* 211
* 14
* 80
* Connected to 127.0.0.1 (127.0.0.1) port 9051 (#0)
* found 173 certificates in /etc/ssl/certs/ca-certificates.crt
* found 694 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
*        server certificate verification OK
*        server certificate status verification SKIPPED
*        common name: *.nianticlabs.com (matched)
*        server certificate expiration date OK
*        server certificate activation date OK
*        certificate public key: RSA
*        certificate version: #3
*        subject: C=US,ST=California,L=San Francisco,O=Niantic\, Inc.,CN=*.nianticlabs.com
*        start date: Fri, 22 Jan 2016 00:00:00 GMT
*        expire date: Sat, 21 Jan 2017 23:59:59 GMT
*        issuer: C=US,O=GeoTrust Inc.,CN=GeoTrust SSL CA - G3
*        compression: NULL
* ALPN, server accepted to use http/1.1
> POST /plfe/rpc HTTP/1.1
> Host: pgorelease.nianticlabs.com
> User-Agent: curl/7.47.0
> Accept: */*
> Content-Length: 0
> Content-Type: application/x-www-form-urlencoded
>
< HTTP/1.1 200 OK
< Server: nginx/1.11.1
< Date: Mon, 19 Sep 2016 23:24:30 GMT
< Content-Length: 2
< Cache-Control: no-cache
< Via: 1.1 google
< Content-Type: text/html; charset=UTF-8
< Alt-Svc: clear
<
* Connection #0 to host pgorelease.nianticlabs.com left intact 
```

**Comment by sebastienvercammen** [comment]
Closing this issue because it's very old and no longer relevant to the current codebase. If the issue still persists for you today, comment on this issue to reopen it with new details (logs, screenshots).
