### ISSUE TITLE
Change notification sound

### ISSUE THREAD

**Issue by homerfan123** [RocketMap/RocketMap#1346]
Hello, I have just the question how to change the notification sound?

Already replaced the "ding.mp3" with a different one with the same name, restarted the whole processes, but nothing changed.

**Comment by Toolshed47** [comment]
I would like to be able to change the notification sound as well. Too many dings get missed in a noisy house. Thanks.

**Comment by DiscoTim** [comment]
try clearing browser cache.

**Comment by Toolshed47** [comment]
Oddly enough it stopped playing sound completely in IE but it works now in Chrome after clearing out the cache. I prefer chrome any way, thank you for the answer.

**Comment by DiscoTim** [comment]
you could try a different format of your sound file for IE, it may be just the encoding of that particular file IE doesn't like.

**Comment by homerfan123** [comment]
thanks worked great! stupid I didn't had that in mind :/

**Comment by sebastienvercammen** [comment]
Closing this issue because it's very old and no longer relevant to the current codebase. If the issue still persists for you today, comment on this issue to reopen it with new details (logs, screenshots).
