### ISSUE TITLE
[Feature Request] Notification sound per rarity / IV notification

### ISSUE THREAD

**Issue by KongGal** [RocketMap/RocketMap#1349]
differend notification sounds based on rarity and maybe one just for IV notifications.

**Comment by DiscoTim** [comment]
This pr (mine) https://github.com/PokemonGoMap/PokemonGo-Map/pull/933 includes the code for different notifications sounds per rarity, although it does not include the actual sound. It's not currently in a state to be merged, but will be soon, it will also also account for iv's.

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
