### ISSUE TITLE
Move translations to the client side

### ISSUE THREAD

**Issue by SoonDead** [RocketMap/RocketMap#1350]
Currently pokemon names, rarities and move types are translated on the server,

This has a few downsides:
1. Some extra server load
2. Not possible to reduce pokemons in raw_data response size to about half of it's current size (described in #1348)
3. Slows down efforts of full interface translations as concepts are mixed. It is currently not trivial how to translate something on the user interface and therefore new features just tiptoe around being localizable. If there could be a clear guideline like "every sentence should be wrapped in the i18n function before it's rendered" or something similar, then the PR authors would know what to do.
4. All clients are stuck with the same language.

The client side is already able to translate. I propose that it should do all the translation.

Locale does not need to be a server side setting, in scenarios where the translation must be done on server side (client has no data processing capabilities, like a very simple command line tool), the locale should be part of the request. I propose reducing the "-L --locale" parameter to only be the "initial client side locale" or completely deprecating/removing it.

Also internationalization is not i8ln but i18n, function names should be changed.

Is there any arguments against this or should this be reworked?

**Comment by DiscoTim** [comment]
someone else suggested the client be moved to https://github.com/i18next/i18next

**Comment by SoonDead** [comment]
@DiscoTim I'm not against i18next, seems like a well made library.

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
