### ISSUE TITLE
[Feature Request] Switch to enable worker labels visually on the map

### ISSUE THREAD

**Issue by sngreco** [RocketMap/RocketMap#1364]
I would like to be able to determine on the map which worker is which.  I anticipate that this would be tremendously helpful when scanning new large beehive patterns and I would like to remove workers from areas with no spawn points, over water, or just in areas I don't want scanned.  This could be easily solved by assigning a label to each worker via the command line.

For example: 
python runserver.py -label worker1 etc...

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
