### ISSUE TITLE
Add / Delete Location at webfront, enabled over command argument [Feature Request]

### ISSUE THREAD

**Issue by st0nec0ld** [RocketMap/RocketMap#1378]
Hey guys, my scanner dont run 24/7.  I start a scan by hand to look for mons around my current location, sometimes at home or at work, when visit friends, on the road, at the park etc.

The workaround to start a scan is inconvenient:
- tap on left top corner
- tap on Locations Seetings
- tap on Search follows me (turn it on)
- wait for GPS signal
- tap on Search follows me (turn it off)
- tap on Search (turn it on)
- wait for scan completed
- tap on Search (turn it off)

Something like this > https://github.com/favll/pogom would be awesome. Tap on the map add the location. Tap on the icon delete the location and all worker switch to "Scanning paused". This should be only possible when i start my scanner with a specified argument, 
#1307 is similar, but wont merge.

My setup: Last release Version (3.2.0) on Rasp 3 with Pagekite.

P.S. sorry for my bad english

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
