### ISSUE TITLE
[Feature Request] Encounter on demand (using spare workers?) for IV and moveset

### ISSUE THREAD

**Issue by vbguy2011** [RocketMap/RocketMap#1379]
Click on desired pokemon on map.
New option "Encounter" from pokemon info window.
Click Encounter, pokemongo-map uses spare account if available, if not, then queues next account, to encounter pokemon.
After encounter, pokemon info window updates with IV, attack, defence, stamina and movesets.
This would be a good addition to pr1272 for those pokemons that aren't on a whitelist.

**Comment by jccwright** [comment]
Has anyone picked this up? I might be interested in working on this *IF* I can have someone who is a bit more experienced available as an ADVISOR. Basically, I'm not a python guy but I'm a decent programmer. I would like to try to do something WITH GUIDANCE so I don't just piss everyone off. I will do all the heavy lifting, just want to have someone available to bounce questions/ideas off of from time to time. 

Any takers?

**Comment by jchristi** [comment]
@jccwright if you join the discord cat, I can help you out

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
