### ISSUE TITLE
Greyed out icons/popup for stale gym data

### ISSUE THREAD

**Issue by SoonDead** [RocketMap/RocketMap#1382]
If you have scanned a gym, it will remain on the map forever and ever, until you remove it from the database. If you have scanned it to be a blue lvl 9 gym a week ago and does not scan that area again, it will show up as a lvl 9 blue gym.

If you move your scanner around you might have a difficulty in seeing which gym was scanned recently.

I propose there should be setting (possibly client-side) for a certain time treshold. e.g. if a gym was not scanned in the last hour/6 hours/day/etc it should show up as stale data on the map. It's hard to just decide on a fixed treshold as it is very dependant on the usage. Even people using the same map could have different preferences.

I propose stale gyms having their icons/pins grayed out to some degree. Team colors should still be visible but paler. Somewhat like fog of war in certain RTSes.

**Comment by jabberjabber** [comment]
Will be fixed by https://github.com/PokemonGoMap/PokemonGo-Map/pull/1288

**Comment by SoonDead** [comment]
@jabberjabber I don't have the time to try it out now. Will #1288 clearly show open spots in gym details? The issue is about filter settings, the gymLabel does not seem to be modified (I only glanced over changes).

**Comment by sebastienvercammen** [comment]
Closing this issue because it's very old and no longer relevant to the current codebase. If the issue still persists for you today, comment on this issue to reopen it with new details (logs, screenshots).
