### ISSUE TITLE
[Feature Request]Add option for gym info from user instead of scanner

### ISSUE THREAD

**Issue by StairyNight** [RocketMap/RocketMap#1389]
Since 0.37 has been forced today and all remaining scanner are still working but alreadd exposing themselves as un-ligit players. Chances are the days for scanners are very short before Niantic deciedes to turn on the switch to kill them all.

From my point of view, it would be useful to save something before being blind. Spawnpoints is of course, which has been done. Another thing is I would like to save the gym location in a 'vector graph' style. I plan to go to a part of the city each day and if I find gyms with high prestiges, I want to log them and save them for tomorrow to battle, as high-prestige gyms tends to last long. It would be nice to be able to manually enter the info like the gym color and how many pokemons in it and probably its prestidge. Curently, I can only do a scrrent shot of the map and it's not even in vector style, which is close to useless.

**Comment by jabberjabber** [comment]
IMO this is out of the scope of this project. The real fix is to wait and hope for the pogo APIs to be reverse engineered. If you are doing manual work, you might as well track stuff on a piece of paper.

**Comment by Axeia** [comment]
Although I agree with jabberjabber, if you really want this and have some Javascript knowledge you could write this yourself in the form of a userscript that you can run in your browser. Adding an onclicklistener and using localstorage this shouldn't be too hard. 
If you don't know javascript you're sadly out of luck.

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
