### ISSUE TITLE
[Feature Request] Clarify Location & Search Settings

### ISSUE THREAD

**Issue by SoonDead** [RocketMap/RocketMap#1393]
Most settings are pretty straightforward and self-explanatory, however the Location & Search Settings are rather confusing for a user.

"Search follows me" and "Follow me" seems very similar and confusing for example, 
## Possible Solution

Show a tooltip on mouse hover or on clicking a little information icon or something.

**Comment by beccasafan** [comment]
Agreed. 

Definitely not clear that one of those moves the scan worker to scan the new location, while the other simply pans the client-side map view and doesn't affect the scan worker(s) or anyone else using the map.

It's also confusing that some things are for server-side only. A number of times I've wanted to type in a location to move the map view to without changing my actual scan location.

A PR could definitely help out here.

**Comment by DiscoTim** [comment]
I like this idea, minus the top two options.

https://cloud.githubusercontent.com/assets/1531746/18438099/f1c38c4e-78cd-11e6-89bd-b906fc7ddcf3.png

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
