### ISSUE TITLE
Option to prune spawn points that are invalid after x failures

### ISSUE THREAD

**Issue by TheNewDarkOne** [RocketMap/RocketMap#1396]
## Current Behavior

Empty spawn points will continue to be scanned even when they are no longer valid
## Possible Solution

if a spawn point fails to return a pokemon after x number of fails, auto prune it from database.
## Context

On Sept 26th, a ton of spawn points were added, but also a ton were removed. Most spawn points did not change. As such, simply wiping database is not the best solution because you'll lose a lot of still valid data. It's more ideal to have a clean means of just removing the bad data on the fly with new scans.

**Comment by SkOODaT** [comment]
yes please some way of cleaning dead spawns out of our databases

**Comment by slideup-benni** [comment]
Maybe we need a new Table. Then we can save the spawnpoint-type as well.

**Comment by TheQL** [comment]
I second this request, this just needs to be compatible to disabling workers on empty scans. So maybe only purge on x consecutive fails if the worker had positive finds before and maybe after the empty scan.

**Comment by TheNewDarkOne** [comment]
Just bumping that it seems spawn POINT migrations are becoming a more regular thing. This will definitely be needed.

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
