### ISSUE TITLE
Feature Request: Filter map by IV

### ISSUE THREAD

**Issue by Dcstegg228** [RocketMap/RocketMap#1411]
Right now the map can only be filtered by pokemon #. It would be a great feature if the map could be filtered by pokemon IV or a combination of the two. For example: Pidgey is filtered from the map unless it has an IV above x% and then it will be shown.

**Comment by springjools** [comment]
You looking for that 100 % IV pidgey?

**Comment by aldarund** [comment]
Omg. gj on iv on pidgey. zero brain really

**Comment by DiscoTim** [comment]
i too am on the quest for the perfect weedle.

**Comment by Dcstegg228** [comment]
I'm looking for perfect IV of any pokemon, and F the rest unless its Lapras.

**Comment by aldarund** [comment]
yeye.  do u realize that iv create encounter for every pokemon on the map and means it double the requests to niantic, leading to faster bans and more angry niantic?

**Comment by Dcstegg228** [comment]
Yes I do so I doubled my workers and proxies, dont care about bans. I'm filtering them as I catch a 100%. Pidgey, bulbasaur, paras, koffing, and machop are on my blacklist so far.  This feature could also be usefull to someone who isn't checking them all though. Even if you check some of the rare stuff you dont want to see all the time.

**Comment by aldarund** [comment]
nice that you dont care. Thats why niantic hates maps, because of this.

**Comment by Dcstegg228** [comment]
Dude there are people on there with thousands of search workers that make more requests in one minute than I make in an hour . Go talk to them. None of this is constructive so lets just stop it.

**Comment by darkelement1987** [comment]
I already made a Request for this with screen shot a while ago, but the pr wasn't merged back then

https://github.com/PokemonGoMap/PokemonGo-Map/issues/1337

**Comment by SiteEffect** [comment]
I am for highlighting high IVs either by transparency of the others or increasing size

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
