### ISSUE TITLE
Stats query don't use proper index

### ISSUE THREAD

**Issue by viliam-jobko** [RocketMap/RocketMap#1415]
## Current Behavior

Index is not used to query DB for full statistic page.

This is query to fetch data for statistics page. In my environment, this query approximately 50 seconds (run multiple times with SQL_NO_CACHE).

``` sql
SELECT DISTINCT `t1`.`pokemon_id`,
                `t1`.`disappear_time`,
                `t1`.`latitude`,
                `t1`.`longitude`,
                `counttable`.`count`
FROM `pokemon` AS t1 
INNER JOIN
  (SELECT `t3`.`pokemon_id`,
          COUNT(`t3`.`pokemon_id`) AS COUNT,
          MAX(`t3`.`disappear_time`) AS lastappeared
   FROM `pokemon` AS t3
   WHERE (`t3`.`disappear_time` > '2016-09-26 00:00:00')
   GROUP BY `t3`.`pokemon_id`) AS counttable ON (`t1`.`pokemon_id` = `counttable`.`pokemon_id`)
WHERE (`t1`.`disappear_time` = `counttable`.`lastappeared`)
```
## Expected Behavior

Use index to faster query DB for full statistic page.

This should be query which is run to fetch data for statistics page. In my environment, this query takes approximately 6 seconds (run multiple times with SQL_NO_CACHE). The only difference against query above is `FORCE INDEX (pokemon_disappear_time)`.

``` sql
SELECT DISTINCT `t1`.`pokemon_id`,
                `t1`.`disappear_time`,
                `t1`.`latitude`,
                `t1`.`longitude`,
                `counttable`.`count`
FROM `pokemon` AS t1 
INNER JOIN
  (SELECT `t3`.`pokemon_id`,
          COUNT(`t3`.`pokemon_id`) AS COUNT,
          MAX(`t3`.`disappear_time`) AS lastappeared
   FROM `pokemon` AS t3 FORCE INDEX (`pokemon_disappear_time`)
   WHERE (`t3`.`disappear_time` > '2016-09-26 00:00:00')
   GROUP BY `t3`.`pokemon_id`) AS counttable ON (`t1`.`pokemon_id` = `counttable`.`pokemon_id`)
WHERE (`t1`.`disappear_time` = `counttable`.`lastappeared`)
```
## Steps to Reproduce (for bugs)

Test above queries in your environment. Feel free to post results in comments (including details of your environment)
## My Environment
- Version used:
- Environment name and version (e.g. Python 2.7): Python 2.7.12
- DB: MySQL 5.7.15 (inno_db_buffer: 3GB)
- Rows in `pokemon` table: 3 685 309
- Operating System and version (desktop or mobile): Ubuntu 16.04

**Comment by aldarund** [comment]
The problem is that i dont see how peewee can specify FORCE INDEX.

**Comment by deirdresm** [comment]
1. Ran first: 1.8 seconds.
2. Ran second: 0.89 seconds. (Confirming the issue.)
3. For grins: create index species_counts on pokemon (pokemon_id, disappear_time);
4. Ran first again: 0.66 seconds.
5. Ran second again: 0.35 seconds.
6. Ran second again, this time with FORCE INDEX (`species_counts`) : 0.23 seconds.

Note that adding a compound column index like that may have unwanted side effects, though, mostly table locking.
