### ISSUE TITLE
Mysql performance slower than sqlite

### ISSUE THREAD

**Issue by simonbuehler** [RocketMap/RocketMap#1419]
hi,

running git as of today i switched from sqlite to a local mysql server. Doing Spawnpoint scanning with 2200 points and 30 accounts i get behind like about 300 seconds, using sqlite i'm early for around 20 seconds.

only hints phpmyadmin gives after fifteen minutes:
Handler read rnd nextDokumentation  628.4 k - indexes not used enough when doing full table scans

any idea? how can i debug this ?

**Comment by Demokdawa** [comment]
I have same kind of issue me too. Few weeks ago, i scanned 6K points with 26 accounts (30 sec behind), and now with 11000 spawns and 80 accs, i'm behind like 6000 s xD

**Comment by TheNewDarkOne** [comment]
Ironically I just had to dump sqlite because of performance issues and database locking and went to mysql. But i also had to start spawnpoint collecting over so I have to rebuild it back up before I can compare.

**Comment by simonbuehler** [comment]
use sqlitebrowser  to export databas and import it in mysql

delete all "CREATE ...." Lines from the sql dump file cause the tables and indexes are already created in mysql

**Comment by derycklong** [comment]
dump to json. i am scanning 50,000 points with 240 accounts.

**Comment by drallieiv** [comment]
Have you tried maria db mysql implementation ?

**Comment by sebastienvercammen** [comment]
Closing this issue because it's very old and no longer relevant to the current codebase. If the issue still persists for you today, comment on this issue to reopen it with new details (logs, screenshots).
