### ISSUE TITLE
[Feature Request] Add search box to stats page

### ISSUE THREAD

**Issue by NoobDev3** [RocketMap/RocketMap#1429]
Adding a search box to the status page to assist in finding a specific Pokemon quickly.
## Expected Behavior

Being able to search for a specific Pokemon from the stats page.

**Comment by cyan** [comment]
if possible it be nice to have the same for gyms where you enter the name of any trainer in the search box and it hide all the gyms this trainer is not in :)

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
