### ISSUE TITLE
Total Pokemon Count removed from Stats Sidebar

### ISSUE THREAD

**Issue by CT9AJ** [RocketMap/RocketMap#1431]
## Expected Behavior

There should be a count for Total Pokemon on the Stats Sidebar.
## Current Behavior

There are only counts for individual Pokemon, total count appears to have been removed when the stats sidebar was enhanced.

![image](https://cloud.githubusercontent.com/assets/20644208/19015623/9fcc43a6-87d5-11e6-864a-e17fb4d5cfb4.png)

**Comment by kamieniarz** [comment]
I miss that total count too!

**Comment by CT9AJ** [comment]
Yeh it was really useful to me, I've tried editing the code to bring it back but not sure what I'm doing.

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
