### ISSUE TITLE
[Feature Request] Hide gym info from map or purge gym info after X amount of time

### ISSUE THREAD

**Issue by Jeyms** [RocketMap/RocketMap#1434]
## Expected Behavior

Hide from map or purge gym info from database after X amount of time.
Same as -pd / --purge-data but for gyms.
## Current Behavior

Current gym information remains on map indefinitely.
## Possible Solution

Relative to -pd / --purge-data.

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
