### ISSUE TITLE
[Feature Request] Add ability to set credentials in order to access the map

### ISSUE THREAD

**Issue by hkuiyo** [RocketMap/RocketMap#1436]
I would like to be able to set a username & password so that when people visit my hosted PokemonGo-Map, they are required to login before they can see it, so that the map is not available out in the open.

**Comment by DiscoTim** [comment]
What you are asking for can be solved with using credentials on nginx or apache, however i agree the app should support this natively, and simply, and also forgo the need to setup a proxy. 

I would like this implemented for different reasons. I would like the app to be able to store user settings on the backend.

several applications of this, and there are likely many more i am not currently realizing:

user settings follow them across devices and user settings are more reliable and persistent. and then also more complex settings can then be introduced for the user.
/admin endpoint on the front end.
seeing/interacting with friends on the map.
notifications can be processed on the backend, not the client.

a number of libraries are available to accomplish this, for example:

https://pythonhosted.org/Flask-User/
https://github.com/maxcountryman/flask-login
https://pythonhosted.org/Flask-Security/

**Comment by hkuiyo** [comment]
When I created the issue I was initially only thinking of just having "Allowed to see the map" yes/no, but it can indeed be further expanded:
- Is logging in required yes or no? (if not required, user could be reported as anonymous user)
- Is the user allowed to see the map, yes or no? (i.e. required to be logged in, or required to be a certain user)
- Is the user allowed to move the marker on the map on the go? (i.e. only allowed by the owner of the map)
- It could indeed store data on the server when it knows about the user that is viewing the map

**Comment by russellito** [comment]
This is something they are talking about in [#1278](https://github.com/PokemonGoMap/PokemonGo-Map/issues/1278)

**Comment by SiteEffect** [comment]
Adding a password for your map like it's in /stats should be doable.

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
