### ISSUE TITLE
[Feature Request] Show CP for Pokemon on the map (do we know the algorithm/random number generator?)

### ISSUE THREAD

**Issue by hkuiyo** [RocketMap/RocketMap#1437]
It would be awesome if we could also show the CP of the Pokemon on the map. But I think we are unable to do this.
- CP are the same for all trainers that share the same level
- Our worker threads will use accounts that represent trainers which have a very low level (probably they will all always have level 1)
- We know the CP of the Pokemon we encounter when the trainer is level 1

Is there a way, given the trainer level of the account that encounters the Pokemon and the CP that the Pokemon has, to determine what CP it would have when the trainer would be level 27? 

Is there a formula for this? Or are we not (yet) aware of how the trainer level is used as the muliplier for the CP of the Pokemon?
I.e. there is probably a random number generator that is seeded with some details that are specific to the trainer level.

**Comment by skeldoor** [comment]
Ranges could probably be given. Like max cp possible if you're X level etc

**Comment by jchristi** [comment]
I'm pretty sure the CP formula is still a mystery. In order to even attempt cracking this, we would need a large data dump of many instances of the same encounter for multiple trainer levels (at least).  And to get that you basically need a fleet of multi-level bots. If someone has that data and is willing to provide it, I'm sure many will gladly take a look and try to crack the formula. I know I would.

**Comment by averylarry** [comment]
2 trainers of the same level can get vastly different CP from the same encounter, right?  So isn't it impossible because it's somehow generated by Niantic, either 100% random or somehow related to individual trainers . . ?

**Comment by jchristi** [comment]
Unless something has changed in the latest patch I've always noticed that the trainers of the same level always see the same CP wild pokemon.

**Comment by PhDeez** [comment]
From my scanning in /r/pokemongodev there is a level multiplier in the dump of the game that I believe determines CP.  I also know that every encounter that I've seen where my wife and I are on the same level (and neither are using incense, so same spawned pokemon for both of us) the CP level was the same.

**Comment by jchristi** [comment]
@PhDeez can you provide the reddit link? Thanks.

**Comment by WalterMagnum** [comment]
If you could log in a level 30 account (all players over level 30 see the same CP mon) on a separate thread that could go around and CP check select pokemon, you could accomplish this.  It isn't very hard to get disposable lvl 30 accounts.

**Comment by hkuiyo** [comment]
That is actually a very good suggestion!

**Comment by lord-emperor** [comment]
It's already possible to "encounter" the Pokemon and know its IVs, therefore possible to know its exact CP at any given level.  
  
However, Pokemon level is determined randomly for each player level. I.e. all players who are level 15 will find a Pokemon with the same level, randomly selected from 1-15.

There is no way to determine what level the Pokemon will be _for you_ unless you level up your scanner account to exactly the same level as you yourself are.

**Comment by perl5577** [comment]
Is not randomly .

Each time my friend with level 30 ( me 29 ) .

if get little pokemon my friend get pokemon with more CP
If get very good pokemon for level 29 my friend get little pokemon 

( I think function Modulo in algo for compute level pokemon  )

**Comment by SiteEffect** [comment]
There is a heavy theory, retrieving CP with modulo by trainer level of a part of  encounter_id

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
