### ISSUE TITLE
Super high CPU bug

### ISSUE THREAD

**Issue by shivampaw** [RocketMap/RocketMap#1440]
Hi,

I've got a bug somewhere where the CPU is super high (90%) and ram is being used a lot.

`python runserver.py -ps -fl -nsc -asi 0 -ari 30 -mf 10 -gi` is the command I am using, also I am using MySQL.

Running `top` gives this:

top - 12:42:46 up 1 day,  1:30,  1 user,  load average: 27.71, 12.46, 12.76
Tasks: 106 total,   2 running, 104 sleeping,   0 stopped,   0 zombie
Cpu(s): 86.3%us, 13.7%sy,  0.0%ni,  0.0%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Mem:   4194304k total,  3689168k used,   505136k free,        0k buffers
Swap:  4194304k total,    71296k used,  4123008k free,  2556820k cached

PID     USER      PR    NI  VIRT       RES        SHR  S     %CPU   %MEM      TIME+        COMMAND
11232 root         20   0   3305m   360m     6076  S   47.9      8.8           2:12.82       python2.7
957     mysql     20   0    2382m   649m     6240 S   2.3       15.9           27:24.39    mysqld

I think there is a problem with all those sleeping tasks?

Edit: There seems to be a lot of "db updates" pending whenever I check.

**Comment by shivampaw** [comment]
Any ideas for this?

**Comment by aguita** [comment]
Please visit the discord channel for help on this.  People there can help much faster, and ask you to do various things to see if it helps. 
https://discordapp.com/invite/PWp2bAm

**Comment by shivampaw** [comment]
I've asked there but nobody helped.

**Comment by shivampaw** [comment]
@aguita ^

**Comment by BaIthamel** [comment]
I'm going to take a wild stab in the dark, this could be due to db locked issues we've seen. We know they're there and people are working on it. Unless you can debug it a bit more for us you'll just have to wait and hope it gets fixed.

**Comment by sebastienvercammen** [comment]
Closing this issue because it's very old and no longer relevant to the current codebase. If the issue still persists for you today, comment on this issue to reopen it with new details (logs, screenshots).
