### ISSUE TITLE
No pokemon icons in gym details and stats

### ISSUE THREAD

**Issue by kamieniarz** [RocketMap/RocketMap#1441]
As in title - I have no pokemon icons + stats page isn't refreshing by itself (I need to reload page to see actual stats). I tried to delete my map folder and download the newest one - didn't work. Any ideas?

**Comment by sebastienvercammen** [comment]
Closing this issue because it's very old and no longer relevant to the current codebase. If the issue still persists for you today, comment on this issue to reopen it with new details (logs, screenshots).
