### ISSUE TITLE
Merge 1428 broke launch without arguments

### ISSUE THREAD

**Issue by Beri51** [RocketMap/RocketMap#1447]
Not launching with error: Gmaps Key required

> XX@XXXXXX:~ $ python ~/PokemonGo-Map/runserver.py 
> usage: runserver.py [-h] [-cf CONFIG] [-a AUTH_SERVICE] [-u USERNAME]
>                     [-p PASSWORD] [-w WORKERS] [-asi ACCOUNT_SEARCH_INTERVAL]
>                     [-ari ACCOUNT_REST_INTERVAL] [-ac ACCOUNTCSV]
>                     [-l LOCATION] [-j] [-st STEP_LIMIT] [-sd SCAN_DELAY]
>                     [-enc] [-ed ENCOUNTER_DELAY]
>                     [-ewht ENCOUNTER_WHITELIST | -eblk ENCOUNTER_BLACKLIST]
>                     [-ld LOGIN_DELAY] [-lr LOGIN_RETRIES] [-mf MAX_FAILURES]
>                     [-msl MIN_SECONDS_LEFT] [-dc] [-H HOST] [-P PORT]
>                     [-L LOCALE] [-c] [-m MOCK] [-ns] [-os] [-nsc] [-fl] -k
>                     GMAPS_KEY [--skip-empty] [-C] [-D DB] [-cd] [-np] [-ng]
>                     [-nk] [-ss [SPAWNPOINT_SCANNING]] [--dump-spawnpoints]
>                     [-pd PURGE_DATA] [-px PROXY] [-pxsc] [-pxt PROXY_TIMEOUT]
>                     [-pxd PROXY_DISPLAY] [--db-type DB_TYPE]
>                     [--db-name DB_NAME] [--db-user DB_USER]
>                     [--db-pass DB_PASS] [--db-host DB_HOST]
>                     [--db-port DB_PORT]
>                     [--db-max_connections DB_MAX_CONNECTIONS]
>                     [--db-threads DB_THREADS] [-wh [WEBHOOKS [WEBHOOKS ...]]]
>                     [-gi] [--disable-clean] [--webhook-updates-only]
>                     [--wh-threads WH_THREADS]
>                     [--ssl-certificate SSL_CERTIFICATE]
>                     [--ssl-privatekey SSL_PRIVATEKEY] [-ps] [-sn STATUS_NAME]
>                     [-spp STATUS_PAGE_PASSWORD] [-el ENCRYPT_LIB]
>                     [-odt ON_DEMAND_TIMEOUT] [-v [filename.log] | -vv
>                     [filename.log]]
> runserver.py: error: argument -k/--gmaps-key is required
## Expected Behavior

Start runserver.py without arguments as config.ini is present and in same directory as before.
## Current Behavior

Not starting as gmaps key required.
## Possible Solution

My config file is the standard ~/PokemonGo-Map/config/config.ini
If I start with python ~/PokemonGo-Map/runserver.py -cf ~/PokemonGo-Map/config/config.ini then it starts again correctly.

I also tried and changed line 50 with line 48 (PR 1428) and it works also without arguments. (Not sure if it breaks something else for someone using no config file or arguments).
Can someone review this ?
## Steps to Reproduce (for bugs)

1. Start runserver.py without arguments using config.ini (standard)
## Your Environment

- Version used: includind 1303 & 1428
- Environment name and version (e.g. Python 2.7): Python 2.7
- Operating System and version (desktop or mobile): Raspbian on Raspberry-Pi

**Comment by BaIthamel** [comment]
Merge 1428 removed a tiny portion of deprecated code from the MAN page. This might be a real issue but you're looking at the wrong commit!

**Comment by Beri51** [comment]
https://github.com/PokemonGoMap/PokemonGo-Map/pull/1428
This is where I changed lines 50 and 48.
I am new to the whole Github thing, maybe the numbers are wrong. Sorry.

**Comment by Omikakim** [comment]
I have the same problem.

**Comment by Climbgunks** [comment]
argh... this seems to be an issue w/ configargparser  not actually reading the default value if you only use the add_argument() call and you don't specify the default config file in the default_config_files keyword array when you create the parser [ current behavior ].   

However, if you do set the default_config_files keywords, then command line config files are merged or layered onto the default values  -- which isn't what we want to happen either.

I have a fix that involves checking for the existence of the command line flag before creating the parser... a bit convoluted, and I need to do some more testing.   For those that want to test, here's the diff against pogom/utils.py

```
diff --git a/pogom/utils.py b/pogom/utils.py
index 0f86769..9109441 100755
--- a/pogom/utils.py
+++ b/pogom/utils.py
@@ -43,12 +43,14 @@ def memoize(function):
 
 @memoize
 def get_args():
-    # fuck PEP8
-    defaultconfigpath = os.getenv('POGOMAP_CONFIG', os.path.join(os.path.dirname(__file__), '../config/config.ini'))
-    if not os.path.isfile(os.path.realpath(defaultconfigpath)):
-        defaultconfigpath = None
-    parser = configargparse.ArgParser(auto_env_var_prefix='POGOMAP_')
-    parser.add_argument('-cf', '--config', is_config_file=True, default=defaultconfigpath, help='Configuration file')
+    # pre-check to see if the -cf or --config flag is used on the command line
+    # if not, we'll use the env var or default value.  this prevents layering of
+    # config files, and handles missing config.ini as well
+    defaultconfigfiles = []
+    if '-cf' not in sys.argv and '--config' not in sys.argv:
+        defaultconfigfiles = [os.getenv('POGOMAP_CONFIG', os.path.join(os.path.dirname(__file__), '../config/config.ini'))]
+    parser = configargparse.ArgParser(default_config_files=defaultconfigfiles, auto_env_var_prefix='POGOMAP_')
+    parser.add_argument('-cf', '--config', is_config_file=True, help='Configuration file')
     parser.add_argument('-a', '--auth-service', type=str.lower, action='append', default=[],
                         help='Auth Services, either one for all accounts or one per account: ptc or google. Defaults all to ptc.')
     parser.add_argument('-u', '--username', action='append', default=[],
```

**Comment by BaIthamel** [comment]
@Beri51 that's PR #1428
