### ISSUE TITLE
[Feature Request] Have multiple pre-configured locations for map server.

### ISSUE THREAD

**Issue by PenguinsFlyGood** [RocketMap/RocketMap#1453]
my map covers a lot of different areas, a community map for my area, and I thought it'd be really cool if in the sidebar you could have preconfigured locations it would jump to in 1 click. right now people have to drag across the map to get to the location they want.

for example, under location it could have location 1 link location 2 link location 3 link

here's a little mockup I made professionally in paint

http://i.imgur.com/n3fgoo3.png

we could rename location 1,2,3 whatever we want and when we click it would bring the map to that location. 

thanks for the consideration

**Comment by ChilliHam** [comment]
https://github.com/PokemonGoMap/PokemonGo-Map/issues/1344

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
