### ISSUE TITLE
purge data not working

### ISSUE THREAD

**Issue by shivampaw** [RocketMap/RocketMap#1457]
Hi

I think their is an issue with purge data.

I use this argument `-pd 2`

But when I see the "regular database clean complete" message my raw_data file still has like 10,000 pokemon in it instead of just a couple hundred in the last 2 hours.

This makes loading times very high (35 seconds).

**Comment by shivampaw** [comment]
Tested again after clearing database and it is still insanely slow after running for a few hours.

-pd isn't working.

**Comment by clifford2006** [comment]
The problem is in models.py afer line 901, someone forgotten to place back the query.execute()
I'm not sure how to do PR, so can somebody do this?

**Comment by sebastienvercammen** [comment]
Closed, this is a very old issue. Any feature requests are now handled via http://vote.devkat.org and if any issue reported in the issue is still related to current code, a new GitHub issue should be opened.
