### ISSUE TITLE
[Suggestion] Clicking “all locations” on the /stats page should trigger `Map.fitBounds()`

### ISSUE THREAD

**Issue by tegob** [RocketMap/RocketMap#1466]
## Expected Behavior

On the `/stats` page, clicking “all locations” to view where a species of Pokémon spawned, the map zoom level should automatically be set so that all the highlighted spawn points are visible.
## Current Behavior

Currently, the same map zoom level is being used all the time, and the map is centered at the search location, causing the spawn points to sometimes appear outside of the visible map. The user then has to scroll or zoom out to view the spawnpoints.
## Possible Solution

Google Maps API v3 provides a `LatLngBounds` object to which you can add multiple `LatLng` objects (i.e. all the highlighted spawn points). You can then pass this object to `Map.fitBounds()`. More info here: http://stackoverflow.com/a/3905922
## Steps to Reproduce (for bugs)
1. Leave the scanner running for a while
2. (For easier repro:) change the search location to some far-away place
3. Right after, open the `/stats` page
4. Pick any Pokémon species and click the “all locations” link
5. The highlighted spawn points won’t be visible, you have to zoom out / move to the original location to see them
## More info

I guess this is supposed to happen in `static/js/statistics.js`.

**Comment by Arengo** [comment]
This would be really helpful! I have to always zoom out a lot before being able to look on the whole area I scan.

**Comment by sebastienvercammen** [comment]
Closed, this is a very old issue. Any feature requests are now handled via http://vote.devkat.org and if any issue reported in the issue is still related to current code, a new GitHub issue should be opened.
