### ISSUE TITLE
Map only scans once or twice then stops

### ISSUE THREAD

**Issue by ITranscendensEI** [RocketMap/RocketMap#1468]
I set up the basic version of PokemonGo-Map and now it only scans once or twice, and just stops. Also I can no longer access the settings or stats tab. All I did was download the latest version from here and added my throwaway accounts. When I did the first scan with only a few accounts, everything seemed to work fine. I setup my filters and notifications no problem. Then when I added extra workers to widen the scan radius, this mess started. I'm not very familiar with programming so I didn't use Python or anything. Any help would be much appreciated.

**Comment by Deatarus** [comment]
I'm pretty sure it's the new Captcha feature Niantic rolled out.

**Comment by sebastienvercammen** [comment]
Closing this issue because it's very old and no longer relevant to the current codebase. If the issue still persists for you today, comment on this issue to reopen it with new details (logs, screenshots).
