### ISSUE TITLE
Less pokemons found with Gyms enabled

### ISSUE THREAD

**Issue by shadi1989** [RocketMap/RocketMap#1469]
## Expected Behavior

same amount of pokemon found with or without Gyms/Gym-info enabled
## Current Behavior

I got 2 VPS servers running:
-both with 150 accounts each(different accounts of course)
-same JSON file
-DB on localhost
-same config (except gym/gym-info)

Server 1: Gym+Gyminfo enabled
scannedlocations: 8347
pokemons: 25638

Server 2: Gym+gyminfo disabled
scannedlocation: 8046
pokemons: 35995

Screenshots from different time:
Same amount of scannedlocations, about 500 pokemon spawns off
Server 1:
![set_1_mysql](https://cloud.githubusercontent.com/assets/20524866/19130934/b24484f0-8b4d-11e6-8ea7-9fff7e7afe28.png)
Server 2:
![set_2_mysql](https://cloud.githubusercontent.com/assets/20524866/19130935/b2492258-8b4d-11e6-936a-a47866b7d282.png)
## Possible Solution

Disabling Gyms+gym-info fixed it but thats not a real solution :)
## Steps to Reproduce (for bugs)
1. Have 2 servers
2. Pull latest build
3. Use as much parameters in config.ini, copy it into the 2nd server
4. Enable Gyms+gyminfo in 1 of the servers.
5. Checkout databases via PhpMyAdmin
## Your Environment
- Version used: Latest build
- Environment name and version (e.g. Python 2.7): Python 2.7.12, pip 8.1.2
- Operating System and version (desktop or mobile): Ubuntu 16.04 x64 VPS in cloud

**Comment by RADiEnCe** [comment]
Does this have anything to do with the new Captcha system?

**Comment by shadi1989** [comment]
@RADiEnCe no it doesn't really, already having it a couple of days.

**Comment by StairyNight** [comment]
It's normal if you dont have enough account. To get gym info, additional API calls are needed and each API call needs to have 10s in between, those calls were used to find pokemon if you dont enable -gi.

**Comment by SoonDead** [comment]
Is it possible that a gym update somehow makes the consecutive scan fail on that account?

I would be interested in what the status page says. Is the scan that much behind? Are there more failed requests?

**Comment by shadi1989** [comment]
@StairyNight thats not the issue, if i need more accounts the queue will run a lot behind. i was 2-5 seconds behind on both servers.

@SoonDead Running 2-5 seconds behind. can't be the problem..
Now waiting to have the new issues fixed, then i will test it more

**Comment by sebastienvercammen** [comment]
Closing this issue because it's very old and no longer relevant to the current codebase. If the issue still persists for you today, comment on this issue to reopen it with new details (logs, screenshots).
