### ISSUE TITLE
Browser slow with many gyms

### ISSUE THREAD

**Issue by Slivo-fr** [RocketMap/RocketMap#1486]
With many gym displayed, mobile browser get slow
## Possible Solution

The map HTML seems to be reloaded almost every second, even if nothing change. Reducing the refresh or refreshing on change may help ?
## Context

Mapped the whole city gyms for my team
## Your Environment

Chrome mobile on Zenfone 2 for mobile browsing

**Comment by sebastienvercammen** [comment]
Closing this issue because it's very old and no longer relevant to the current codebase. If the issue still persists for you today, comment on this issue to reopen it with new details (logs, screenshots).
