### ISSUE TITLE
[Feature Request] dump-pokestops

### ISSUE THREAD

**Issue by kbtbc** [RocketMap/RocketMap#1487]
Now that active scanning is dead (temporarily I hope) ... I would like to use the spawnpoint and pokestop data I have saved.   I saw this tool, which might make some of this data very useful: https://www.reddit.com/r/pokemongodev/comments/50cxls/what_is_the_best_path_i_could_do_for_xp/

We can currently dump spawnpoints (constrained with the -st flag) ... I'm looking to do the same w/ pokestops (and why not gyms, too?)  

What I'm missing is a pokestop.json file -- I could probably work this out in the code, but I would be starting from scratch since I'm not a dev.    A simple side script to do this would be awesome :-)

**Comment by shadi1989** [comment]
Think this site will do it for you : http://www.pokemongomap.info/

**Comment by kbtbc** [comment]
Thanks for the tip! It's took a little learning, but in Chrome using the Developer Tools and copying the response of mapdata.php from that site, and then feeding it into a json formatter, I was able to get this info.

**Comment by F1delis** [comment]
I have a spawns.json with > 40.000 spawnpoints, but I see now way to load it to the map.

**Comment by StairyNight** [comment]
@shadi1989 Do you suggest that it can be relatively simple for a noob to pull the webpage and then somehow feed the data in local mysql database to show the gym and pokestop locations on the map?

**Comment by m3g4mInD** [comment]
Yeap its simple, i have made that , only php/mysql data ,
Pokestops  : http://prntscr.com/ctbc2e
Gyms :   http://prntscr.com/ctbck2

This is cool for the people who whant atack gyms for coins :)

**Comment by StairyNight** [comment]
@m3g4mInD  Mind sharing the procedure how you did that?

**Comment by m3g4mInD** [comment]
For Gyms:  https://gist.github.com/m3g4mInD/7e981603a852b099675bacb396e1b9c9

For Pokestops: https://gist.github.com/m3g4mInD/b5e1a7e022976765e465601f87b1368f

I'am working on spawnpoints ....
I know the code is not clean and i have some mistakes,but i gonna improve better code.
Thanks.

**Comment by SiteEffect** [comment]
We could add a --dump-pokestops and --dump-gyms and make it being used by -ss scanning to enable spawnpoint scan for Gym trackers and lured Pokémon trackers.

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
