### ISSUE TITLE
[Feature Request] Spawn Points filter 

### ISSUE THREAD

**Issue by PeshBG** [RocketMap/RocketMap#1499]
Hello all,
can anyone make a spawn point filter per type(for example the ones that are active to remain but the grey ones to be removed) Options
1. Remove only gray ones(inactive)
2. Remove all that dont have pokemons(gray and any blue like)
3. Selection based on color type.

This will be helpful if the API is never released to the public and only kept for FPM

Most of us have the data in the SQL DB and that will be useful to implement(the same was as pokestops are hidden when not lured)

**Comment by macinmn** [comment]
um... you can do this now (when functionality returns anyway).  just turn off spawn points, and only show active pokemon.   or are you asking because you are colorblind and can't tell difference in the prior scanned data?

**Comment by TheNewDarkOne** [comment]
Can probably be merged with my request here
https://github.com/PokemonGoMap/PokemonGo-Map/issues/1472

there is  a bit of overlap

**Comment by PeshBG** [comment]
yes it does look similar :) i know i can filter pokemon but with the no search mode(that is used while the new api is being reversed) is a bit crowded on the map in terms of spawn points. as you know the points are the same the timing is the same, so with the nearby tracker in game, you can still limit the location a pokemon that you see there might be on the map. but the gray dots are a bit 2 much :D (and i was hopping for a drop down for the search points to be created by someone more knowledgeable :)

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
