### ISSUE TITLE
[Feature Request] Preserve Historic Gym Data

### ISSUE THREAD

**Issue by SoonDead** [RocketMap/RocketMap#1502]
Currently if a gym receives updated values, the data is overwritten in the database. This pervents you from making queries about how long a gym is standing who captured the gym and when and how a specific player tends to move between gyms.

My simplest solution would be to add an after insert/update trigger on the gym table and log the new values to a history table on every change.

Problems with this:
- No SQLite support
- I have to look through the python code to see if the gym members are already in the database when the `last_updated` is updated, so the members can also be properly tracked (their uids dumped in he history table for example).
- Could potentially slow down the insert/update (not sure if it actually does though).

Any ideas about implementing this properly?

**Comment by m3g4mInD** [comment]
You can do this,using php/mysql/javascript :)

**Comment by SoonDead** [comment]
@m3g4mInD Sorry, I do not understand. My issue is about preserving gym data when it is overwritten by new values. What exactly would I use javascript for here?

**Comment by foltincsaba** [comment]
When the map ran I saved actual gym data to another table on a daily basis, and calculated stable gyms from that. So this would be a cool idea! 👍

**Comment by drallieiv** [comment]
I was thinking about the same thing.

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
