### ISSUE TITLE
[Feature Request] Support for Rectangular search areas

### ISSUE THREAD

**Issue by thatsweater** [RocketMap/RocketMap#1506]
## Expected Behavior

Allow the selection of rectangular search areas such as with TBTerra's spawnScan, which is now obsolete because of the API. This may seem trivial but for people with large areas that are better covered by rectangles than circles, would be very useful, especially to scan for spawnpoints as we believe we will have to as there have been a couple of shifts recently.
## Current Behavior

Circles!
## Possible Solution

Rectangles :)

In spawnScan you enter latlon for the upper left and then bottom right point of each rectangle, in the config file,  here is a link, https://github.com/TBTerra/spawnScan

**Comment by MysticalOS** [comment]
This was actually something i almost mentioned once when I wanted to map out a long country road between two towns. I used beehives to map the towns spawn points but i wanted to also map the spawn points between the two towns that were near the road but not much further then that. so I could use maybe a long thin rectangle to do this. Basically, +1 this

**Comment by TheNewDarkOne** [comment]
This was actually something i almost mentioned once when I wanted to map out a long country road between two towns. I used beehives to map the towns spawn points but i wanted to also map the spawn points between the two towns that were near the road but not much further then that. so I could use maybe a long thin rectangle to do this. Basically, +1 this

**Comment by birdstream** [comment]
Or just give an extra argument to the server like --geofence [coord1,coord2...]? I was trying to learn how to implement something like this from various examples i found on the web but my programming skills are far from good, sadly :/

**Comment by Angelarius** [comment]
I would also like to add that if, like me, you live directly on the waterfront that circle scanning is 50% wasted when half or close to half is over water :) rectangles would help people like me too.

**Comment by TheQL** [comment]
But why not use SpawnScan, once there is a working API, to create such scan areas and load the .json into PGOMap, either into one instance or several, to keep workers in a local scan range.

**Comment by thatsweater** [comment]
The development of spawnScan is over, as TBTerra went off to school or something. It won't work...Not to mention captcha risks that aren't factored into it.

**Comment by TheQL** [comment]
As soon as pgoapi is back, if ever, it might just work. Captcha risks are real though...
But somebody could fork it and resume development for that matter.

**Comment by baskettcase** [comment]
I would really like to have this also. Where I live it would be nice to be able to just get a bottom left point and a top right point and have it scan everything in between.

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
