### ISSUE TITLE
Googlemap vs Openstreetmap

### ISSUE THREAD

**Issue by titanicboyke** [RocketMap/RocketMap#1509]
It is also possible to use also the map from OpenStreetMap?
This folder has softer colors what makes playing more enjoyable for you.
![gmap](https://cloud.githubusercontent.com/assets/22316434/20005944/6e06e120-a295-11e6-9f77-65596745a1fa.jpg)
![osm](https://cloud.githubusercontent.com/assets/22316434/20005957/79d3d88c-a295-11e6-9f0f-0b2064f49e90.jpg)

**Comment by F1delis** [comment]
You can easily create your own googlemap style. I did this here for example: [https://github.com/PokemonGoMap/PokemonGo-Map/pull/1488](https://github.com/PokemonGoMap/PokemonGo-Map/pull/1488)

**Comment by titanicboyke** [comment]
day and night is not just another map where I wanted to see more details.

**Comment by FrostTheFox** [comment]
I've discussed a little about OpenStreetMaps integration with custom tileservers, atm its not a priority but it's on our list to look at.

**Comment by Borges-Wellington** [comment]
@titanicboyke @F1delis  Please can anyone add OpemstreatMap to RM?

**Comment by FrostTheFox** [comment]
We're still looking at integration with Leaflet or some other OSM enabled library sometime in the future. We're just reviewing our options in terms of tileservers, because many would not be happy with the increased traffic from RM users.

**Comment by sebastienvercammen** [comment]
Closed, this is a very old issue. Any feature requests are now handled via http://vote.devkat.org and if any issue reported in the issue is still related to current code, a new GitHub issue should be opened.
