### ISSUE TITLE
[Feature Request] Display Trainer + Detailed Gym Information

### ISSUE THREAD

**Issue by QuadTog** [RocketMap/RocketMap#1514]
Pogom.db stores detailed Trainer and Pokemon information but we don't display this on the map.

By editing the Infobox we could show the 'owning' Trainer for each Pokemon. Furthermore we could drill-down into an defending Pokemon's CP and IV's by clicking on them.

The Stats Pane could also be enhanced by allowing users to search a Trainer and then display all gyms that Trainer is defending.

**Comment by WalterMagnum** [comment]
This has been done in #1422.

**Comment by QuadTog** [comment]
I believe that functionality is currently broken as others and now I, have encountered the issues mentioned within.

But thanks for the prompt reply!

**Comment by jabberjabber** [comment]
#1422 has been merged, this should be closed.

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
