### ISSUE TITLE
[Feature Request]Map Boundaries 

### ISSUE THREAD

**Issue by faketits** [RocketMap/RocketMap#1516]
**As you may know getting accounts to jump around the world can get them banned\captcha\soft ban
setting Limits for cords to a small area\cities can help with this issue.** 

## Expected Behavior
Setting the location that we would like the map to be active at and dumping all other requests.

## Current Behavior
At this moment anyone can change the map location to anywhere and for small topology maps (small cities\ countries) this can mess with the "Statistics" and with the Accounts.

## Possible Solution
adding to config \ runserver tags with 8 variable 2 for east 2 for west 2 for south and 2 for north to set the "Valid Bounds" and other then that dump the change location request.

## Context
This impact my server in couple of ways, mostly i'm trying to get good statistics that can lead the community to learn from the Data we collect and it does not help having remote countries included in the statistics, that and the fact that my accounts teleport all over the world.

**Comment by jeafke** [comment]
This I hardcoded in app.py 
As a temporary measurement u could do something like this


    def next_loc(self):
        args = get_args()
        if args.fixed_location:
            return 'Location changes are turned off', 403
        # part of query string
        if request.args:
			#Added a 1 to the varname
            lat1 = request.args.get('lat', type=float)
			#Added a 1 to the varname
            lon1 = request.args.get('lon', type=float)
        # from post requests
        if request.form:
			#Added a 1 to the varname
            lat1 = request.form.get('lat', type=float)
			#Added a 1 to the varname
            lon1 = request.form.get('lon', type=float)
		
		# 00.00 == maximum latitude     11.11 = minimum latitude     88.88 = maximum longtitude     99.99 = minimum longtitude
        if lat1 < 00.00 and lat1 > 11.11 and lon1 < 88.88 and lon1 > 99.99:
            lat = lat1
            lon = lon1
-
        if not (lat and lon):
            log.warning('Invalid next location: %s,%s', lat, lon)
            return 'bad parameters', 400
        else:
            self.location_queue.put((lat, lon, 0))
            self.set_current_location((lat, lon, 0))
            log.info('Changing next location: %s,%s', lat, lon)
            return self.loc()

**Comment by kevdotcom** [comment]
Every tried using -nsc and -fl? It fixes your search location so nobody can move it around via the Website.

**Comment by faketits** [comment]
@kevdotcom  it's not my intention to fix the location.. just not to get out of the scanning zone

**Comment by faketits** [comment]
@jeafke  i've try to implement your code and receive:

Traceback (most recent call last):
  File "/root/PGM0.45/PokemonGo-Map/runserver.py", line 22, in <module>
    from pogom.app import Pogom
  File "/root/PGM0.45/PokemonGo-Map/pogom/app.py", line 250
    def next_loc(self):
                      ^
IndentationError: unindent does not match any outer indentation level

got any idea?

**Comment by faketits** [comment]
@jeafke you sir have saved my life :) thank you!

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
