### ISSUE TITLE
Gym not scanned

### ISSUE THREAD

**Issue by willydk** [RocketMap/RocketMap#1545]
![image](https://cloud.githubusercontent.com/assets/2586095/20289361/766d951a-aa8e-11e6-94e9-94abd4b84d82.png)

There should be a gym where I circled in the image, however, this 700m scan with --no-pokemon somehow cannot see this gym...

Does anyone know where I can shortened from 700m to maybe 600m?

**Comment by Obihoernchen** [comment]
Do you have the most up to date version and use https://github.com/pogodevorg/pgoapi in requirements.txt?

**Comment by willydk** [comment]
Pretty sure I do,

requirements.txt
git+https://github.com/pogodevorg/pgoapi.git#egg=pgoapi

**Comment by Obihoernchen** [comment]
try to change this to <500:
```bash
grep -n 'self.step_distance = 0.900' pogom/schedulers.py
101:            self.step_distance = 0.900
253:            self.step_distance = 0.900
```

**Comment by willydk** [comment]
thanks, will do

**Comment by willydk** [comment]
I thought it was 700m, but its 900m!

**Comment by Obihoernchen** [comment]
Don't forget to increase your -st by two.

**Comment by willydk** [comment]
yea, thanks so much

**Comment by springjools** [comment]
Hasn't niantic increased this to 1000m?

**Comment by sebastienvercammen** [comment]
Closing this issue because it's very old and no longer relevant to the current codebase. If the issue still persists for you today, comment on this issue to reopen it with new details (logs, screenshots).
