### ISSUE TITLE
[Feature Request] Write account names into a captcha.csv when they encountered and solved a captcha

### ISSUE THREAD

**Issue by Arengo** [RocketMap/RocketMap#1553]
The most recent commit to automatically solve captcha'd accounts with 2captcha is really decent. It has a downside though - multiply captcha'd accounts can burn through 2captcha credit when the financially better option would be just to switch it out with a new one. I found out myself that some accounts just encounter captchas much often than others, funny thing is that this is tied to a region with accounts on them all created at another time, all search parameters match other regions which are not that affected

## Expected Behavior

An account encounters a captcha and gets auto-solved. It's account name and optional further account details will be printed into a captcha.csv which can later be analysed by the maintainer instead of manually searching through 100 MB+ log files. This also might enable, when no auto-solve is active, that challenged accounts can be right forwarded to other tools.

## Current Behavior

When two empty scans are found, the account will be checked for captcha. Regardless how often this happens, so a "bad" account can burn through 2captcha credit or just annoy map maintainer and users.

**Comment by chowderchow** [comment]
Don't think this is needed. That's exactly what log files are for. Doing `grep captcha` for your log files will easily tell you which/how many/when accounts are captchad, how many failed the captcha and how often.

**Comment by forcewill** [comment]
How about instead of that, write to db (could be another database) the info

dirty_accounts(Name, statusinstance, status) something like 
myaccountname | pearlharbour | (captched, banned, not activated, ... etc)

so people could build uppon that the tools to do things like,

- Remove  banned accounts from config files/scripts
- Build captcha solutions
- etc

**Comment by crckdns** [comment]
pretty simple to doperate via syslog ^^
Btw there is no official way to log stuff __and__ display the instance console ^^ so useful request.

**Comment by drallieiv** [comment]
The question are there "Other Tools" when you can feed your accounts and resolve captcha manually ?
except pokeAlert withc is mobile based
