### ISSUE TITLE
[FEATURE REQUEST] poketranslate table in db

### ISSUE THREAD

**Issue by roflinger** [RocketMap/RocketMap#1589]
Sorry, I have no clue about adding pull request:
I use it to do analyzes in my area (who is in which gym and with which pokemon and so on, it´s only german atm sorry :D) take it if you need it

CREATE TABLE "poketranslate" ( `pokenr` INTEGER PRIMARY KEY AUTOINCREMENT, `pokename` TEXT )

insert into poketranslate ("pokename")
Values ('Bisasam'),
('Bisaknosp'),
('Bisaflor'),
('Glumanda'),
('Glutexo'),
('Glurak'),
('Schiggy'),
('Schillok'),
('Turtok'),
('Raupy'),
('Safcon'),
('Smettbo'),
('Hornliu'),
('Kokuna'),
('Bibor'),
('Taubsi'),
('Tauboga'),
('Tauboss'),
('Rattfratz'),
('Rattikarl'),
('Habitak'),
('Ibitak'),
('Rettan'),
('Arbok'),
('Pikachu'),
('Raichu'),
('Sandan'),
('Sandamer'),
('Nidoran♀'),
('Nidorina'),
('Nidoqueen'),
('Nidoran♂'),
('Nidorino'),
('Nidoking'),
('Piepi'),
('Pixi'),
('Vulpix'),
('Vulnona'),
('Pummeluff'),
('Knuddeluff'),
('Zubat'),
('Golbat'),
('Myrapla'),
('Duflor'),
('Giflor'),
('Paras'),
('Parasek'),
('Bluzuk'),
('Omot'),
('Digda'),
('Digdri'),
('Mauzi'),
('Snobilikat'),
('Enton'),
('Entoron'),
('Menki'),
('Rasaff'),
('Fukano'),
('Arkani'),
('Quapsel'),
('Quaputzi'),
('Quappo'),
('Abra'),
('Kadabra'),
('Simsala'),
('Machollo'),
('Maschock'),
('Machomei'),
('Knofensa'),
('Ultrigaria'),
('Sarzenia'),
('Tentacha'),
('Tentoxa'),
('Kleinstein'),
('Georok'),
('Geowaz'),
('Ponita'),
('Gallopa'),
('Flegmon'),
('Lahmus'),
('Magnetilo'),
('Magneton'),
('Porenta'),
('Dodu'),
('Dodri'),
('Jurob'),
('Jugong'),
('Sleima'),
('Sleimok'),
('Muschas'),
('Austos'),
('Nebulak'),
('Alpollo'),
('Gengar'),
('Onix'),
('Traumato'),
('Hypno'),
('Krabby'),
('Kingler'),
('Voltobal'),
('Lektrobal'),
('Owei'),
('Kokowei'),
('Tragosso'),
('Knogga'),
('Kicklee'),
('Nockchan'),
('Schlurp'),
('Smogon'),
('Smogmog'),
('Rihorn'),
('Rizeros'),
('Chaneira'),
('Tangela'),
('Kangama'),
('Seeper'),
('Seemon'),
('Goldini'),
('Golking'),
('Sterndu'),
('Starmie'),
('Pantimos'),
('Sichlor'),
('Rossana'),
('Elektek'),
('Magmar'),
('Pinsir'),
('Tauros'),
('Karpador'),
('Garados'),
('Lapras'),
('Ditto'),
('Evoli'),
('Aquana'),
('Blitza'),
('Flamara'),
('Porygon'),
('Amonitas'),
('Amoroso'),
('Kabuto'),
('Kabutops'),
('Aerodactyl'),
('Relaxo'),
('Arktos'),
('Zapdos'),
('Lavados'),
('Dratini'),
('Dragonir'),
('Dragoran'),
('Mewtu'),
('Mew')

select * from poketranslate

**Comment by crckdns** [comment]
how about using already existing German translation with the -L flag?

**Comment by roflinger** [comment]
as i said, i use it to analyze my area..
who is in which gym with which pokemon and so on..
it´s only about analyzing the db

**Comment by SoonDead** [comment]
If you create the table yourself the application will still work.

Or you can look into temporary tables for example that only exists while you run your queries.

**Comment by SiteEffect** [comment]
We could add a additional column to the pokemons table reflecting your set locales id->Pokémon name translations.

**Comment by SoonDead** [comment]
@Arengo just to clarify: what you are suggesting is to store it in the table where all encounters are stored. Yes?

**Comment by SiteEffect** [comment]
Was my first thought because it's the most fitting place, reviewing it makes me think about reusability of data and db load in certain calls

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
