### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ksjrKp/pyproj/

### ISSUE THREAD

**Issue by redking974** [RocketMap/RocketMap#1598]
## Expected Behavior
Installation of requirements

## Current Behavior
Error :
`    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ksjrKp/pyproj/setup.py", line 72, in <module>
        objects = cc.compile(['nad2bin.c', 'src/pj_malloc.c'])
      File "/usr/lib/python2.7/distutils/ccompiler.py", line 574, in compile
        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
      File "/usr/lib/python2.7/distutils/unixccompiler.py", line 124, in _compile
        raise CompileError, msg
    distutils.errors.CompileError: command '/usr/local/arm-marvell-linux-gnueabi/bin/arm-marvell-linux-gnueabi-ccache-gcc' failed with exit status 1
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ksjrKp/pyproj/`

## Steps to Reproduce (for bugs)
1. installation of python (python --version -> 2.7.12)
2. installation of pip (pip --version -> 9.0.1
3. pip install requirements.txt

## Context
I've tried to launch PGM on my NAS Synology DSM6.
I've install python, pip, configure db
I've got an error when I launch pip install requirements.txt

## Your Environment
* Version used: last develop branch
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): DSM6

**Comment by cvharris** [comment]
Check the [prerequisites] page and make sure you've run through everything thoroughly. I am on MacOSX and definitely missed this the first time around. After doing the prereqs I no longer had the error

**Comment by redking974** [comment]
Thanks for reply @cvharris, sadly I check all of prereqs and don't find what I forgot into my installation :/

**Comment by ultrafunkamsterdam** [comment]
had the same issue on debian, so looks like a bug or incompatible package.

**Comment by sebastienvercammen** [comment]
@redking974 If you're still having the problem, try:
```
sudo apt-get install python-dev
```
Map works perfectly fine on Debian (@ultrafunkamsterdam), but I did notice OP is using ARM.

**Comment by redking974** [comment]
Thanks @sebastienvercammen but I've stopped try to install it into my Synology NAS because in fact I don't know if it's possible. Maybe I could try your command line and see. Thanks anyway.
