### ISSUE TITLE
Prepare for Gen2

### ISSUE THREAD

**Issue by stefanvds1** [RocketMap/RocketMap#1605]
Prepare the map scanner for Gen2. 

## Expected Behavior
Icons/encounters should work

## Current Behavior
Not sure

## Context
With Gen2 possibly coming out soon, It'd be good to be prepared.

**Comment by SkOODaT** [comment]
i doubt well see gen 2 this year i could be wrong niantic likes to surprise but they need to add many other features before gen 2 lol

**Comment by TheNewDarkOne** [comment]
Sk00DaT. gen 2 is expected as soon as this thursday

**Comment by SkOODaT** [comment]
TheNewDarkOne thier is nothing saying that it will be thursday and if your referring to the starbucks leak it could mean anything

**Comment by Albert62** [comment]
It was announced today that they will be giving details on  **Dec 12** about more Pokémon being released.

**Comment by filippounitn** [comment]
Probably not a difficult update, but this should be priority number 1 when gen 2 will be released

**Comment by dikkedeur** [comment]
well its now announced that gen2 is coming. or at least 80 new pokemons,

**Comment by SiteEffect** [comment]
Yup, where is the code ;-)
