### ISSUE TITLE
account-recycler sets higher sleep time than needed for 2captcha fails

### ISSUE THREAD

**Issue by smint86** [RocketMap/RocketMap#1611]
## Expected Behavior
When automated solving of a 2captcha challenge (with starting parameters --captcha-solving --captcha-key) fails, it should be retried. 2captchas are solved by users, who make errors sometimes.

## Current Behavior

> 2016-12-07 06:36:06,874 [ search-worker-0][        search][ WARNING] Account NAME is encountering a captcha, starting 2captcha sequence
> 2016-12-07 06:36:10,595 [ search-worker-0][        search][    INFO] Retrieved captcha ID: 2156495445; now retrieving token
> 2016-12-07 06:36:10,924 [ search-worker-0][        search][    INFO] Retrieved captcha token, attempting to verify challenge for NAME
> 2016-12-07 06:36:11,075 [ search-worker-0][        search][    INFO] Account NAME failed verifyChallenge, putting away account for now
> 2016-12-07 06:36:11,075 [ search-worker-0][        search][    INFO] Waiting to get new account from the queue
> 2016-12-07 06:36:14,651 [account-recycler][        search][    INFO] Account recycler running. Checking status of 1 accounts
> 2016-12-07 06:36:14,651 [account-recycler][        search][    INFO] Account NAME needs to cool off for 119.0 minutes due to catpcha failed to verify
> 2016-12-07 06:37:14,654 [account-recycler][        search][    INFO] Account recycler running. Checking status of 1 accounts

## Possible Solution
The 2captcha challenge should be retried at least 2 times before sending the account to sleep. Also, 120 minutes is way to much in this situation. The account worked just fine five minutes after this, when the captcha got solved correctly (after manual restart).

## Steps to Reproduce (for bugs)
1. Use --captcha-solving
2. Wait till a captcha gets solved wrong

**Comment by spammer23** [comment]
-ari 600 for 10 minute wait

**Comment by smint86** [comment]
That would lower the rest interval for all failures, not just for captcha related ones. 

[https://github.com/PokemonGoMap/PokemonGo-Map/pull/1609] points in the right direction, unfortunately just aiming at a 2captcha server timeout. When there is no valid response from 2captch (eg wrong solving) it uses -ari instead.

**Comment by birdstream** [comment]
@smint86 I fixed that so also wrong solving also takes 10 min by default

can be set with -cri or --captcha-rest-interval :)

**Comment by sebastienvercammen** [comment]
Closing this issue because it's very old and no longer relevant to the current codebase. If the issue still persists for you today, comment on this issue to reopen it with new details (logs, screenshots).
