### ISSUE TITLE
Issue on displaying types of moveset

### ISSUE THREAD

**Issue by redking974** [RocketMap/RocketMap#1622]
## Expected Behavior
Display all types of moveset with a background

## Current Behavior
Only several types have background (normal and dragon in my example). As you could see, "Acier" is displaying when I highlight it, but if not it's "transparent" because of color of text and page.
![dd](https://cloud.githubusercontent.com/assets/23528297/21080359/1760b50a-bfad-11e6-9e86-a04addd96738.png)

## Possible Solution
Don't know, maybe CSS ?

## Steps to Reproduce (for bugs)
Open Web GUI and click on a gym

## Your Environment
* Version used:
* Environment name and version (e.g. Python 2.7): 2.7.12
* Operating System and version (desktop or mobile): W10

**Comment by sebastienvercammen** [comment]
Closing this issue because it's very old. If the issue still persists for you today, comment on this issue to reopen it with new details (logs, screenshots).
