### ISSUE TITLE
Corrupted database, integrity error

### ISSUE THREAD

**Issue by AdrienNguyenWorldline** [RocketMap/RocketMap#1636]
## Expected Behavior
When running into speed mode, the initial scan, finds spawnpoints and save in database in what location is which spanwpoint.

Data should be transactional, or integrity checks/repairs done at startup or db clean.

## Current Behavior
But if you encounter a database error you might have inserted the link (scanspawnpoint table) but not the spawnpoint itself.

The stacktrace shown is : 
`2016-12-17 12:12:37,902 [ search-overseer][        search][   ERROR] Schedule creation had an Exception: unsupported operand type(s) for -: 'NoneType' and 'int'
Traceback (most recent call last):
  File "/root/PokemonGo-Map/versions/latest/pogom/search.py", line 383, in search_overseer_thread
    scheduler_array[i].schedule()
  File "/root/PokemonGo-Map/versions/latest/pogom/schedulers.py", line 602, in schedule
    queue += SpawnPoint.get_times(cell, scan, now_date, self.args.spawn_delay)
  File "/root/PokemonGo-Map/versions/latest/pogom/models.py", line 1110, in get_times
    endpoints = SpawnPoint.start_end(sp, scan_delay)
  File "/root/PokemonGo-Map/versions/latest/pogom/models.py", line 1093, in start_end
    start = sp['earliest_unseen'] - (4 - plus_or_minus) * 900 + spawn_delay`

## Possible Solution
Search in your database if this query gives any result : 
`SELECT * FROM scanspawnpoint WHERE spawnpoint NOT IN (SELECT id FROM spawnpoint);`
and clear it with 
`DELETE FROM pokevislyon.scanspawnpoint WHERE spawnpoint NOT IN (SELECT id FROM pokevislyon.spawnpoint)`

## Steps to Reproduce (for bugs)
Insert manually wrong data in DB

## Your Environment
mysql

**Comment by humer2000** [comment]
Hi Folks

I am trying to run PokemonGo-Map on a server with a specific domain name 

I built a windows 2008 Server x32
installed MySQL
Installed Python
Installed PIP and GIT
IIS is runing pythons files correctly, everything is working ok.

I followed installation instructions but the app is not working, 

Can someone please help me to achieve this project and make it works on my server ?

**Comment by hokiepokedad** [comment]
Hmm good find.  We are having the same errors also and will try to delete orphaned entries.  Does that mean that spawnpoint will be missed now if "done" is 1?

**Comment by AdrienNguyenWorldline** [comment]
@hokiepokedad even with a 100% scan and an error like that, pogom will act the same way then when spawnpoints are added and will think it is a new spawnpoint

**Comment by sebastienvercammen** [comment]
Fixed by #2128.
