### ISSUE TITLE
[Feature Request] Make use of nearby_pokemon at forts information

### ISSUE THREAD

**Issue by saintmagician** [RocketMap/RocketMap#1638]
Edit: This is NOT about lured pokemon. This is about "nearby" pokemon for areas where the new tracker is available. See this screenshot: http://imgur.com/gallery/Mj4Fl
The new tracker displays "sightings" (pokemon within 200m of you, that is not near a pokestop) and "nearbys" (pokemon located at a visible pokestop). The game client only ever displays up to 9 nearbys, however the API call to get map info gives you all possible nearbys. This feature request is about displaying these nearbys on the map next to their respective pokestop. Ideally, we'd even be able to match them up to known spawn points. 

When you do the API call to get back map info, you get the following information: capturable_pokemon, wild_pokemon, nearby_pokemon

As far as I can see, capturable pokemon list is the same as the wild pokemon list. PokemonGo-Map currently parses all wild_pokemon and inserts them into the db. The nearby_pokemon list is used only to generate the 'Nothing on nearby_pokemons or wild. Speed violation?' message. 

The nearby_pokemon list contains two kinds of nearby pokemon: pokemon within 200m (appears in game as 'sightings'), and pokemon with attached fort information (appears in game as 'nearby'). The latter category could be parsed and displayed in PokemonGo-Map. You could display them on the pokestop that they are attached to. Although these pokemon won't appear exactly on the pokestop, they are generally within 70m of the pokestop. This would be good enough for most people. The upside is that you can see a LOT of nearby_pokemon - up to 1km away I believe. For example, a single scan near where I live gives about 60 nearby pokemon attached to various pokestops. 

example of nearby pokemon (within about 1km, always attached to a fort that is currently visible)
{'fort_image_url': u'http://lh4.ggpht.com/bkaTb8_dO93oGayYan4HZuWJZgClnI-By1QkGLIU6bkT-rMl3-pC-mNgRf5aH-tYm19D4Ae5_yHJKw6sUlo', 'fort_id': u'39120c0642e34915927f7ffbaf9de9d3.16', 'distance_in_meters': 705.1959838867188, 'encounter_id': 6974047907822660857L, 'pokemon_id': 98}

example of sightings pokemon (within 200m, not attached to a fort)
{'encounter_id': 17934254007354986880L, 'pokemon_id': 16}

example of wild pokemon:
{'last_modified_timestamp_ms': 1482042640750L, 'longitude': 149.10000526448906, 'pokemon_data': {'pokemon_id': 120}, 'latitude': -35.244089105157315, 'spawn_point_id': u'6b17ad4b94f', 'encounter_id': 8196300305619878856L, 'time_till_hidden_ms': -278923631}

Ideas:
- Display nearby pokemon at the pokestop using some kind of fake spawn point, until the same pokemon appears as in wild_pokemon. This way when people scan, they will see all pokemon in all scanned 70m circles, and all pokemon attached to all visible pokestops
- Display nearby pokemon as extra information about a pokestop. So you could click on a pokestop and see recent nearby pokemon attached to it. 
- Have a alternate scanning mode that scans circles with 900m radius instead of 70m radius, and only process nearby pokemon attached to pokestops. This means much faster scanning, but you will only see pokemon near pokestops. For people who play in areas with lots of pokestops, this may be more useful.

**Comment by saintmagician** [comment]
![sample](https://cloud.githubusercontent.com/assets/21219702/21293316/91c0973a-c574-11e6-8a70-de73cac79a19.png)

Here's an example of what I mean. That's from my modified pokemon go map. I get pokemon from the nearby_pokemon list, and make a fake spawn point that's based on the pokemon number (i.e. pokedex number) + pokestop ID. Then I set its lat and lng to be the pokestop's lat/lng with a small random variation (so multiple pokemon at the same pokestop aren't completely overlapping). Then I set time to live to be a minute. 

There's a lot of problems with this though. It doesn't mesh well with alerts. When the same pokemon appears in wild_pokemon, you end up with two of the pokemon (one from the nearby_pokemon list with a fake spawn point, and the real one from wild_pokemon). So yeah, lots of work needed. But I think it's a cool idea. You can very quickly get a snapshot of what pokemon are around in a new area, and in a pokestop-dense area this is most pokemon.

**Comment by jorgitoh** [comment]
This PR will be so good. I guess we need to use -bh -st 1 with this because we cant move the accounts. Good job with this :)

**Comment by smc87** [comment]
https://github.com/PokemonGoMap/PokemonGo-Map/issues/1638

**Comment by jorgitoh** [comment]
Just to be clear. @saintmagician With the actual version, If i use - st 1 with -np ill scan like 1k radius looking for stops  & gym. Are u saying, that with this kind of scan we can get the nearby pokemons to a stop within 70m? That will be really good, because with one account per st with a big sd and get a lots of pokemons regarding of the spawns or wild pokemon and avoiding captchas. I really like a version with "alternate scanning mode" like u said. Good job! I'll keep an eye on this PR. Sry for my english!

**Comment by saintmagician** [comment]
Bit more background on this: the current tracker (http://imgur.com/gallery/Mj4Fl) displays sightings and nearby pokemon. Nearby-poke are always attached to a visible pokestop. They always spawn very close (I believe within 70m, but I'm not 100% sure) to a pokestop. This feature request is not about lured pokemon @smc87 

Thanks for the mockup @Asner . I don't know a lot about how the db works... if you are assigning randomly, is that going to mess up the db? i.e. I understand we keep track of all pokemon that have spawned at a spawn point, and use this information to infer when (in the hour) the spawn point pops. If there's no harm to randomly assigning nearby pokemon to spawn points close to the pokestop, then I defintely think this is the way to go. 

The other problem I see with your approach is that what happens if the nearby pokemon is at a pokestop that we haven't scanned around previously, and therefore don't have spawn points? I think I actually have a solution for this... take a look at this map cell (i.e. one of the things in the response['GET_MAP_OBJECTS']['map_cells'] list): 
![pic 3](https://cloud.githubusercontent.com/assets/21219702/21419904/a79ae8a0-c87e-11e6-9ebc-5c7bbf5a0126.png)

Some cells have a 'spawn_points' list. Some cells do not. Very rarely, some cells have both a 'spawn_points' and 'wild_pokemons' list. I believe (but can't be sure yet) that the 'spawn_points' list is a list of all 'spawn_points' in that cell which currently do not have a pokemon spawned. So if a cell contains fort X on its forts list, it's spawn_points list should contain all x/y coords of spawn points near it. Could you put this data into the spawn points table of the db? Even though we don't have a spawn_point_id, a (lat,lng) pair should be enough to uniquely identify a spawn point. 

@jorgitoh I don't think you'd need to use "-st 1". If this works, you could scan using any scanning mode that currently works, this just means we display more information on the map. Additional pokemon will appear near pokestops, but their locations may be slightly wrong (e.g. on the map it may appear to the right of a pokestop, but when you actually show up at the pokestop, the pokemon may spawn a bit to the left of it. 

The current "-np" scan uses 900m radius circles. This won't work because above a certain speed, you no longer receive the nearby_pokemon list in your responses. There are two ways around this:
- limit the speed to 35km/hour
- scan using 900m radius circles (like the current "-np" scan), except at every scan point, keep repeating the scan until nearby_pokemon are found. In my tests, on average there are three failed scans after jumping to a new location 1.5km away. This means 40seconds per useful scan on average, which I think is still faster than 35km/hour.

**Comment by Asner** [comment]
@saintmagician i used another way.
```python
sp = None
for csp in distance_stops[p['fort_id']]: # distance_stops = Result of the query
    if csp['latest_seen'] > now_secs:
        csp['until_seen'] = csp['latest_seen']
    else:
        csp['until_seen'] = csp['latest_seen'] + 3600 # Time shift 

distance_stops[p['fort_id']].sort(key=itemgetter('until_seen')) # Sorts the dict 
sp = distance_stops[p['fort_id']][0] # Selects the one with less time
log.info('[SELECTED] latest{}, earliest {} for spawn {}'.format(sp['latest_seen'], sp['earliest_unseen'], sp['id']))
```
It selects the spawn point that is about to disappear based on the seconds of the current time (e.g 3350).

For the "randomly" in pokemon table, i assign an attribute called "nearby" (0 or 1) to mark the diference.

For the last part, maybe, but without prediction (using speed-scan to get disappear time).

**Comment by jorgitoh** [comment]
@saintmagician we dont need speed control or something like that with ur idea. We need to create behives with one worker and dont move the account after that, that is was i said -bh -st1 -np. Each worker will check that 900m scan radius every xx second, but that worker ill never move or change his position. With this we can scan a big are with a small numbers of accounts avoiding captcha and speed issues.

**Comment by jorgitoh** [comment]
@Asner do u have a fork or something with this PR?

**Comment by neiljroper** [comment]
I think this is being looked at in potentially the wrong way.  IMO it'd be better to have the nearby pokemon data added to a new table (nearby_pokemon maybe).  This data to be read by the map and added to the pokestop info.  Webhook notifiers would work along the lines of "A <pokemon name> is near <pokestop name> Click here to goto pokestop.

That would be my idea anyway.

**Comment by neiljroper** [comment]
My solution is attached.
I ran a test with -nps -bh -st 1 -w 7 and it worked fine. Pokestops must be on, I had pokemon off to prevent duplicates.

**Comment by neiljroper** [comment]
@jorgitoh sounds like either its the first scan of an area or its parsing pokemon (and using step distance of 0.07 instead of 0.9)  If you are still having issues try contacting me in the discord (user is enayr #2369) and i'll try and help

**Comment by jorgitoh** [comment]
Hi @neiljroper, any news with this?. Im using ur code right now. -bh -st 1, big sd ( like 150 sec ). I dont know why im getting captcha because the workers doesnt move. Did u make any change in ur code?. Regards.

**Comment by SiteEffect** [comment]
I will have a look into this next week.

**Comment by jorgitoh** [comment]
This PR is awesome. 1 account = 1800m. There is a way to using this with API 0.57, I think the radius was down from 900 to 450.

**Comment by jorgitoh** [comment]
Hi @neiljroper can u merge ur code with current 0.57 code?. i'll appreciate that :D

Edit. I read ur code. Like I said before the scan ratio should be 450 instead of 900. And now a nearby monster get 6 items not 5 ( now the monsters have gender )

actual_nearby_pokemons = [n for n in nearby_pokemons if len(n) == 6]

**Comment by FrostTheFox** [comment]
Feature Requests are no longer are taken via GitHub. Please submit FRs using http://vote.devkat.org
