### ISSUE TITLE
Accounts not scanning after returning to queue

### ISSUE THREAD

**Issue by bluemode** [RocketMap/RocketMap#1647]
## Expected Behavior
Once the -ari has completed it should return to the queue

## Current Behavior
I am noticing instances of accounts never actually returning after the script has ran for long periods of time. 

## Possible Solution
blame on someone else and wait for a fix

## Steps to Reproduce (for bugs)
1. I run -bh -w 31 -asi 2000 -ari 1600
2.leave running for a couple hours
3. watch accounts never return to the queue and everything slowly dies
4. profit?

## Context
caused increased usage of !needful in #general 

## Your Environment
Observed on Mac/PC
Python 2.7
Cool tones with a splash of color on love seat

**Comment by eXPeri3nc3** [comment]
I am seeing the same issue. I'm running -speed and -ari

**Comment by Hydrargyrum-Wells** [comment]
This might be the problem fixed by #1578.

**Comment by sebastienvercammen** [comment]
Closing this issue because it's very old. If the issue still persists for you today, comment on this issue to reopen it with new details (logs, screenshots).
