### ISSUE TITLE
Exception while downloading map: filedescriptor out of range in select()

### ISSUE THREAD

**Issue by stefanvds1** [RocketMap/RocketMap#1657]
## Current Behavior
when running -ss with more than 350 workers, i get a warning during the scan.
Exception while downloading map: filedescriptor out of range in select()

## Steps to Reproduce (for bugs)
1.  run -ss
2.  --workers more than 350
3.  'too many open files' limit raised in ubuntu

## Your Environment
I'm running Ubuntu, latest develop clone.

**Comment by v2Mike** [comment]
Use this article to fix. I ran into the same thing with stock ubuntu on my server. It's not from running more workers it is probably from the number of people hitting your website. 

http://stackoverflow.com/questions/21515463/how-to-increase-maximum-file-open-limit-ulimit-in-ubuntu

**Comment by sebastienvercammen** [comment]
Labeled as enhancement: capturing the error and printing a proper explanation will definitely be clearer.

**Comment by sebastienvercammen** [comment]
Fixed in #1807.
