### ISSUE TITLE
default step size for gym-only scanning is too large (misses gyms)

### ISSUE THREAD

**Issue by Stereolab42** [RocketMap/RocketMap#1682]
There are three places in the code similar to this:

            step_distance = 0.9 if args.no_pokemon else 0.07

This means that if you just want to scan for gyms and not pokemon -- by specifying -np on the command-line -- the search step size gets much bigger since gyms can be "seen" from much farther distances. However, I've discovered that 0.9 is TOO large. It misses many gyms. In my tests, it should be no larger than 0.7 to see all gyms. Proof:

1. Set your coords to "37.427292, -122.315022".
2. Conduct a small gym-only scan, clearing the DB (-cd -nk -ng -gi -st 3 -w 5).
3. Pull up the map. You can see three (currently Valor) gyms on the bottom edge of Huddart Park. However, there are actually FIVE gyms here. Two are being missed.
4. Kill the map and pull up search.py and schedulers.py. In the three places it occurs, replace 0.9 with 0.7.
5. Restart the map, clearing the DB. You can now see all FIVE gyms.
6. There are many other coordinates where this happens.

Images attached:

![good](https://cloud.githubusercontent.com/assets/20936860/21745814/cc562c4c-d4e8-11e6-9a62-77510f5b335a.png)
![bad](https://cloud.githubusercontent.com/assets/20936860/21745816/cf7f62bc-d4e8-11e6-92fe-ce5aca9b367c.png)

**Comment by Stereolab42** [comment]
It looks like even 0.7 might not be small enough... found a location where I had to go down to 0.6 to see a specific gym.

**Comment by Imoq** [comment]
I believe that the new specific value is 0.5, it has been corrected in Pogo but perhaps needs a PR to correct that line in the map for -np scans.

**Comment by Stereolab42** [comment]
Ugh. Well that will make gym scanning that much more inefficient. :(

**Comment by SwenWacker** [comment]
Due to problems in finding all gyms I changed in schedulers.py line 145 and 298
+             self.step_distance = 0.450
-              self.step_distance = 0.900

works fine

**Comment by drallieiv** [comment]
It has been fixed by 13054591 at 2017-01-13 14:19:17
