### ISSUE TITLE
Error 32 : Broken Pipe

### ISSUE THREAD

**Issue by Demokdawa** [RocketMap/RocketMap#1758]
This error related to flask is here since october 2016, and slow down the server. 

error: [Errno 32] Broken pipe

To reproduce :
Start server
Check console for data to be requested
Close the window or abort the request
Check terminal

**Comment by sebastienvercammen** [comment]
Please don't delete the template for Github issues.

Edit your description to include the template, a screenshot of the problem (and optionally additional logging details), and we'll reopen.
