### ISSUE TITLE
[Feature Request] automatic stop after 100%  succesful scan

### ISSUE THREAD

**Issue by st0nec0ld** [RocketMap/RocketMap#1775]
Hey guys, my scanner dont run 24/7. i use the "scan here button" when needed and stop it by hand.

Plz create an option/feature > stop scanner automatic after 100% succesful scan.

Example config > scanner with -st 3 with 19 worker (one worker for each circle) and the scanner stops when each worker has one successful scan.

Perhaps 3 - 4 workers as reserve, when some worker fail with scan.

This could replaced all the crapy android/ios scanner app out there.

I hope you unterstand my idea, english is not my native language.

Thx

**Comment by sebastienvercammen** [comment]
Feature requests over at http://vote.devkat.org. Thanks!
