### ISSUE TITLE
Duplicate pokemon/notification

### ISSUE THREAD

**Issue by jagauthier** [RocketMap/RocketMap#1779]
Here's the scenario I've experienced twice.
The map notifies, in the browser, of certain pokemon.  Snorlax, and Lapras are among them.

The other day, I got notification for a snorlax.  I was comfortable, so I did not want to get up and chase it. After the snorlax timed out, the map beeped with another snorlax in the exact location.  I felt this was an error, so I went to the location and confirmed: NO SNORLAX.

This happened again today with a Lapras.  I reviewed my webhooks, and I found that each time the webhook received the information and notified me only the first time.

The subsequent times must be a bug in the frontend somewhere (assumption, but not scanner, or webhook would have received secondary notification as well)

**Comment by walaoaaa1234** [comment]
happened to me, you need to clean database because niantic change some spawnpoint or maybe something wrong with speedscan,

**Comment by sebastienvercammen** [comment]
Closing this issue because it's very old. If the issue still persists for you today, comment on this issue to reopen it with new details (logs, screenshots).
