### ISSUE TITLE
[Feature Request] Make an (optional) switch to stop all scans as soon as the new API is forced

### ISSUE THREAD

**Issue by Imoq** [RocketMap/RocketMap#1784]
This is a feature request, not yet implemented.

## Expected Behavior

When the new API (0.55 coming soon, but applies for any future changes) gets forced, make all scans immediately stopped to avoid accounts flagged/banning.

## Current Behavior

Scans don't check forced API version. 

## Possible Solution

It would be great to add an (optional?) flag to check API = current, and if it isn't, don't scan.

1) Can be achieved by doing some bash script, checking "curl https://pgorelease.nianticlabs.com/plfe/version" each X seconds/minutes and then issue a killall when the number is different to 0.53 (for the current one).

2) Could be done from inside the map, just don't have the technical knowledge to do so, if it receives the "use the new client" message, stop the scans.

## Context

On latest API change, I lost around 85% of my scanning accounts due to be flagged/banned few hours/days after the API change, as it happened while I was sleeping and when I woke up it was too late, my accounts had already been running for hours on old API.

**Comment by jagauthier** [comment]
Put this here for voting:
https://feedback.userreport.com/9eec75e1-1e84-4f02-b254-5e239d896805/#ideas/popular

**Comment by chrissas** [comment]
i have error : sed not read /home/chrissas/RocketMap/Tools/Easy-Setup/../config/config.ini:

**Comment by Imoq** [comment]
That doesn't have anything to do with this, @chrissas , go to Discord for support.

**Comment by ultrafunkamsterdam** [comment]
simple shell script

'''
#!/usr/bin/env bash
API_VERSION=53

[[ $(curl - https://pgorelease.nianticlabs.com/plfe/version | grep -io "$API_VERSION") ]] && RESULT1="true" || RESULT1="false"

sleep 60

[[ $(curl - https://pgorelease.nianticlabs.com/plfe/version | grep -io "$API_VERSION") ]] && RESULT2="true" || RESULT2="false"

if [ $RESULT1 == "false" ] && [ $RESULT2 == "false" ]; then pkill -f runserver.py && exit 1;fi

'''

**Comment by Imoq** [comment]
Thanks, it's also being worked here: https://github.com/RocketMap/RocketMap/pull/1787

**Comment by sebastienvercammen** [comment]
Feature requests via http://vote.devkat.org.
