### ISSUE TITLE
Crash when starting up many accounts

### ISSUE THREAD

**Issue by Zyrix** [RocketMap/RocketMap#1791]
When running with a decent amount of accounts (around 60-100), sometimes there is a crash during startup involving the updating of total stats.

## Expected Behavior
Starting up normally

## Current Behavior
`Traceback (most recent call last):
File "runserver.py", line 91, in run
run_old(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "pogom/search.py", line 475, in search_overseer_thread
update_total_stats(threadStatus, last_account_status)
File "pogom/search.py", line 541, in update_total_stats
last_account_status[username] = copy.deepcopy(tstatus)
File "/usr/lib/python2.7/copy.py", line 163, in deepcopy
y = copier(x, memo)
File "/usr/lib/python2.7/copy.py", line 256, in _deepcopy_dict
for key, value in x.iteritems():
RuntimeError: dictionary changed size during iteration`

## Possible Solution
I think the problem occurs when there are new accounts starting up while the total stats are updated. As there is already a deepcopy used here I don't know why this is still happening.

## Steps to Reproduce (for bugs)
It is hard to reproduce as it only happens in around 1 of 10 script startups. A large amount of accounts is also required.

**Comment by jagauthier** [comment]
I saw this issue with just 3 accounts.

**Comment by tobias86aa** [comment]
I have ended up whit this problem to.

**Comment by sebastienvercammen** [comment]
Closing this issue because it's very old. If the issue still persists for you today, comment on this issue to reopen it with new details (logs, screenshots).
