### ISSUE TITLE
Encountering pokemon not working properly sometimes

### ISSUE THREAD

**Issue by midadami** [RocketMap/RocketMap#1792]
Some pokemon aren't encoutered correctly so IVs and attacks aren't obtained even when the id is the encounter list. With "Some pokemon" I mean that for the same pokemon some have IVs and moves and some don't.

## Expected Behavior

A pokemon should have the IVs and moves after being encountered.

## Current Behavior

Some pokemon aren't encountered correctly so you can't check the IV's or the attacks. It doesn't happen everytime but just enough to be annoying.

## Possible Solution

Do retries in case an encounter wasn't done correctly or had a wrong response. Problem might be linked to Hash Server?

## Steps to Reproduce (for bugs)

1. Place the pokemon id on encounter whitelist.
2. Scan for a while. A % of the pokemon placed on the encounter whitelist will not have IV's and moves.

## Context

Its annoying when you send webhooks for pokemon and the IVs and moves are empty.

## Your Environment

* Version used: Last commit
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Windows 10

**Comment by springjools** [comment]
It has nothing to do with hash server, this issue has always been present. In my opinion is a very small ratio that miss their iv:s, like < 5 %. I solved it by checking for iv:s on my webhook bot.

**Comment by midadami** [comment]
That doesnt solve it, you just ignore the wrong encounters. Ive tried retrying and it doesn't seem to work either.
I guess to fix it we would need to move position a bit to rescan and then try to encounter again.

**Comment by birdstream** [comment]
I'm not sure but i think it may have to do with location jitter?

**Comment by midadami** [comment]
No, I still get empty IVs without jitter.

**Comment by birdstream** [comment]
Ok, just a thought...

But now that i remember this issue has always been there. Do you check IV's on all pokemons...?

**Comment by midadami** [comment]
I don't, only about 40-50 pokemon.

**Comment by springjools** [comment]
It solves it in the way that you don't get any error messages. In my opinion, it is not needed that you must get iv:s of 100% of the pokemons, 99% is okay that too.

**Comment by alexccs** [comment]
@springjools May I know what's the webhook bot you mentioned? it generate console command to search a location get from Telegram?
