### ISSUE TITLE
Captchas bookmarkelt page refreshing too quickly

### ISSUE THREAD

**Issue by Plop** [RocketMap/RocketMap#1797]
## Expected Behavior

Wait 30 seconds before refreshing the page for each captcha

## Current Behavior

After solving a few captchas, the page is refreshed too quickly (not 30 as defined by default, each second, the timer is decreased too fast)

## Steps to Reproduce (for bugs)

1. Open the captcha bookmarklet page
2. Solve a few captchas
3. Watch the timer decreasing too quickly

## Your Environment

* Version used: Commit https://github.com/RocketMap/RocketMap/commit/174967ddab3b54f297eec485da209bc898da9540
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Debian 8

**Comment by walaoaaa1234** [comment]
- You can use -mcr (--manual-captcha-refresh) to change the timer until the captcha solving page refreshes (Default: 30s). You'll see what this means once you use it.

**Comment by Plop** [comment]
Well, I get what this means. The problem is that with -mcr 30, with a few captchas solved, it doesn't last for even 30. Maybe 4/5 seconds only ?

I hope this will help to understand : http://sendvid.com/28w7vkrs
The issue occurs at 0.:29 until the end of the video.

**Comment by walaoaaa1234** [comment]
ooo, always refresh your page before you click on the bookmarklet again, because the script run multiple times

**Comment by neskk** [comment]
@Plop which browser are you using? I tested this in Chrome and Firefox and it was working fine.

**Comment by Plop** [comment]
Using Chrome 55.0.

I tried in private nav, to check if it was one of my extensions, but the issue still occurs.

It seems to work fine if I refresh the page before clicking the bookmarlet again

**Comment by neskk** [comment]
JavaScript timer function is running twice. You should refresh the page and click the bookmarklet again and it should stop that behavior. I've seen that happening too but it's not very frequent. Gonna do some tests and maybe tell window to refresh completely to see if it solves the problem.

**Comment by Plop** [comment]
Yep, it's working fine if I do that.

Thanks for your help and your hard work :)
