### ISSUE TITLE
Gyms are not intermittently not being updated correctly

### ISSUE THREAD

**Issue by ashleykleynhans** [RocketMap/RocketMap#1800]
## Expected Behavior
When RocketMap scans gyms, the gym members should be updated in the DB and the web interface should display the Pokemon in the gym.

## Current Behavior
Occasionally, when RocketMap scans gyms, the gym members aren't updated in the DB and hence the web interface only displays the name of the gym, the prestige and the guard pokemon and none of the Pokemon that are actually inside the gym.

This is an intermittent issue, it doesn't always happen, but when it does, I notice the following error in the logs:

```
2017-02-02 17:32:11,131 [    db-updater-0][        models][   DEBUG] Inserting items 0 to 4.
    whq, dbq)
  File "/Users/ashley/POKEMONGO/PokemonGo-Map/pogom/models.py", line 2204, in parse_gyms
    GymMember.gym_id << gym_details.keys()).execute()
  File "/Users/ashley/venv/lib/python2.7/site-packages/peewee.py", line 3274, in execute
    return self.database.rows_affected(self._execute())
  File "/Users/ashley/venv/lib/python2.7/site-packages/peewee.py", line 2656, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/Users/ashley/venv/lib/python2.7/site-packages/peewee.py", line 3492, in execute_sql
    self.commit()
  File "/Users/ashley/venv/lib/python2.7/site-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/Users/ashley/venv/lib/python2.7/site-packages/peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
```

The gym in the frontend then just always displays like [this](http://take.ms/uX1xu) forever, without ever displaying the Pokemon inside.

## Possible Solution
Investigate and fix the DB query causing the gym updates to fail.

## Steps to Reproduce (for bugs)
1. Scan several gyms
2. Eventually some gym updates will fail
3. Check the logs

## Context
I use RocketMap to scan for gyms, and the gym update is failing to function correctly since I updated from the develop branch earlier today and followed the deployment instructions in Discord. Prior to the latest update, everything was functioning perfectly.

## Your Environment
* Version used: current develop branch
* Environment name and version: Python 2.7
* Operating System and version: Mac OSX

**Comment by springjools** [comment]
Cannot reproduce the bug: needs more information regarding user development version and configuration.

**Comment by ashleykleynhans** [comment]
@springjools doesn't happen with MySQL, only happens with SQLite. DB gets locked and instead of retrying, the worker crashes.  DB locks in other places too, but then it just retries.

**Comment by kinar** [comment]
I've also got what appears the be the same problem while using MySQL.

I have ~75 gyms in my scan area and 2 of them refuse to pull in detailed gym info.  They are both on the outskirts of the scanning area but that may be a red herring,  I've tried dropping all gym info from the database (truncate the following tables: gym, gympokemon, gymdetails, gymmember) but when they repopulate, its the same way.  I don't currently have a log turned on so I can't verify if I get the same error in the logs yet.

But if anyone needs me to provide any info, I'd be happy run whatever you guys need to help track this down.

**Comment by dikkedeur** [comment]
@kinar i had the same on 1 gym, that was also on the outer ring of the map that i scan.
a day later it was fine, but it was confusing me as well.
also using mysql, so its not a sqlite thingy alone.

**Comment by jagauthier** [comment]
"Me too" posts are not that helpful.  I've experienced this on gyms that are not on my outskirts.  They resolved themselves with a -cd, but I never dug into it.

**Comment by FrostTheFox** [comment]
Since the reporter stated this issue only occurs on SQLite, and that is now long gone, I'll assume that this issue is no longer a problem. If it is, please feel free to reopen.
