### ISSUE TITLE
Manual captcha token does not return to server with SSL

### ISSUE THREAD

**Issue by jtp10181** [RocketMap/RocketMap#1803]
## Expected Behavior

Either a warning that manual captcha is not support with the server running on SSL, or for it to actually work

## Current Behavior

I have testing different situations and have determined that what is making it not work for me is enabling SSL
I can access the bookmarlet and I get the stats on it, I can solve the captchas, but the server never gets the tokens back.

If I disable the SSL cert and change the "mcd" setting to be http:// instead of https:// it works as expected.

## Steps to Reproduce (for bugs)

1. Run server in SSL mode with manual captcha setup
2. Try to solve a manual captcha
3.
4.

## Your Environment

* Version used: Current Pull https://github.com/RocketMap/RocketMap/commit/4471f748b83f234d465815f58439956f8e5dedaf
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): WIndows 7 x64

**Comment by FrostTheFox** [comment]
So, I'm not very knowledgeable on this function yet. But if you or someone else could try this with an *nginx reverse proxy* setup for TLS rather than the built in map function, that'd be helpful to know.

**Comment by myntath** [comment]
I run SSL (and cloudflare) and I haven't had a problem. I am on nginx setup with a reverse proxy, always have been.

**Comment by jtp10181** [comment]
I just setup nginx last night. Haven't done the SSL part yet. What should I test? Set the -mcd to the URL being used for ngnix I'm guessing? Otherwise I was thinking of sending it back to the http (not ssl) map address and port to make it work if it's an ssl cert issues.

**Comment by neskk** [comment]
Please provide logging/debug information to support your claims. I just tested the system with SSL an it's working fine.

![image](https://cloud.githubusercontent.com/assets/2057020/22620308/df7e5870-eb00-11e6-9e11-a1980a53eb36.png)

**Comment by jtp10181** [comment]
Ok here is the vv debug logs with "[captcha-" on a working setup on regular http within my local network only. Going to work on the not working info now, I will find that debugging stuff in chrome too and see if anything is suspect.

[Captcha-Working.txt](https://github.com/RocketMap/RocketMap/files/752535/Captcha-Working.txt)

**Comment by jtp10181** [comment]
Ooooook. So I tested this last night and it WOULD NOT work. Did the exact same thing today and now it works fine. I tested it pretty heavy too, I ran through at least 30 on internal LAN and external mobile devices (off wifi). 

So I will re-open this issues if I if starts doing it again.
