### ISSUE TITLE
Missing sprite files Error

### ISSUE THREAD

**Issue by sanals** [RocketMap/RocketMap#1809]
There is an error when running the program for the first time sayin "Missing sprite files"

## Expected Behavior
To function without error

## Current Behavior
I encounter the following error

2017-02-06 18:40:51,359 [      MainThread][     runserver][CRITICAL] Missing sprite files.

The commands I gave are

python ./runserver.py -a ptc -u user_name -p password  -l "76.30448, 9.96914" -st 3 -k map_key

## Possible Solution
I don't know how python works. I folllowed the steps without any error. Although had some warnings when running command "npm install", few depricated versions for minimatch,  graceful-fs, node-uuid.

## Steps to Reproduce (for bugs)
Normal steps should be enough

## Your Environment
PC, Windows 8.1
downloaded files from provided links, except pip was from "https://pip.pypa.io/en/stable/installing/'

**Comment by Thyllz** [comment]
Sprites has been removed intentionally. You should check discord

**Comment by jtp10181** [comment]
Why don't they have some generic safe sprites for the default? Could just be different colored shapes or something, but at least it would work to start off. If I had not already been on discord and known I would have been very confused.

**Comment by sanals** [comment]
Thats bad. I have no idea what to do with discord to make this projet run. Is there any guide?

**Comment by Thyllz** [comment]
https://rocketmap.readthedocs.io/

https://discord.gg/PWp2bAm

**Comment by sebastienvercammen** [comment]
Intentional, not an error. Read the docs or join us on Discord.
