### ISSUE TITLE
Invalid return code from buildpack 

### ISSUE THREAD

**Issue by CatchMeImFamous** [RocketMap/RocketMap#1811]
There is a bug but dont know where it come from.

If we want to deploy with Scalingo following link, there is this message while deployment : 

 !     An error occured when preparing deployment
 !   Error deploying the application
 !   → Invalid return code from buildpack 

Maybe the buildpack have to be updated ?

**Comment by FrostTheFox** [comment]
Deployments aren't officially supported, in fact, they're likely to be removed from the readme in the near future.
