### ISSUE TITLE
[Bug] Navigation link to GMaps doesn't work on other languages than english

### ISSUE THREAD

**Issue by PoUpA** [RocketMap/RocketMap#1812]
## Expected Behavior
Navigation link to GMaps should open the directions in google map
## Current Behavior
If google is set in french for example, it look for "Current location" (in english) and it fail as it mean nothing in french.

## Possible Solution
to fix the bug correct file static/js/map.js  and replace the function openMapDirections with this : 
`function openMapDirections(lat, lng) { // eslint-disable-line no-unused-vars
    var url = 'https://www.google.com/maps/?daddr=' + lat + ',' + lng
    window.open(url, '_blank')
}`

## Steps to Reproduce (for bugs)

1. Set your logged google account to another language than English (ie French)
2. go on a RocketMap instance
3. Click on a pokemon
4. Click on navigation link
5. Watch gmaps fail

## Context
Navigation is not possible if your google account is set to something else than english

**Comment by FrostTheFox** [comment]
Changed in 6877c41, thanks.
