### ISSUE TITLE
Config filter to remove common Pokemon completly

### ISSUE THREAD

**Issue by JRCrawford** [RocketMap/RocketMap#1814]
## General Summary
Dealing with all the Pokemon requires a lot of processing. It would be great to have a filter that will remove displaying certain Pokemon completely and forcing the user never to be able to see it.  A working example of this can be seen here: https://melpogomap.com/

## Expected Behavior
Add a line like this to your config file:
```hide_from_frontend: [13, 16, 21] #hiding weedle, pidgey and spearow```

1.) Speed.  Simply having more Pokemon on your frontend slows down the website.  That is one of the reason why https://melpogomap.com/ works so fast... they refuse to show common pokemon.
2.) Usability. Seeing tons of pidgeys or weedles is not helpful to anybody really and sometimes you can't see the rarer Pokemon right away due to all the other "Common Pokemon" littering the page

**Comment by jagauthier** [comment]
This is not a bug, but a feature request.  I would recommend putting this at 
http://vote.devkat.org

**Comment by sebastienvercammen** [comment]
As @jagauthier has already explained, future requests go on http://vote.devkat.org/.
