### ISSUE TITLE
[FEATURE REQUEST] Adjustable time for Lures

### ISSUE THREAD

**Issue by FMKaiba** [RocketMap/RocketMap#1817]
Since we have had more than one ( two ) events that affect the time the lure is good for, adding a setting to adjust the 'is a pokestop luring' display would be advisable.

## Possible Solution
Either a command line flag accepting an integer for amount of minutes the lure will show as active with the default of 30. OR an option on the pullout menu ( on the left ) for lure time, under the pokestop settings.

**Comment by SiteEffect** [comment]
There are two PRs right now addressing Lured Pokéstop timers.

**Comment by sebastienvercammen** [comment]
Feature requests: http://vote.devkat.org.
