### ISSUE TITLE
Speed scan slowly grinds to halt, misses scans, 100% cpu - logs inside

### ISSUE THREAD

**Issue by dajoker17** [RocketMap/RocketMap#1822]
## Expected Behavior

Speed scan should continue to run without requiring restarting every day or so, or using 100% cpu

## Current Behavior

On some instances it will run for a number of hours, then slowly start pegging the CPU, fail to schedule new scans, start missing scans (too late for scan). 
This seems to occur randomly on different instances over time.  I have tried moving co-ordinates and this restart the initial scan but will eventually fail again.  I am almost always guaranteed to have multiple instances doing this a few days after a nest migration, making me wonder if its a spawn point issue?  Mostly it goes away if the database is dropped and recreated.  on this instance the initial scan has not completed, but I have seen the same behaviour on 100% too.

Sorry for the massive log file, but I thought a complete log might be handy to find out whats going on. 

[well1f.zip](https://github.com/RocketMap/RocketMap/files/775218/well1f.zip)

Summary:
The instance last scanned at line 36,9473
It then seems stuck in this loop:
2017-02-15 06:46:22,801 [    db-updater-3][        models][   DEBUG] Inserting items 0 to 1.
2017-02-15 06:46:22,816 [    db-updater-4][        models][   DEBUG] Inserting items 0 to 60.
2017-02-15 06:46:23,598 [    db-updater-0][        models][   DEBUG] Upserted to WorkerStatus, 60 records (upsert queue remaining: 0).
until I restarted it restarted on line 36,9937 Where it continued to run and quickly updated the map with the missing scans.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
Latest, develop build, windows server 2012 hyper-v, dedicated mysql database,

* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by myntath** [comment]
I was just having something similar to this happen to me yesterday. Noticed number of pokemon scanned was log after investigation I saw that CPU was at 100% all from one instance (out of four). After a restart still 100% until all scans were found then it seemed to be doing alright. I went to bed but this morning I see that the scans dropped off again.

I will try investigate if I can repeat this.

**Comment by dajoker17** [comment]
Its repeated at every nest migration for me.  It sometimes takes days to show up.
I have tried picking a new location on the map and starting the initial speed scan again with the same results.
I also noticed all the summary information in the status page goes missing on these instances, with 0 items scheduled (although this may not be related).  Workers are however still scanning and updating.
This leads me to suspect the issue is with the spawn points or tth timing that causes this behaviour, as the only solution I found was to -cd and start again.

**Comment by myntath** [comment]
I hadn't noticed this after a nest migration before, but I have semi-regularly cleared my database so that may not be the problem.  I backed up and then dropped the relevant tables rather than clear the whole db and that has fixed the problem for me. 

I haven't been able to identify anything suspicious in the logs in relation to this, although I didn't run a full debug level log.

This also means I (probably) have a set of tables which could probably be used to investigate the problem. I think this is a bit beyond me but I'm willing to help out someone or share my tables.

**Comment by dajoker17** [comment]
A bit more digging today: 
It seems to happen to me more on large -st25+ (with many Empty cells)
2017-02-14 20:33:05,051 [ search-overseer][    schedulers][    INFO] Initial spawnpoint scan, 14861 of 14885 bands are done or 99.8% complete
2017-02-14 20:33:05,316 [ search-overseer][    schedulers][    INFO] Found 1753 spawn points within hex

Overseer is taking 5m+ to refresh the queue
2017-02-15 04:18:21,957 [ search-overseer][    schedulers][    INFO] New queue created with 1362 entries in 468.923000 seconds

So I'm sure if the scheduler is updated every 5m is causing some kind of issue if the queue creation hasn't completed? Next up I will checkup on 1) My CPU is i7-2600 @2.8G running 5vms's, so not extremely fast, maybe a shiney xeon will help?.  2) Perhaps there is an optimisation that will speed up the queue creation? 3) is the Queue creation silently failing somewhere from some other cause?.

**Comment by myntath** [comment]
Of my two instances it is the larger one with many empty cells (ocean) that encountered this issue. I am running on a vps with two vcores using a xeon e5-2620. Most of the time load maybe 15%. When the bug starts 100% usage. Also the instance had been running smoothly for at least a week before I hit this for the first time. Since dropping tables it has been running smoothly again (now for about 24 hours)

**Comment by alexccs** [comment]
My map stucked after a few days of smooth running too. (new db new clone for gen 2) Can't see problem in logs, even after restart, it will just eventually sending workers to that same step until all workers stuck there. 

I restored the DB back to 2 days before and seems temporary fixed it.  I got around 8 x ST11-14 instances, only 2 of them got this problem.

![photo6152128141842294717a](https://cloud.githubusercontent.com/assets/20939421/23197661/d4fddc68-f8fc-11e6-9a6b-c71a0e972b51.jpg)

**Comment by hayelf** [comment]
I have the same problem as alexccs. Basically one step is stuck indefinitely

**Comment by SiteEffect** [comment]
#1849  might fix some of your issues.

**Comment by TheCrabity** [comment]
Same issue, even after #1849

**Comment by pki0** [comment]
30x -st 25  instances and one instance has the same problem:

Tried:
changing proxy, changing accounts, changing location, changing workername

After restart still the same issue

**Comment by pki0** [comment]
#1884 Did not fix that problem. Still one instance running at 100% CPU.

Some idea how to delete all spawnpoints and scannedLocations in this hex?

**Comment by myntath** [comment]
I just found a problem with the speed scan routine for hour long spawns. I will create a PR shortly to fix it. Could someone test the following to see if it fixes the problem.

in pogom/models.py, class SpawnpointDetectionData

         query = list(cls.select()
                         .where(cls.spawnpoint_id == sp['id'])
                         .order_by(cls.scan_time.asc())
                         .dicts())

the function for classifying hour long spawn points assumed data being fed to it in date order but it was actually being returned sorted by id number. This may have let to certain spawn points not being able to be classified once large amounts of data on the spawn have accumulated and causing lots of load for the cpu.

I don't believe you will need to clear your db after implementing the fix, just restart the instance.

Edit: see https://github.com/RocketMap/RocketMap/pull/1893

**Comment by pki0** [comment]
Thanks! @myntath 
This fixes the issue!

**Comment by Imoq** [comment]
Latest commit #1893  fixed the 100% CPU issue! However, I'm unsure as if this will help with 1-hour TTHs to be found, and/if we need to -cd in order to have now the right despawn times. Ideas?

**Comment by myntath** [comment]
There should be no need to -cd. The bug only meant that it was difficult or impossible to detect some spawn points. It didn't mean they were detected incorrectly. All the data in the database was correct it was just being interpreted wrongly.

**Comment by Imoq** [comment]
Great, thanks! I think I got the impression that something was wrong because a lot of workers started to fall behind after applying this, but that's related to the issue reported here: https://github.com/RocketMap/RocketMap/issues/1905

**Comment by dajoker17** [comment]
This is now resolved for me with the latest pull, four or five days and all instances sitting back on 3-4% cpu.
 great work RM team!
