### ISSUE TITLE
Safari only: Not able to scroll on /stats after clicking options

### ISSUE THREAD

**Issue by johnforeland** [RocketMap/RocketMap#1825]
Safari (macOS and iOS) refuses to scroll on /stats page if I open the options pane and change 'Duration', 'Sort', or 'Order'.

Actually, I don't even need to change the values, if I only open the dropdown menu, close the menu, and the exit the Options pane, I cannot scroll. Safari automatically scrolls back to the top. (So no data load which occurs after duration change)

## Expected Behavior
Should scroll after changing settings in /stats in Safari

## Current Behavior
Does not scroll after changing settings in /stats in Safari

## Possible Solution
Most likely a jQuery bug?

## Steps to Reproduce (for bugs)
1. Open /stats in Safari
2. Open Options
3. Change value in either dropdown menu
4. Scroll disabled / return user to top of page

## Your Environment
* Version used: Newest on everything (Vanilla RocketMap, iOS, macOS, Safari)
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Both

**Comment by SiteEffect** [comment]
Safari on iOS: Hard to scroll through list of exclude/notify Pokémons. When you enabled a few, the list becomes harder and harder to scroll at all while wandering vertically until not reachable anymore.

**Comment by myntath** [comment]
This seems to be an old issue that has never been fixed.

See 
https://github.com/RocketMap/RocketMap/issues/1192
and for a fix on some browsers (not safari)
https://github.com/RocketMap/RocketMap/pull/1268/files

**Comment by TheNewDarkOne** [comment]
I pretty much have to switch to chrome solely for stats panel. it's been an issue in safari forever.

**Comment by SiteEffect** [comment]
So we need some visibility. No knowledge for that :-/

**Comment by sirlindqvist** [comment]
Have same issue

**Comment by pki0** [comment]
![ejwvx1eogyamanc7cadqiuuotyfi0ewpotv-llv7svf3pu4ah1vcztz1avh3ztjwryyj1ekrsd1k6rv6lccks5s3szrtqiozcsr88usrmewtycqoxpwp48whwtxete7me6vu-wmknclx](https://cloud.githubusercontent.com/assets/21021281/23523483/63363c9c-ff87-11e6-9fd2-d33bd1f2cc8e.png)

Why is this not working anymore?
