### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by mhjw** [RocketMap/RocketMap#1836]
## Expected Behavior
Build without errors

## Current Behavior
I get this error: 
```
Running "cssmin:build" (cssmin) task
>> TypeError: Object #<Object> has no method 'isAbsolute'
Warning: CSS minification failed at static/dist/css/app.built.css. Use --force to continue.

Aborted due to warnings.
```
I used --force to force the build, but that results in a zero-length app.min.css in the webinterface.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: latest
* Environment name and version (e.g. Python 2.7): 
Python 2.7.12
* Operating System and version (desktop or mobile):
Debian 8

**Comment by sebastienvercammen** [comment]
Most common problem is an outdated version of npm. Run `npm -v` to confirm (you most likely have a v0.10.x).

To update npm (and node as well, since you most likely have an old one):
```
npm install -g npm
npm install -g n
apt-get uninstall node
n stable
npm install
```
(Don't forget the last `npm install`, you'll need it to rebuild `node-sass`.)

**Comment by irus99** [comment]
This also helped me on centos. I ran this command at the end

npm rebuild node-sass

**Comment by mhjw** [comment]
No, that's not the problem. I'm using npm version 1.4.21

**Comment by sebastienvercammen** [comment]
```
No, that's not the problem. I'm using npm version 1.4.21
```
Latest is npm v4.2.0... Please follow the instructions before saying it doesn't work.

**Comment by mhjw** [comment]
My apologies, I just updated to npm 4.2.0, but I still encounter the same error. 
I'll try a fresh Debian install and will report back.,.

**Comment by mimikq** [comment]
i have the same issue : 

```

Running "cssmin:build" (cssmin) task
Verifying property cssmin.build exists in config...OK
Files: static/dist/css/app.built.css -> static/dist/css/app.min.css
Files: static/dist/css/mobile.built.css -> static/dist/css/mobile.min.css
Files: static/dist/css/statistics.built.css -> static/dist/css/statistics.min.css
Files: static/dist/css/status.built.css -> static/dist/css/status.min.css
Options: rebase=false, report="min", sourceMap=false, banner="/*\n pogomap 2017-04-05 \n*/\n"
>> TypeError: Object #<Object> has no method 'isAbsolute'
Warning: CSS minification failed at static/dist/css/app.built.css. Use --force to continue.

Aborted due to warnings.
```
```


ii  npm                            1.4.21+ds-2               all          package manager for Node.js

pip --version
pip 8.1.2 from /opt/python/lib/python2.7/site-packages (python 2.7)

cat /etc/debian_version
8.7

```
thx for help
