### ISSUE TITLE
[Feature request] Option to show pokemon from lures

### ISSUE THREAD

**Issue by jurbraam94** [RocketMap/RocketMap#1839]
Pokemon from lures

## Expected Behavior
I would like to be able to activate searching for pokemons from lures. More rare pokemon spawn from lures in our area.

## Context
It would be really nice if this is an option in rocketmap. People who dont want to use it dont have to activate it.

**Comment by SiteEffect** [comment]
There are two heavily related PRs right now

**Comment by byjurbraam** [comment]
And nothing happens with both of them, one is cancelled and the other one is two months old..

**Comment by dev042** [comment]
@jurbraam94 if you're faster in coding. Feel free to submit a PR

**Comment by sebastienvercammen** [comment]
Feature requests: http://vote.devkat.org. As mentioned, there are also open relevant PRs to contribute to.
