### ISSUE TITLE
not running on mac missing module hash_server

### ISSUE THREAD

**Issue by mmkevin** [RocketMap/RocketMap#1843]
File "./runserver.py", line 26, in <module>
    from pogom.search import search_overseer_thread
  File "/Users/Kevin/Desktop/isrightkev/webend2/pogom/search.py", line 41, in <module>
    from pgoapi.hash_server import HashServer
ImportError: No module named hash_server

pip --version (pip 9.0.1 from /usr/local/lib/python2.7/site-packages/pip-9.0.1-py2.7.egg (python 2.7))
python --version (Python 2.7.11)

done (rm -rf pgoapi) & (sudo pip install -r requirements.txt) makes no difference

**Comment by dev042** [comment]
instead of `rm -rf pgoapi` what is definitly wrong try ```sudo -H pip uninstall pgoapi
sudo -H pip install -r requirements.txt```

**Comment by pleitegeier** [comment]
same was here on mac...  

source bin/activate
python ./runserver.py........................

**Comment by pleitegeier** [comment]
same was here on mac...

source bin/activate
python ./runserver.py........................

![1](https://cloud.githubusercontent.com/assets/25908182/23137250/39cb0ad8-f7a1-11e6-98eb-06c2d2b1d721.png)

**Comment by TheNewDarkOne** [comment]
sudo -H pip install --upgrade --ignore-installed -r requirements.txt

if you've installed python3 at any point, then you need to define pip2.7 to ensure you install requirements into python2 and NOT python3

sudo -H pip2.7 install --upgrade --ignore-installed -r requirements.txt

**Comment by isrightkev** [comment]
@dev042 this seems to fix the error but now im getting ` [      MainThread][     runserver][CRITICAL] Missing sprite files.`

**Comment by dev042** [comment]
@mmkevin you need to join the rocketmap discord and read #faq :D

**Comment by isrightkev** [comment]
@dev042 sweet thanks fixed it :D

**Comment by sebastienvercammen** [comment]
User error. RTFM.
