### ISSUE TITLE
[Feature Request] Timestamp for a gyms last team change

### ISSUE THREAD

**Issue by Ninjabull** [RocketMap/RocketMap#1847]
Something I've been missing is a timestamp for when the scanner first scanned a gym while held by the current team. I don't want to spend too much time training in a gym I know is highly contested where I probably will be kicked out by the end of the day. 
![Image](https://i.gyazo.com/d4c06eb231f0f59a5a7bae238f2e6cdb.png)

**Comment by dev042** [comment]
that's the game.

**Comment by Daniel-Lilja** [comment]
So is going outside looking for Pokémon without having a map telling you where they all are.

**Comment by mpw1337** [comment]
I had something like that on my own map, not team change, but last time it got modified. That includes team change, but also prestiging/attacking, whether successfully or not.
https://github.com/mpw1337/RocketMap/tree/last_modified <-- didn't tested it yet, but will do it tomorrow.

**Comment by sebastienvercammen** [comment]
Feature requests: http://vote.devkat.org.
