### ISSUE TITLE
[CRITICAL] Missing sprite files.

### ISSUE THREAD

**Issue by derpicknicker1** [RocketMap/RocketMap#1848]
## Expected Behavior

I installed from git and expected to simply start the server
## Current Behavior

When i do ```python ./runserver.py -a ptc -u "username" -p "pass" -l "52.26406019381932, 10.524044036865234" -st 3 -k "xIxxxxD8--9vjxxxxxsXaxxxx3NxxxxxxZxxxM"```
i vget the following error message:
```2017-02-21 10:13:00,391 [      MainThread][     runserver][CRITICAL] Missing sprite files.```

## Steps to Reproduce (for bugs)

1. ```git clone https://github.com/RocketMap/RocketMap.git```
2. ```cd RocketMap```
3. ```pip install -r requirements.txt```
4. ```npm install```
5. ```npm run build```
6.  ```python ./runserver.py -a ptc -u "username" -p "pass" -l "52.26406019381932, 10.524044036865234" -st 3 -k "xIxxxxD8--9vjxxxxxsXaxxxx3NxxxxxxZxxxM"```

## Context
I installed like described [here](https://rocketmap.readthedocs.io/en/develop/basic-install/index.html)

## Your Environment

* Version used: im on commit ae142fa4848811596b8b926f09fa183dd3932fcf
* Environment name and version (e.g. Python 2.7): 
  - python 2.7.11
  - pip 9.0.1
  - node 6.7.0
  - npm 3.10.2
* Operating System and version (desktop or mobile): Win10 Pro N

**Comment by walaoaaa1234** [comment]
https://discord.gg/PWp2bAm

**Comment by lellis2k** [comment]
Can someone post the !sprites message here? It says I have to wait 10 minutes before posting a message in the discord chat

**Comment by ghost** [comment]
You can grab the sprites at [FrostTheFox - Removed link, please consult Discord.]
Simply extract the "static" folder into the root of RocketMap. Replace any files in conflict.

Mac OS Users: You must manually extract the icons folder and the png files into the static folder.

**Comment by sebastienvercammen** [comment]
PEBKAC, RocketMap has removed all copyrighted/trademarked content.
