### ISSUE TITLE
Missing Sprites

### ISSUE THREAD

**Issue by wfg6894** [RocketMap/RocketMap#1850]
Everytime I try to launch a server either via my computer or one hosted of jelastic I get this error.

**Comment by Thyllz** [comment]
All copyrighted content has been removed from RocketMap. Join discord for more info on the subject.

**Comment by SiteEffect** [comment]
You should really join Discord and ask what else you could do

**Comment by malloc67** [comment]
I'm also having this issue on a fresh Fedora build.  I've found two references to the issue, in both cases the respondent simply says "join Discord".  I joined Discord, and when you enter its just an empty display, no observable indication of other users.

Can someone please explain how to workaround this issue ... at least to the extent of allowing the server to start up?

thank you

**Comment by Thyllz** [comment]
Sounds like you haven't connected to rocketmap on discord then, cause there's always people online. Try: https://discord.gg/PWp2bAm
There is anither issue opened for the same problem with a short instruction on how to solve it, but I don't know the rules for linking sprites etc. Hopes this helps though.

**Comment by FrostTheFox** [comment]
The Discord can help you with this.
