### ISSUE TITLE
Accounts waiting for manual reCaptcha during sleep don't get cleaned after successfully being uncaptcha'd

### ISSUE THREAD

**Issue by Arengo** [RocketMap/RocketMap#1851]
Below I am only referring to manual captcha solving without using 2captcha. My observations were made with a large pool of accounts and only a small part working.

## Expected Behavior

When an account get's flagged for a need of a reCaptcha token, it waits the configured time until going to sleep - rotating out into a different queue than failing or resting accounts and waiting for a reCaptcha. This is displayed in the manual captcha solving screen if used. When a token for such an account arrives, it goes back live from sleep to get uncaptcha'd. After that it returns into the general queue of available accounts. While it's entry in the /status page is cleaned.

## Current Behavior

Right now the entry for such an uncaptcha'd account out of sleep is not cleaned from the /status page of the web-server. Instead that account remains being shown and adds up with all other accounts of the same issue. The time of ``Last Modified`` is halted meanwhile because it is not an active worker. This is the case until a regular bigger database cleanup is done by the web app which takes a while.

Hereby, the status-page looks quite bad while in reality it is smoothly working. As a result there is unneeded confusion for the human as well as third-party software using workerstatus data.

## Possible Solution

Make a DB query to delete uncaptcha'd accounts out of ``workerstatus`` table, which were taken out of their captcha sleep, after they are successfully uncaptcha'd.

## Steps to Reproduce (for bugs)

1. Run a big account batch in comparison to active workers
2. Encounter reCaptcha
3. Wait till the captcha'd account goes to captcha sleep
4. Uncaptcha and observe -> don't profit.

## Context

I am manually solving captchas during initial scan with -speed and also using third party software like Worldopole which draws statistics out of ``workerstatus`` table to analyze if the map runs smooth.

## Your Environment

* Version used: Today's pull (21. Feb 2017)
* Environment name and version (e.g. Python 2.7): Python 2.7, newest requirements.txt (--upgrade)
* Operating System and version (desktop or mobile): Ubuntu 16.04

**Comment by SiteEffect** [comment]
Additionally there are cases where captcha'd accounts freeze in the process of being awakened for applying reCaptcha token to uncaptcha it.

**Comment by titanicboyke** [comment]
![untitled-3](https://cloud.githubusercontent.com/assets/22316434/23230582/dc48ab18-f944-11e6-879e-57f87e32e5d6.jpg)
Indeed my workers remain on failid accounts also after solving captcha

**Comment by SiteEffect** [comment]
^this might be unrelated to my Issue though.

**Comment by LoStBoYz** [comment]
I have a similar problem where accounts in an instance won't accept captcha tokens and tokens are piled up in the SQL tokens table.

**Comment by neskk** [comment]
@Arengo This isn't really an issue, it's more like an architectural limitation. Captcha affects accounts not workers... we update worker status because it's the structure responsible for holding most of the scanning information and progress. Since workers can continue to work even after a captcha is encountered, it makes it impossible for us update the information properly. Worker status are already cleaned up every 30min so, it's not pretty but it's not an issue either.
PS - I never had accounts freeze while waking up for captcha solving.
@LoStBoYz I fail to see how tokens pile up since there's a cleanup loop that takes out old tokens.

**Comment by LoStBoYz** [comment]
I have 2 remote PCS connected to the SQL server via the Internet. No issues with connections as far as I can see. Whenever those PCs accounts encountered captcha, those info is registered in the database and registered as captchaed accounts. I can see these in the Web bookmarklet way of clearing captcha. 

Whenever I manually clear the captcha via the Web captcha, these tokens will be passed on to clear the captchaed accounts. But one of the remote PC captchaed accounts somehow never takes the token. You can seen the tokens being 'piled' up in the tokens table. Of course it will be cleared after a period of time, but those affected accounts somehow never get the token and continues to be registered as captchaed. 

In normal circumstances, you will rarely see a token listed in the tokens table as it is passed on to the affected account to be cleared.

**Comment by pki0** [comment]
This is really an issue @neskk 
The Problem was not there until the rewrite of manual captcha solving.
For me Accounts dying one after one because they don't wake up to scan again. After few hours on 0.45 all accounts are not usable anymore because they don't wake up.

**Comment by neskk** [comment]
@klatterhans show me logs or try to debug what is happening because I've been using manual captcha handling for 3 weeks now and it's working perfectly :|

**Comment by LoStBoYz** [comment]
Ok found the problem. The remote PC time was not synch to the server's. It was out by 3 mins. When the remote PC's time was synced to Internet time, I can clear captcha for those map instances in that PC.

**Comment by neskk** [comment]
@LoStBoYz glad you found the mistake.

**Comment by SiteEffect** [comment]
I do not regard this as solved but it is not a major thing right now.
