### ISSUE TITLE
scan failed with message Missing sprite files

### ISSUE THREAD

**Issue by puredota** [RocketMap/RocketMap#1856]
332 [      MainThread][     runserver][CRITICAL] Missing sprite files.

Any one can kindly help me solve the problem? 
Please provide some details.
Thanks

**Comment by Thyllz** [comment]
https://rocketmap.readthedocs.io/en/develop/extras/faq.html

**Comment by BeriBGood** [comment]
Or you could update your install with the new merged PR

**Comment by FrostTheFox** [comment]
Update to get the non-copyrighted sprites, or join Discord to get actual pokemon sprites.
