### ISSUE TITLE
How do i open/start it?

### ISSUE THREAD

**Issue by gobbe123** [RocketMap/RocketMap#1859]
I have downloaded the rocket map developer.zip file. But i dont know how to start it. When i try to use scalingo i need to pay is this free or do you need to pay to use rocket map?

**Comment by Thyllz** [comment]
Should be free, but you should really take a look at https://rocketmap.readthedocs.io/en/develop/
There's lots of guides including basic installation and how to get it up and running.

**Comment by dev042** [comment]
@gobbe123 that's not an issue!

**Comment by FrostTheFox** [comment]
Issues are not for support. Please read the documentation or use the Discord for help.
