### ISSUE TITLE
[Feature Request]: remove long,lat from labels and gyms on map.

### ISSUE THREAD

**Issue by dajoker17** [RocketMap/RocketMap#1866]
## Expected Behavior

My users have taken to blacking out the long/lat on facebook posts as they think having it there assists the spoofers.
I am not sure there's any reason to display this information.
If you click on the "get directions" its not hard to get the long/lat if required.

## Current Behavior

The mon popup, and the gym both display the long/lat. 
![untitled-5](https://cloud.githubusercontent.com/assets/25513982/23318871/5a6f55f2-fb28-11e6-9806-198964ea9e71.jpg)

Remove the long/lat to produce this instead:
![untitled-6](https://cloud.githubusercontent.com/assets/25513982/23318933/9722484c-fb28-11e6-973b-d2c8fd8c02d0.jpg)

## Possible Solution

Any other additions to make the life of the spoofer a bit harder :)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by tegob** [comment]
👎 This is useful information, especially in rural areas where Pokémon don’t always spawn near roads. Removing it would reduce the usefulness of RocketMap.

**Comment by pki0** [comment]
Remove it for yourself in map.js and run npm run build again.

Delete:
https://github.com/RocketMap/RocketMap/blob/develop/static/js/map.js#L441
https://github.com/RocketMap/RocketMap/blob/develop/static/js/map.js#L491
https://github.com/RocketMap/RocketMap/blob/develop/static/js/map.js#L521

**Comment by dajoker17** [comment]
I thought it might be more useful as a command line option (if possible).

**Comment by FrostTheFox** [comment]
The spoofers can run their own map and get this information easily, or even some tools of their own has similar functionality. This is one of those "security through obscurity" type of things. You can remove it on your own map if it makes you or your users feel better.
