### ISSUE TITLE
Duplicate pokemon in gym lable again

### ISSUE THREAD

**Issue by BrownSlaughter** [RocketMap/RocketMap#1879]
https://github.com/RocketMap/RocketMap/pull/1853 was done to fix the sidebar and label but only seemed to fix sidebar

## Expected Behavior
only count the pokemon once

## Current Behavior
![gym2](https://cloud.githubusercontent.com/assets/8204684/23345060/84b87232-fc7f-11e6-9a8e-ef276f6eb96e.png)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: latest dev
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by Obihoernchen** [comment]
Add `.distinct()` above this line https://github.com/RocketMap/RocketMap/blob/develop/pogom/models.py#L616
and see whether this fixes your gym issue

**Comment by BrownSlaughter** [comment]
It does seem to have fixed it, i shall monitor it over a few days and let you know if the error returns

**Comment by M3G4THEKING** [comment]
@BrownSlaughter  You need to delect the gym in db and wait for be scan again and check.

**Comment by BrownSlaughter** [comment]
I cleared my db a day ago and this has definitely fixed the issue, thanks Obihoernchen
