### ISSUE TITLE
Password matching PTC rules preventing server from starting

### ISSUE THREAD

**Issue by FizzBuzz791** [RocketMap/RocketMap#1880]
## Expected Behavior

Using a password that matches/is accepted by the PTC account creation page shouldn't cause the program to crash.

## Current Behavior

Program immediately crashes with; `runserver.py: error: Unexpected line 1 in config.main: password: [ ... , ... , ... , FtvhxVDbKI%#ia6&f2H7]`

The `...` signify passwords created when rules were less strict, they work fine. 6 chars, [a-z], [0-9], [!] 

## Steps to Reproduce (for bugs)

1. Create an account at https://club.pokemon.com
2. Generate the password using something like LastPass; [A-Z], [a-z], [0-9], [!%@#] (20 characters)
3. Add to config.ini and try to run the server.

## Context

Wanting to create more accounts to allow speed scan to work faster and have multiple instances at different locations.

## Your Environment

* Version used: Latest build/commit
* Environment name and version (e.g. Python 2.7): Python 2.7.12
* Operating System and version (desktop or mobile): Windows 10

**Comment by FrostTheFox** [comment]
I do believe this is something we can't really control, configargparse is known for having issues with # and ; characters being in any values of a configuration file.

**Comment by FizzBuzz791** [comment]
Hrmm OK, I didn't realise it was an issue with a third-party parser. Is it possible to escape the values somehow? i.e. if you put the password inside single or double quotes (`'` / `"`) ? Alternatively, could we add something to the documentation so that others that come after me will know it's a known issue?

**Comment by FrostTheFox** [comment]
I'm not sure about escaping it, it's probably just easier to advise not to put #/; into the password. I'll push something like that into the docs in a little.

**Comment by FizzBuzz791** [comment]
Sounds fair. Thanks for the clarification.
