### ISSUE TITLE
Feature Request: Push Notifications

### ISSUE THREAD

**Issue by SkOODaT** [RocketMap/RocketMap#1881]
Some sort of push notification for iphone and Androids to alert of status changes to the scanners IE: api force/paused scanning/accounts failing etc 

their are several push notifications services out there be a very awesome and welcome addition if we knew when the scanners were having issues on the fly mobile......

(i have an iphone so i say push notifications not sure what the android equivalent is)

**Comment by dev042** [comment]
push notification is a overhead and need some significant changes.
you need to store all device ids they want a push notifications and check it with the apple server.

db > saved device id > apple server > check if notification is okay

**Comment by SkOODaT** [comment]
maby even just a simple email would be nice, just some sort of alert incase we are away/sleeping/working etc

**Comment by sebastienvercammen** [comment]
Feature requests: http://vote.devkat.org.
