### ISSUE TITLE
[Feature Request] Notification zones

### ISSUE THREAD

**Issue by Ninjabull** [RocketMap/RocketMap#1883]
Possibility to select a zone on your map were you want different notification rules.

For example: You are at home and want to get notified if there's a Larvitar, Dratini or whatever nearby, pokemon you could go and get quick just for candies. But you also want to get notified if there's like a 100% Larvitar or something else you think is worth to go across the town for.

Currently you would have to get notified for all of them and check if they are close by or worth the effort.

**Comment by Daniel-Lilja** [comment]
Most people probably think this is a waste of time since you could just open multiple incognito windows.

**Comment by sebastienvercammen** [comment]
Feature requests: http://vote.devkat.org.
