### ISSUE TITLE
[Feature Request] User accounts for saving preferences

### ISSUE THREAD

**Issue by bshoemaker12** [RocketMap/RocketMap#1885]
## Expected Behavior

I'd like for there to be an ability to create a user account that I can log into, that will save my Pokemon hidden list.

## Current Behavior

Currently, these lists are maintained with a cookie. I believe it expires rather quickly.

## Possible Solution

Ideal solution: allow you to create an account & maintain your list that way.
Less ideal but still helpful: Make the cookie expire much less quickly, so I only have to hide a bunch of crappy pokemon once

## Context

The map is borderline unusable on mobile, because it's such a wonky experience typing into the box, and I have do it every time I open the browser it seems.

## Your Environment
Android

**Comment by sebastienvercammen** [comment]
Feature requests: http://vote.devkat.org.
