### ISSUE TITLE
Deadlock creating a big DB queue

### ISSUE THREAD

**Issue by Plop** [RocketMap/RocketMap#1910]
## Expected Behavior

No deadlocks and no issue with the DB queue.

## Current Behavior

Running the map for a while will cause deadlocks, and the deadlocks will cause errors like
`[      db-updater-3][        models][ WARNING] DB queue is > 50 (@35470); try increasing --db-threads.`

I'm running two instances : 

`python runserver.py -ns -ac accounts.csv -st 35 -w 70 -l 'LOCATION' --db-threads 89`
`python runserver.py -ns -ac accounts2.csv -st 44 -w 350 -l 'LOCATION' --db-threads 233`

I have to precise that the db-threads are high because I was trying to solve the DB queue issue.
The issue happens with --db-threads 2, with 13, with 89, with 233, with whatever value.

I was running them for a few days with only --db-threads 13 and it was running really fine.
I don't know what causes this issue since only 10 hours as I haven't even connected to the server, the map was running by itself.

I don't know if it's relevant, but I set mysql max_connections to 5000, both in my.cfg & un the config/config.ini file.

Here are some screens

![image](https://cloud.githubusercontent.com/assets/876470/23586782/1c55463e-019d-11e7-9005-0d83ec53171c.png)
![image](https://cloud.githubusercontent.com/assets/876470/23586783/1ee86624-019d-11e7-893e-5358a3eb7ca6.png)

My DB is using InnoDB : 
![image](https://cloud.githubusercontent.com/assets/876470/23586930/d6f9c912-01a0-11e7-9fec-17c3c6d0528f.png)

## Possible Solution

No idea

## Steps to Reproduce (for bugs)

1. Run the map
2. ???
3. Deadlock
4. DB queue increasing
4. Crash

## Context

Trying to run instances of the map.

## Your Environment

* Version used: Latest commit : https://github.com/RocketMap/RocketMap/commit/6e72f9461991c37d832ed6643049c605ff68476d
* Environment name and version (e.g. Python 2.7): Python 2.7 ; MySQL 5.5.54 ; 
* Operating System and version (desktop or mobile): Debian Jessie

**Comment by sebastienvercammen** [comment]
Please add additional information on the deadlock by running this SQL command:
```
SHOW INNODB STATUS
```
(or `SHOW STATUS` if the former doesn't work)

and CTRL+F for `DEADLOCK`.

**Comment by Plop** [comment]
I didn't find any "deadlock", but some "lock".

Here is a screenshot : 
![image](https://cloud.githubusercontent.com/assets/876470/23646521/7277744a-0311-11e7-9e1d-59bea7bb8622.png)

I hope it's what you wanted.

Fyi, I don't have the deadlock error since yesterday. I runned my two instances on a new DB, it seemed to work, so I put them back using the "old" DB with deadlocks errors. No problem since this moment, I really don't understand why.

**Comment by claydy** [comment]
Had the same problem, I had some Triggers activated on the pokemon table. Also when I reboot the DB -Server and the Scanning-Server keeps running it gets deadlocked for some reason

**Comment by sebastienvercammen** [comment]
Is anyone still having this issue on latest commit?

**Comment by dongemus** [comment]
I was getting them consistently when running all my instances, I have shut some down since the RPM changes. Tonight I will pull the latest commit and fire them all up again and then post results here

**Comment by sebastienvercammen** [comment]
@dongemus What were the results?

**Comment by dongemus** [comment]
Sorry I forgot to post the results. Four days ago I did start up all 31 -st 40 instances with 150 accounts each, no encounters, no gym info and was able to get the queue to go up and then the deadlock error. With taking that to 27 instances it didn't happen. 

For me it seems like I ran too much for my hardware, specifically the CPU (i7 hexcore @3.40GHz/core).  I just ordered another machine and will use that to balance the load once I power everything back up (after shadowban fix).

**Comment by sebastienvercammen** [comment]
Issue seems to have been an overloaded server. Deadlocks (or too much waiting for locks) commonly occurs when there are too many threads/instances fighting for the same data, when the server is overloaded, and so on.

Some previous merges have improved this, and the current devkat work (to be released on the 26th) improves locks for common INSERT/UPDATE queries, so we don't expect this to still be a problem.
