### ISSUE TITLE
hash_server missed

### ISSUE THREAD

**Issue by Ramonem** [RocketMap/RocketMap#1912]
## Current Behavior
When i initialize runserver,py i got ImportError: No module named hash_server

## Possible Solution
Change to the correct branch in requirements.txt
I got this message when install: 
Cloning https://github.com/pogodevorg/pgoapi.git (to 6ae636b097c4c8f4ea12d90b10cd4c8b911a2628) to /tmp/pip-build-L8Si7a/pgoapi
  Could not find a tag or branch '6ae636b097c4c8f4ea12d90b10cd4c8b911a2628', assuming commit.
and
Cloning https://github.com/maddhatter/Flask-CacheBust.git (to 38d940cc4f18b5fcb5687746294e0360640a107e) to /tmp/pip-build-L8Si7a/flask-cachebust
  Could not find a tag or branch '38d940cc4f18b5fcb5687746294e0360640a107e', assuming commit.
the rest its ok

## Steps to Reproduce (for bugs)

1. sudo -H pip install -r requirements.txt
2. run python runserver.py -tut

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Linux Mint 18

**Comment by FrostTheFox** [comment]
This is not something in our requirements.txt, this is a dependency of one of our dependencies (likely pgoapi). Those messages are normal, it's just pip letting you know it's installing from git. Probably best to raise the issue with them.
