### ISSUE TITLE
Two errors

### ISSUE THREAD

**Issue by tokar86a** [RocketMap/RocketMap#1913]
I receive this two error quite often it seems to happen whit in one hours of the scanner have started.

http://imgur.com/a/mVTrT

## Your Environment
* Version used: Python 2.7.13 and windows server 2012 R2

**Comment by SiteEffect** [comment]
Seems to me like an issue with your python installation / configuration and usage of multi-threading, carrying some incompatibilities. Have you tried setting everything up new? Including a whole purge of your Python installation? Make sure there are no conflicts if you have also Python 3 installed.

**Comment by sebastienvercammen** [comment]
Image attached is because the process is getting killed by the OS. Check your memory usage or any environment problems (installed requirements, versions) and report back if the issue persists.
