### ISSUE TITLE
Fix Python Path

### ISSUE THREAD

**Issue by ShotgunMavericks01** [RocketMap/RocketMap#1940]
## Problem

Python value for the Path variable was set to **C:\Python27\;**

## Context

"_You have to remove final backslash if that's the case for you too._"

Is what was mentioned in the guide link below. I have no idea how to go about fixing this. Sorry if this is a stupid question/issue but it was said that I can open an issue if I have any problem with this. Thank you!

https://github.com/RocketMap/RocketMap/wiki/Windows-Installation-and-requirements#step-5-fix-python-path

## My Environment
* GIT Version used: (2.12.0 64-bit)
* Environment name and version (Python 2.7.13):
* Operating System and version (Windows 7 Desktop):

**Comment by walaoaaa1234** [comment]
use http://rocketmap.readthedocs.io instead

**Comment by FrostTheFox** [comment]
Please refer to http://rocketmap.readthedocs.io/en/develop/extras/environment-variables-fix.html instead.
