### ISSUE TITLE
db-updater threads get stuck in internal error loop when gymdetails include emoji

### ISSUE THREAD

**Issue by somebro** [RocketMap/RocketMap#1942]
It appears that some gyms have a UTF8 character (or emoji) embedded in the name of the gymdetails. Here is the debug log of the attempt to insert the gymdetails:

`2017-03-19 21:10:45,913 [    db-updater-0][        peewee][   DEBUG] ('REPLACE INTO gymdetails(gym_id,name,description,url,last_scanned) VALUES (%s, %s, %s, %s, %s), (%s, %s, %s, %s, %s)', [u'fe8df783f41248fcba005fd321d20797.16', u'Angry Frog \U0001f438 At The Angry Crab', None, u'http://lh5.ggpht.com/BNmFfE0re2x6VZ-N4KYKeOrEO7jZTrVvZR_TJLVSGQb1-k9qbphg3ek3YyQdTGteHvlXfgju4NeRuxEJDM6w2Q', datetime.datetime(2017, 3, 20, 4, 10, 45, 913022), u'aa93d765aa8d4fb49580669e9afd798c.16', u'Los Olivos Park Regulations ', None, u'http://lh3.googleusercontent.com/1qTKVSXjg8wQU9xncl-ErYcGLoDljVzMjyGiu5gtjT86_mkuwlBdNQt5f73urauDb52h56VM2NqQBdq9KUpC', datetime.datetime(2017, 3, 20, 4, 10, 45, 913094)])
2017-03-19 21:10:45,913 [    db-updater-6][        peewee][   DEBUG] ('SET FOREIGN_KEY_CHECKS=0;', None)`

but here is the error that I'm getting from the db-updater:

`2017-03-19 21:10:45,922 [    db-updater-0][        models][ WARNING] InternalError(1366, u"Incorrect string value: '\\xF0\\x9F\\x90\\xB8 A...' for column 'name' at row 1")... Retrying...`

This is using mysql as the db. Have not tried with sqlite. I have changed the charset and the collation for both the mysql gymdetails and the name column to utf8mb4 and neither seem to resolve the error. Additionally, I'm able to do this mysql insert successfully without any issues using the mysql shell: `Insert INTO `gymdetails2` (`gym_id`, `name`, `last_scanned`) VALUES ('fe8df783f41248fcba005fd321d20797.16', 'Angry Frog \\xF0\\x9F\\x90\\xB8 At The Angry Crab', '2017-03-20 04:10:45');` As best that I can tell it seems to be possibly an issue with peewee or maybe the way we are defining our gymdetails name field in the model?

## Expected Behavior
Should be able to insert gyms (even if they have emoji or other foreign characters in the gym name).

## Current Behavior
Many many errors messages about this issue as the insert is attempted over and over again. Eventually nothing else is able to be inserted into the db while all the db-updater threads are continually trying to insert this gym over and over again and failing every time.

## Possible Solution
1. should not continually attempt to insert this gym into the db an infinite amount of times. At the minimum it should give up after x failed attempts.
2. could potentially strip out any emojis or other potential fatal characters if peewee/rocketmap can't handle them.
3. or even better it should be changed so that this error does not happen and it is successfully able to store and save the gymdetails with a standard install.

**Comment by SiteEffect** [comment]
This should vanish with MySQL and utf8_general_ci encoding

**Comment by friscoMad** [comment]
Fixed by #2015
