### ISSUE TITLE
Launching Docker Image Immediately Stops the Container

### ISSUE THREAD

**Issue by BinaryWasteland** [RocketMap/RocketMap#1961]
## Expected Behavior

Docker starts the RocketMap container and it stays running

## Current Behavior

Docker attempts to start the container and after a second it stops it. Tested on mac osx docker and same issue.

## Steps to Reproduce (for bugs)

1. Start Synology Docker
2. Download Image From Registry
3. Launch setup wizard
4. add to same nw as mysql in setup docs
5. added in env variables (tried without as well) for PTC, Login, Google API Key, DB Info
6. Proceed to next step and click auto launch after finished
7. Click Finish
8. Runs for a second then stops.
9. Checked the logs and only shows variable I can use no setup info...

## Context

Trying to launch rocket map on a docker instance

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):
FrostTheFox/RocketMap Docker Registry Image
Tried with PTC info, location and mySQL Env info and still crashes

**Comment by FragginWagon** [comment]
Ended up having to not use ENV ARGS and instead popped in an execution command and it works....
