### ISSUE TITLE
grunt build failed  on at static/dist/css/app.built.css

### ISSUE THREAD

**Issue by mimikq** [RocketMap/RocketMap#1965]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

If your output looks as above, you can proceed with installation:

cd ~/
sudo apt-get install git
git clone https://github.com/RocketMap/RocketMap.git
cd RocketMap
sudo -H pip install -r requirements.txt
npm install
sudo npm install -g grunt-cli
sudo grunt build

due your installation instruction i went and i failed on last step due that CSS

i checked also github : issues : https://github.com/RocketMap/RocketMap/issues/1836 and i didn't find any solution for that and it is closed.

## Your Environment
* Version used:
pip 8.1.2
npm 1.4.21
* Environment name and version (e.g. Python 2.7): python 2.7
* Operating System and version (desktop or mobile):linux debian 8.7

**Comment by lluisd** [comment]
Try with a newer node (so also npm) version

**Comment by mimikq** [comment]
> ~/RocketMap$ sudo npm version
>   npm: '4.4.4',
>   node: '0.10.29',
> ~/RocketMap$ dpkg -l | grep npm
> ii  npm                            1.4.21+ds-2               all          package manager for Node.js

can you please explain which one you mean ?

**Comment by mimikq** [comment]
`wget -qO- https://deb.nodesource.com/setup_4.x | sudo bash -
and then:

sudo apt-get install nodejs`

this is solution, thx for help

**Comment by jagauthier** [comment]
Would you please close your issue?
