### ISSUE TITLE
Disable "Search" switch

### ISSUE THREAD

**Issue by JoseLSegura** [RocketMap/RocketMap#1966]
On the left menu we have a "Search" switch, that allows anybody with access to the map to disable the search process.

Some people, by accident, touch it when looking at the map from mobile, so I want to hide it in the same way that the set location button can be hided.

**Comment by walaoaaa1234** [comment]
```
-nsc, --no-search-control
Disables search control. [env var: POGOMAP_NO_SEARCH_CONTROL]
```

**Comment by joselsegura** [comment]
Oh, thanks. I didn't know that option. Rocket Map it's a marvelouse surprise box :-D
