### ISSUE TITLE
Sqlite, "Too many sql variables"

### ISSUE THREAD

**Issue by xtrmdev** [RocketMap/RocketMap#1973]
I'm getting an exception:  "Too many sql variables".
When trying to add new areas, after an initial scan has completed in some areas.

## Expected Behavior
Want to be able to use sqlite and add new areas.

## Current Behavior
Adding a new small area with 10 accounts, i get an exception saying "Too many sql variables"

## Possible Solution
Fix the query in models.py: ?
        query = (SpawnPoint
                 .select(SpawnPoint, one_sp_scan.c.cellid)
                 .join(one_sp_scan, on=(SpawnPoint.id ==
                                        one_sp_scan.c.spawnpoint_id))
                 .where(one_sp_scan.c.cellid << cellids)
                 .dicts())
        l = list(query) <--- CRASH  Line 962

Maybe something to do with overlapping scan locations.. ?

## Steps to Reproduce (for bugs)
1. Scan 7 areas with 10 accounts.
2. Wait for it to complete 100%.
3. Scan a new area.
4. Crash.
I have attached the db.

## Your Environment
Latest pyhton.
Git pull 8 hours ago .
Windows 10 64.

[pogom.zip](https://github.com/RocketMap/RocketMap/files/921747/pogom.zip)
![error](https://cloud.githubusercontent.com/assets/3748405/25038175/90abe310-20fd-11e7-996f-016ed660f24f.png)

**Comment by cptmedic** [comment]
Please see this quote below from thunderbot in discord

> SQLite doesn't support real concurrency, so you're limited directly by the read/write speed of your drive and you're hoping that nothing happens concurrently (otherwise it breaks).Higher threads or extra workers = increased odds of SQLite locking up. sqlite also has a very low limit of number of variables that can be used in a single query, which breaks support for medium or large sized maps. You need MySQL if you want a proper database. 

To be honest you need to switch to MySQL as sqlite really isn't a db that has much support due to limitations.

**Comment by FrostTheFox** [comment]
^ `sqlite also has a very low limit of number of variables that can be used in a single query, which breaks support for medium or large sized maps.` This line in particular. You need to switch to MySQL.
