### ISSUE TITLE
[RFC] Remove Gym Pokemon stamina_max

### ISSUE THREAD

**Issue by friscoMad** [RocketMap/RocketMap#1975]
This is a RFC as I don't want to spend the time/effort for creating a PR that needs to modify the DB if there is a known reason to keep this field.

Even if API returns stamina and stamina_max for all pokes, there is no reason to process and store stamina_max (or stamina) for pokemons defending gyms as they will have always the same value, the full stamina of that pokemon.

It is not a great issue but it will reduce DB space and marginal db and cpu load.

## Expected Behavior
It won't change anything.

## Current Behavior
Both fields stamina and stamina_max are stored.

## Possible Solution
Just store one of them, stamina_max should be always the one with the full health, but other projects as Worldople are already using stamina, so I vote for keeping that.

As I said this is just to get opinions before opening the PR, if there is something I am missing please point me and please give your opinion about the field that should be left.

**Comment by Acadia1337** [comment]
I support anything that will decrease db load although I personally do not use detailed gym info.

**Comment by Alderon86** [comment]
I vote for keeping stamina, drop stamina_max!
