### ISSUE TITLE
PTC Access tokens are not working

### ISSUE THREAD

**Issue by MustaSusi** [RocketMap/RocketMap#1976]
Getting a lot of PTC force request of PTC access tokens and them failing.
Reauthenticating with refresh token failed, using credidentials instead
Problem relies at time and server time, yet those are fine at server and at mariadb, only rocketmap/pgoapi doesnt work.

## Expected Behavior
Logins should work and tokens should be fine.
## Current Behavior
Tokens are not accepted.
## Possible Solution
Change server time +1h and all works fine.
## Steps to Reproduce (for bugs)
1. make clone of rocketmap at my comp
2. change config
3. run

## Context
Cant run servers without changing clock 1h forward

## Your Environment
Version latest develop branch
Windows 7 64
Python 2.7.12, MySQL/MariaDB 10.1
![ptcfail](https://cloud.githubusercontent.com/assets/26636447/25073451/be81ceaa-22ef-11e7-86c3-e73846a12e69.jpg)

**Comment by FrostTheFox** [comment]
Not a rocketmap issue, everything login/actually making requests is pgoapi.
