### ISSUE TITLE
hlvl-kph is not working (high level encounters)

### ISSUE THREAD

**Issue by dsorc** [RocketMap/RocketMap#2001]
## Expected Behavior
Level 30 accounts to scan according to the speed limit.

## Current Behavior
Speed limit isn't working:
- scans over 11 minutes
- the 1st level 30 account has 362 encounters out of 503
- average time between encounters for 1st account is 2 seconds
- no captcha was triggered
- I did NOT check distance between spawns

Log containing location and time stamps:
https://app.box.com/s/jt0vyntql6rtlkdyyo5qasq1fm277cbo

## Steps to Reproduce (for bugs)
1. Enable verbose to a log file
2. Add pidgey, ratatta and other common pokemon to the whitelist encounter list.
3. Scan for 10-20 minutes
4. Check the log to see which level 30 accounts are encountering pokemon and how often

## Context
Is the behavior correct? Are the accounts not scanning too often over too great of a distance?
Might this get the accounts banned?
Maybe they are not even providing GPS location and only snipping (safe for now?).

## Your Environment
Stock develop
Python 2.7
Windows 10

**Comment by sebastienvercammen** [comment]
Confirmed. Also found the source, the timing got wrongly committed. Fix coming in ~5 to 15 minutes.

**Comment by dsorc** [comment]
Since the accounts don't get captcha'd I wonder if this fix is actually needed.

**Comment by sebastienvercammen** [comment]
@dsorc Irrelevant, features should do as advertised. Speed limits should be speed limits, the user can always turn them off. Captchas, bans, ...
