### ISSUE TITLE
Manual Captcha solving problem

### ISSUE THREAD

**Issue by shamy13** [RocketMap/RocketMap#2013]
Hello,
I have a problem. In my config file is:

```
#captcha-key:
#captcha-dsk:
captcha-solving: True
manual-captcha-domain: http://127.0.0.1:5000
manual-captcha-refresh: 60
manual-captcha-timeout: 180
```

and on the site http://localhost:5000/bookmarklet show me:

> Working accounts:0
> Remaining captchas:0
> Failed accounts:0

but i Have few account working... Where is problem?

**Comment by shamy13** [comment]
The screen this situation:
http://wstaw.org/m/2017/05/04/Ashampoo_Snap_2017.05.04_01h36m21s_001_.png

please, help me...

**Comment by walaoaaa1234** [comment]
# [Discord](https://discord.gg/rocketmap) for general support @shamy13 
https://rocketmap.readthedocs.io/en/develop/first-run/captchas.html
 no need to set **manual-captcha-domain** if solving captchas within localhost

**Comment by shamy13** [comment]
Yes, but on discord anyone know the reason
@walaoaaa1234 when I delete manual-captcha-domain is working :) Thank you very much :)

**Comment by walaoaaa1234** [comment]
@shamy13 close this issue if fixed
