### ISSUE TITLE
L30 connection pool always fail

### ISSUE THREAD

**Issue by edwardwong80** [RocketMap/RocketMap#2018]
Hello,

I've just updated to latest version a moment ago, but I am seeing this weird error, on discord I am seeing some body else having same problem, not sure if some bugs triggered.
(Note: my normal scanning accounts working well, my server is in IP Ban range so I am using proxy for RocketMap and it works well without L30 encounter)

2017-05-05 12:15:11,095 [         Thread-11][connectionpool][ WARNING] Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f82880fe650>: Failed to establish a new connection: [Errno 111] Connection refused',)': /

**Comment by Stuck7hrottle** [comment]
Is your webhook running?

**Comment by sebastienvercammen** [comment]
> but I am seeing this weird error, on discord I am seeing some body else having same problem, not sure if some bugs triggered

If you'd have asked your question on Discord, someone would have instantly jumped in to use the bot's command `!NewConnectionError`, which gives you this:

> [5:53 PM] BOT Thunderbot: Your webhook server is down.

aka, you've set a webhook server but it's offline or not receiving any messages... 100% unrelated to L30 accounts.
