### ISSUE TITLE
Useless line in models.py

### ISSUE THREAD

**Issue by neskk** [RocketMap/RocketMap#2030]
https://github.com/RocketMap/RocketMap/blob/develop/pogom/models.py#L1951

Line 1951, no need to double check if pokemon_id is in enc_whitelist.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by sebastienvercammen** [comment]
Fixed with #2041.
