### ISSUE TITLE
/search_control URL get hammered a bit excessively

### ISSUE THREAD

**Issue by FeikoWielsma** [RocketMap/RocketMap#2038]
## Expected Behavior
If search control is off (which it is for most people), Rocketmap shouldn't be pinging /search_control every 5 seconds.

## Current Behavior
Rocketmap is pinging /search_control every 5 seconds, which creates a lot of hits and bandwith for no reason. Example: [chrome_2017-05-14_23-58-12](https://cloud.githubusercontent.com/assets/8656008/26038177/801b2f8e-3902-11e7-93d1-0865b758f280.png)
## Possible Solution
If search control is off, don't ping /search_control.

## Steps to Reproduce (for bugs)
Disable search control, look in your access logs with something like goaccess, then look at the requested files.

## Context
I was looking through my access logs, and found a rather big spike of data and hits which look a bit excessive

## Your Environment
Ubuntu 16.04, standard Rocketmap

**Comment by FrostTheFox** [comment]
Closed, #2040
