### ISSUE TITLE
API Watchdog check fails due to proxy -> pauses all scans

### ISSUE THREAD

**Issue by evilmoses** [RocketMap/RocketMap#2047]
![capture](https://cloud.githubusercontent.com/assets/23256850/26150956/b2070fc0-3af8-11e7-9641-0030dcb855dd.PNG)

Watchdog check failed due to Proxy timeout. Scan now paused. No attempt to retry the check was made before I closed the scan 20 minutes later.

Now running with -novc to prevent this occurring.

Have 10 proxies in use for the scan, with the following config settings:

proxy-display: full
proxy-rotation: random
proxy-refresh: 3600

I have restarted having updated the refresh to 600 and added proxy-timeout: 15, but given that I am running with -novc I do not know if this fixes my issue.

Perhaps the watchdog needs to be retried x number of times using all available proxies in the instance of a failure, to prevent false negatives and pausing the scan.

**Comment by Obihoernchen** [comment]
Try to decrease your version-check-interval. Default is randomly set between 60 - 300s.
It should retry every version-check-interval.

**Comment by Obihoernchen** [comment]
There was a bug. Submitting a PR shortly.

**Comment by evilmoses** [comment]
That is perfect, thank you. Will do what you suggested.
