### ISSUE TITLE
API Watchdog check using bad proxy??

### ISSUE THREAD

**Issue by evilmoses** [RocketMap/RocketMap#2051]
Using latest version to test watchdog fix, and it works. The check is being performed again after a failure. Log shows something weird now though, maybe an error, maybe coincidence....

![capture](https://cloud.githubusercontent.com/assets/23256850/26191968/e485722a-3ba7-11e7-8c77-ab4b606125f9.PNG)

It looks in the screenshot that the Watchdog check is using a proxy that is known as being bad? The Proxy refresh is performed, and then one of the timed out proxies is being used for the check? Is that just because it happened so soon after the refresh,. or is there an issue?

At this point, the scans were paused to the watchdog check failure.

**Comment by sebastienvercammen** [comment]
The connection to the Niantic server to check the version has timed out. This is most likely due to a slow-ish proxy.

I'll add a config item to customize the timeout on requests rather than having it hardcoded as it is now. I've assigned myself to remember.

**Comment by evilmoses** [comment]
So setting the proxy-timeout: 15 makes no difference in this case currently? That only applies to the refresh?

The issue I raised, was that the Proxy refresh is done (first few lines), and then the API watchdog check is done afterwards, but using a proxy that had just been determined to be bad, instead of using one of the 3 known to be good. I blacked out all my proxies but the one that is bad to show you. Just seemed weird to use a known bad proxy to do the watchdog check?

**Comment by friscoMad** [comment]
I am not sure but I can see this happening if you have proxy-file and proxy-refresh enabled, due to threads contexts switching overseer thread could start the version check before the proxy check was ended (it has a 5 sec timeout and the error is shown just 1.1 sec after the refresh end message, probably the proxy was selected before the proxy refresh start.

**Comment by tobias86aa** [comment]
I have problem related to this thing to.

21:59:44,492 [   search-overseer][        search][ WARNING] error on API check: IOError(24, 'Too many open files')

I have been forced to shutdown the API watchdog on most of my maps.

**Comment by FrostTheFox** [comment]
@tokar86a That's a different error, relating to ulimit. That's not an RM code issue. Google "too many open files".

**Comment by FrostTheFox** [comment]
Also, I didn't dig in too far, but just from peeking at the watchdog code, it is implementing the same mechanism for fetching a new proxy as the scan threads do (calling get_new_proxy from proxy.py).

I would be inclined to agree with @friscoMad, based on the times your logs are showing.

**Comment by sebastienvercammen** [comment]
Closing because everything related to proxy checking has been reworked. If you test on the latest commit and the issue persists, please comment on this issue and we'll re-open.
