### ISSUE TITLE
JSON Error: PTC often bans IPs now and we don't check for this.

### ISSUE THREAD

**Issue by PKMTracker** [RocketMap/RocketMap#2094]
Issue:
PTC often bans IPs now. We don't do a check for these. IPs appear to be good upon startup, however they cause the famous JSON Error that is being spammed in the Help channel.

Fix:
Check for PTC and Niantic non banned IP state before starting. Add to rotational proxy check as well.

Hope this helps,
Smurfies

**Comment by SiteEffect** [comment]
I think @FrostTheFox is going to address this.

**Comment by FrostTheFox** [comment]
ye i can work on this now

**Comment by sebastienvercammen** [comment]
Fixed in #2114.
