### ISSUE TITLE
Proxy File Refresh Error: File not reloaded properly.

### ISSUE THREAD

**Issue by PKMTracker** [RocketMap/RocketMap#2098]
Issue:
When using a Proxy File and Proxy Refresh, adding new proxies to the file do not become usable. With the recent on-the-fly banning of IPs by PTC, this becomes a bigger issue.

Fix:
Actually reload the file in it's entirety on the Proxy Refresh timer to allow dynamic proxy swapouts.

Hope this helps,
Smurfies

**Comment by SiteEffect** [comment]
Works for me /shrug
Are you sure you don't change file permissions on the fly when adding?

**Comment by PKMTracker** [comment]
Same permissions. I was using Round for the rotation method and adding proxies (not removing). The newly added ones never became used, even if the previous ones became bad/failed check.

**Comment by sebastienvercammen** [comment]
@PKMTracker I'm debugging your issue right now, but the code is exactly the same for proxies loaded at startup and proxies refreshed later on.

Do you see any of these messages in your logs (and if so, which ones)?
```
Periodical proxies refresh disabled.
Loading proxies from file.
Loaded %d proxies.
Proxy file was configured but no proxies were loaded. Aborting.
No proxies are configured.
Checking %d proxies...
```
Proxy rotation methods are irrelevant: `round`, `random` and `none` all base their indexes off the exact same dataset when fetching a new proxy.

I'd also like a screenshot of the following:
```
git status
git log -1
```

**Comment by sebastienvercammen** [comment]
Closing, no response for 11 days. If the problem persist, reply to the previous message and we'll re-open.
