### ISSUE TITLE
Gym and pokestops filters are not working

### ISSUE THREAD

**Issue by JoseLSegura** [RocketMap/RocketMap#2100]
Runiing the latest version, the gym and pokestops filters doesn't filter anything. This filters are:

- Filter pokestops by lured
- Filter gyms by team
- Filter gyms by open spot
- Filter gyms by level

IDK if that filters exist previously to the latest commits (at least lured pokestops already exists), but with the last version, it doesn't work

**Comment by joselsegura** [comment]
My fault: I didn't update the nodejs part and forget to

`npm install && npm install -g grunt-cli && grunt build.`
