### ISSUE TITLE
Active workers are not really active

### ISSUE THREAD

**Issue by friscoMad** [RocketMap/RocketMap#2116]
In the overseer message we are showing active workers but it really only shows the number of workers defined and not the ones that are actively scanning. 

## Expected Behavior
Don't count workers waiting for accounts

## Current Behavior
Just shows the number of configured workers

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by tomballgithub** [comment]
Agreed, found this bit I posted in #pr a while back.  

> I noticed something.  Worker counts (such as in /get_stats) include workers that are 'down'.  This could be workers waiting on a new account (because banned, errors of expired hash key, etc) but there are not any, or due to API change, or other reasons.   IMHO, worker counts should not include workers that are inactive.  I noticed this because I have a script that gets the total worker counts in /get_stats and let's me know if an instance goes down (because worker count drops).  However, I see cases where things have gone down and the worker counts don't change because the instances are still up but they include 'down' workers as active ones.

**Comment by SiteEffect** [comment]
It's just coded as ``args.workers``. I guess we can fix that, @tomballgithub what are the columns you check with your script?

**Comment by tomballgithub** [comment]
I check "Working:" field at http://arengopokemap.xyz/get_stats

**Comment by SiteEffect** [comment]
@tomballgithub which does also not reflect the number correctly, afaik. Tried a fix in the referenced PR.
