### ISSUE TITLE
Raids battles info

### ISSUE THREAD

**Issue by w1n** [RocketMap/RocketMap#2122]
# **Current Behavior**
Too large eggs and bosses on the map
![screenshot_24](https://user-images.githubusercontent.com/6386996/27993939-684807e4-64bb-11e7-83a0-5ee190dce71b.jpg)
# **Expected Behavior**
Standart gym-icon with additional icon of raid boss level
# **Possible Solution**
Show red (active), pink (expected) icon on the left bottom with raid boss level
All additional information show in gym-info tab only
It would be great if raid battle shows something like this
![raid](https://user-images.githubusercontent.com/6386996/27993749-79088e1c-64b8-11e7-9ab4-137bac55ff1f.png)
# **P.S.**
Also would be great to see some filter and notifications of raid levels/bosses
Example: Notify of all Tyranitar bosses on the scan area

**Comment by friscoMad** [comment]
This will be fixed by #2085

**Comment by SiteEffect** [comment]
Also, special raid filtering - parallel to gym - is also somewhere on the to-do list.
