### ISSUE TITLE
Discord and Map issues

### ISSUE THREAD

**Issue by MrCanan** [RocketMap/RocketMap#2123]
Hi,

First, thanks for your awesome work.

I touch nothing, except pull last commits, and get two problems.
I hope find help here, or just for the 1 point to be able to go on Discord. =)

Problem 1 : 
```
Link : https://discordapp.com/invite/rocketmap
I can not join your Discord, because I always get this message : "This instant invite is invalid or has expired".
```
I tested with different browsers and on many supports, but always this message.
So I have no more choice except to post here, even if I guees it is not the good place.

Problem 2 : 
```
2017-07-09 12:20:02,543 [        MainThread][     runserver][CRITICAL] Missing front-end assets (static/dist) -- please run "npm install && npm run build" before starting the server.
```

I test Even if edto do "npm install && npm run build" (as asked) in RocketMap folder, but still no changes when I start it.
I founded some "issue" posts on this GitHub, so I did everything on them, but still no changes.
Link 1 : https://github.com/RocketMap/RocketMap/issues/1445
Link 2 : https://github.com/RocketMap/RocketMap/issues/288

Problem 3 : 
```
2017-07-09 13:05:35,794 [ search-worker-197][       account][   ERROR] Error while downloading remote config: 'DOWNLOAD_SETTINGS'.
Traceback (most recent call last):
  File "/home/RocketMap/pogom/account.py", line 170, in rpc_login_sequence
    parse_download_settings(account, response)
  File "/home/RocketMap/pogom/account.py", line 651, in parse_download_settings
    'responses']['DOWNLOAD_SETTINGS']['hash']
KeyError: 'DOWNLOAD_SETTINGS'
```

I also try to remove everything (RocketMap, pogoapi, etc.) and clone again to retry all, but still have this two errors !
All version (python, pip, npm, etc.) are exactly same as expected.
Do you know why and how can I correct them ?

Very cordially.

**Comment by sebastienvercammen** [comment]
RocketMap is an official Discord partner, so we have a vanity URL: https://discord.gg/rocketmap. If this link is permanently unavailable to you, it means you've been banned from the server.

As for number two, open your terminal (command-line), go to your RocketMap folder, then run `npm run install`.

Screenshot the result and post it here.

The third issue is because your account is most likely banned, so it can't log in. We can indeed improve handling this part.

**Comment by MrCanan** [comment]
Hi,

Thank for your fast answer.


Problem / Answer 1 : 
I came on the RocketMap Discord few times. It was 2 or 3 month ago, for asking help when the Doc was saddly outdated, so when we needed person who already use it to explain us some tips.
But there were always people, on the "help" channel, who was just talking about movies, games and anything else totally unrelated to the channel. So I kindly asked them to stop it, because it prevented seeing useful messages.
And without luck, one of these people, who polluting this "help" channel, had rights on this Discord, so he kicks and bans me, even if it was his fault !
So I asked, in private message, to other members with the same role on the Discord, but they said they did not have the rights for and only him can roll back it, so I thought it was going to be temporary and that I was going to be able to talk again afterwards.


Problem / Answer 2 : 
```
[root]:1> cd /home/RocketMap
[root]:2> npm install
npm WARN lifecycle pogomap@0.1.0~postinstall: cannot run in wd %s %s (wd=%s) pogomap@0.1.0 grunt build /home/RocketMap
```


Problem / Answer 3 : 
I never have this error with Ban accounts, but it is probably a new one due to all recent changements. So no problem, I will use new account when the Problem 2 will be solved. =)


Very cordially.

**Comment by sebastienvercammen** [comment]
@MrCanan 

**Problem 1:** Be realistic. I know our mod team, and odds are you were even banned by Fox or myself. You undoubtedly did something you shouldn't have, just as I'm sure these people weren't "polluting" the channel, rather they must've gotten off-topic for a minute or two as sometimes happens when they're talking about several subjects (originally relating to RocketMap).

If you give me your Discord username, I'll look into it.

**Problem 2:** Sounds like a permission issue. Try the following:
```
npm install --unsafe-perm
```
and show us the result.

**Comment by MrCanan** [comment]
Hi,

Problem / Answer 1 : 
In all cases, I don't want to post anymore on this Discord, but only to be able to read news and others potential useful messages. Simply, because I am sure these people are still there, and even if they write unrelated answer (vulgar limit), they will never be repressed. They just need to ask to member with high rights, and the member they want will be ban, even if it is him who pollute the channel.
Don't worry about it, but I am realistic, it happened exactly what I explained. I have some witnesses, and I am sur you know the problem, like the old forums where young guys always on it win rights and feel have power. =)

Problem / Answer 2 : 
	[root]:1> cd /home/RocketMap
	[root]:2> npm install --unsafe-perm
	...
	Done, without errors.
I also already try :
	cd /home/RocketMap
	chmod 775 /home/RocketMap/static/dist
	pip uninstall -y -r requirements.txt
	pip install -r requirements.txt --upgrade
	npm install -g grunt-cli
	grunt build
	npm install --unsafe-perm

Very cordially.

**Comment by jagauthier** [comment]
Mr Canan> Give him your discord name and he'll look into it.  He's very reasonable, and I've seen him give second chances.

**Comment by sebastienvercammen** [comment]
@MrCanan Language barrier aside, you're avoiding the question and I can only assume you've been rightly banned.

**Problem 2:** "Done, without errors" means it succeeded.

Do you have any other questions? Is something not working?

**Comment by MrCanan** [comment]
**Problem 1 : ** 

I will not waste time to prove something I know being correct, just because someone has more right to do what he wants. Simply banish them, they freely pollute the help channel, then we may want to come back. =)


**Problem 2 : ** 

I know what "Done, without errors" means, and it is the reason why I can post my problem here !

I had the error : 
```
[        MainThread][     runserver][CRITICAL] Missing front-end assets (static/dist) -- please run "npm install && npm run build" before starting the server.
```

I can not use the default instruction, because I got an error : 
```
[root]:1> cd /home/RocketMap
[root]:2> npm install
npm WARN lifecycle pogomap@0.1.0~postinstall: cannot run in wd %s %s (wd=%s) pogomap@0.1.0 grunt build /home/RocketMap
```

So I use the alternative one : 
```
[root]:1> cd /home/RocketMap
[root]:2> npm install --unsafe-perm
...
Done, without errors.
```

**But even if the message say "Done", I still have it.**

So I try also : 
```
cd /home/RocketMap
chmod 775 /home/RocketMap/static/dist
pip uninstall -y -r requirements.txt
pip install -r requirements.txt --upgrade
npm install -g grunt-cli
grunt build
npm install --unsafe-perm
```

**But no change, I always have : "[CRITICAL] Missing front-end assets (static/dist)".**

**Comment by SiteEffect** [comment]
Just throwing this onto you in the hope it's solved by not having a clear solution: ``sudo npm run build``

**Comment by FrostTheFox** [comment]
As the owner of the Discord server, bans are rare and if you were given one it was likely for a good reason. If you don't even give me a name to look into, I have to assume you were rightfully banned and there's nothing I can do.

**Comment by sebastienvercammen** [comment]
@MrCanan You talk about not wanting to waste your own time, yet you don't mind wasting ours.

Issue closed. We have real problems to solve.

**Comment by MrCanan** [comment]
Seriously, I understand why everybody go on Monocle. =)
I also installed it, but I just wanted to give a last chance to RocketMap and his community, but it was a real bad idea.

**Comment by jagauthier** [comment]
You didn't give anything chance.  You pretended you couldn't join the server, then you admitted you were banned. You claimed it wasn't your fault, and when the Discord moderators wanted to look into it for you, you refused their help.

Fun Troll day for you. Bye!

**Comment by MrCanan** [comment]
It is amazing, stop to stick on the Discord problem !
Some guys on the "help" channel doesn't help, because they prefere to speak together about movies, games and other unrelated thing, and if you ask them gently to stop, you become kicked, then banned. It is easier to understand this problem, and I share it to hope it will be not happen again to other person.

The main problem was about : "[MainThread][runserver][CRITICAL] Missing front-end assets (static/dist) -- please run "npm install && npm run build" before starting the server.", even if a lot of solution was tested.
But saddly, as you can see, there is no real solution here, except just some repetitions of already try, so don't worry and don't lose your time. Good bye last chance for RocketMap. =)

**Comment by FrostTheFox** [comment]
No, you don't get kicked or banned for asking people to stay on topic in #help. Stop lying.

**Comment by jagauthier** [comment]
If you have custom .js files in static/js you're going to get that error.  Because the code loops through all the .js files for a grunt compiled version.  So, if you put anything in static/js that doesn't have a grunt built counterpart in static/dist/js then you will also get the frontend error.

What's your discord username again?
