### ISSUE TITLE
Offset account logins to keep hashing requests controlled

### ISSUE THREAD

**Issue by FMKaiba** [RocketMap/RocketMap#2137]
When an account logs in after a search interval of another account finishes, there is a spike in RPM as the account requires ( correctly so ) a bunch of requests to log in and act genuine.

This is perfectly fine, unless in the condition of a large volume of accounts being used at once, which multiplies this issue.

In my case it takes the usual RPM value of 47.8, and brings it up to around 178 RPM.

This causes users to have to pay for a larger RPM key when it might not be necessary if the following were implemented.

## Expected Behavior

RocketMap would have a stable RPM ( Hashing Requests per Minute ) during runtime, when accounts are being rotated out.

## Current Behavior

Huge spike in RPM during the login phase. Going from baseline value of 50 RPM to 180 RPM during switching between accounts.

## Possible Solution

Add a setting to randomize account rest or search intervals ( Would also have the effect of being more human-like ). This way a spike in RPM would be balanced over a larger time period.

## Steps to Reproduce (for bugs)

Run RocketMap with account rest and search intervals like:
account-search-interval: 900
account-rest-interval: 7200

monitor RPM and notice the spike as accounts rotate out.

**Comment by nhumber** [comment]
another approach would be to add a variable to limit the max simultaneous logins at a time or even max logins per minute, all 3 options would help with this problem.

**Comment by sebastienvercammen** [comment]
RM has `--login-delay`, which offsets account logins. Try setting it to `15` or `20`.

**Comment by FMKaiba** [comment]
`[--login-delay]: Time delay between each login attempt`
Problem with that is it mean each of the accounts must fail login first from rate limiting, and then all try simultaneously at the delay specified. It does not offset or stagger accounts.

**Comment by sebastienvercammen** [comment]
@FMKaiba Wrong, you misinterpreted the sentence. `--login-delay` adds a delay between each account logging in, it does stagger accounts.

**Comment by sebastienvercammen** [comment]
No update for 7 days and `--login-delay` already does what was requested. If any problem persists, feel free to comment to re-open the issue.
