### ISSUE TITLE
Status page columns keep resizing

### ISSUE THREAD

**Issue by pogo-excalibur** [RocketMap/RocketMap#2144]
## Expected Behavior
The status page should be easy to read.

## Current Behavior
Whenever an account's status message changes the columns all resize to fit the new text. 

## Possible Solution
At present, the message column is the only one that needs to resize often.
To achieve this, the other columns could be fixed to the minimum required for their content, with the extra space left for the message column.

## Steps to Reproduce
1. Start a search instance
2. View the /status page
3. Watch the columns move around as the account messages update

## Context
Not a big deal, just mildly irritating when checking account statuses.

## Your Environment
Firefox (Windows 10),
Firefox (Android 6.0)

**Comment by pogo-excalibur** [comment]
I'm happy to submit a PR to fix this.

**Comment by sebastienvercammen** [comment]
@pogo-excalibur Go for it, PR it. No one is on this atm.
