### ISSUE TITLE
Account not released when removing inactive proxy

### ISSUE THREAD

**Issue by AEtHeLsYn** [RocketMap/RocketMap#2149]
## Expected Behavior
After proxy refresh, if a proxy is deleted from proxy list (inactive, banned...), account should start a new login with a new proxy.

## Current Behavior
Account doesn't get released, worker stays forever in "logging into account..." but log says "Account xxx proxy xxx is not in a live list any more".

## Possible Solution
Maybe set the account as failed?

## Steps to Reproduce (for bugs)
1. Load a proxy list
2. Block the IP of a proxy using a firewall (Windows firewall works)
3. Wait

## Context
Workerks get stuck as proxies fail, even if they come up some time after.

## Your Environment
* Version used: Last dev
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Windows 10

**Comment by SiteEffect** [comment]
Won't it "fix itself" on the next scan? Just dying when the proxy is really banned.

**Comment by AEtHeLsYn** [comment]
Nope. When assigning a new proxy, as _proxy_url_ is not null, no new proxy is picked. With the PR I submitted before, even if a proxy is assigned we check if the proxy is on the args.proxy list to change it in case it is not.
