### ISSUE TITLE
-tut not setting buddy

### ISSUE THREAD

**Issue by friscoMad** [RocketMap/RocketMap#2158]
After the protobuf rework inventory parsing during tut will fail and not set your new friend as a buddy.
Also we need to test if inventory comes even when we are not asking for it and that it does contain a new poke as due to the last_timestamp maybe we need to do something to get it.

**Comment by CoolCanuck** [comment]
Hi @friscoMad. Is this solved?

**Comment by friscoMad** [comment]
Not yet
