### ISSUE TITLE
Docker pull error

### ISSUE THREAD

**Issue by Alphawarz** [RocketMap/RocketMap#2165]
After a.

> docker pull frosttheffox/rocketmap

starting a container will return:

> [        MainThread][     runserver][CRITICAL] Missing front-end assets (static/dist) -- please run "npm install && npm run build" before starting the server. 

> 

To get the docker image of rocketmap to work.
i simply have to 
`git clone https://github.com/RocketMap/RocketMap.git` 
and then
`docker build -t name .`

## Expected Behavior
After pulling the latest image and creating a container the application should run as intended.

## Current Behavior
Returns error

## Possible Solution
Origins of the problem may be due to outdated Dockerhub or Dockerfile.

## Steps to Reproduce (for bugs)

> docker pull frostthefox/rocketmap 

>

**Comment by Toetje585** [comment]
Also happening for me :)

**Comment by FrostTheFox** [comment]
Unsure of the issue on this one. It doesn't make sense that cloning and building from RocketMap/RocketMap works fine, because Dockerhub builds from here.

**Comment by Alphawarz** [comment]
@FrostTheFox the issue seems to have been resolved
I just did a docker pull just for testing purposes.

Also like you said, it doesn't really make sense that cloning/docker build worked and docker pull didn't.

*Water under the bridge.*

Thank you.

**Comment by Alphawarz** [comment]
I was wrong to close the issue.
It is apparently still happening.
