### ISSUE TITLE
Range choice should use ranges.. not dropdown choices.

### ISSUE THREAD

**Issue by CoolCanuck** [RocketMap/RocketMap#2201]
Using multiple dropdowns for level selection not user friendly. This is why range sliders exist. By switching to a range slider, the amount of visible space for other features is greatly increased. 

![image](https://prod-foundation-forum.s3.amazonaws.com/uploads/part/part_image/29697/jqm_range-sliders.png)

![image](https://user-images.githubusercontent.com/15615155/28691931-983ef70c-72ec-11e7-9610-b64dfb9cb29d.png)

## Context

- Trying to improve the user experience, and to match web standards.

**Comment by sebastienvercammen** [comment]
@CoolCanuck Considering you posted an example, can I assume you will be submitting a PR to improve user experience with range sliders?

**Comment by CoolCanuck** [comment]
Hi,

I dont have the skill to do this. The screenshot is an example from a random website unrelated to pokemon go and I don't have ranges on my map. I have tried to fix it, but no luck

**Comment by thermoscookies** [comment]
would people prefer a slider or a row of check boxes? sometimes I want to show just level 1, 4 and 5. don't care much for the current 2 and 3s.

**Comment by sebastienvercammen** [comment]
@CoolCanuck Since this is not something you will be working on yourself, this is a feature request and it should be posted on http://vote.devkat.org.
