### ISSUE TITLE
Webhook Documentation

### ISSUE THREAD

**Issue by pogo-excalibur** [RocketMap/RocketMap#2203]
## Expected Behavior
Webhook documentation should (at a minimum) be up-to-date.
More webhook examples would also be useful.

## Current Behavior
Webhook documentation hasn't been (materially) updated since May 14th.

**Comment by sebastienvercammen** [comment]
Anyone is welcome to submit an update to the docs, devs have been busy working on code updates.

@pogo-excalibur Can I assume you will take it upon yourself to submit a PR for the webhook docs?

**Comment by pogo-excalibur** [comment]
@sebastienvercammen 
Yes - I may not have time for a few days though

**Comment by sebastienvercammen** [comment]
@pogo-excalibur Any updates?
