### ISSUE TITLE
is this normal? 

### ISSUE THREAD

**Issue by andywoody63** [RocketMap/RocketMap#2207]
Can anyone help? setting up a server for the first time and i get this error. Doesnt matter what account i use i always get this same error. 
![error](https://user-images.githubusercontent.com/7735248/28709299-a32a2138-7377-11e7-942b-c0a1754d9322.jpg)

**Comment by andywoody63** [comment]
the account is new and has accpeted the Tos as i logged in on my phone with it

**Comment by andywoody63** [comment]
NOONE WILL ANSWER ANYTHING OR HELP ON DISCORD.

**Comment by pogo-excalibur** [comment]
This doesn't appear to be a RM issue - RM is logging into your account sucessfully.
This looks to be an issue with the hashing service, and should be taken up with their support team.

**Comment by andywoody63** [comment]
i used the hashing service through https://www.pokefarmer.com/ as recommened in your wiki. They sent me a key which i added into the git command in this format... -hk HASHINGHEY
they have said the key is fine and their servers are performing as exspected and asked to double check with you guys to see if it was a common issue. 
Sorry to be a pain, thought i would have a go at setting this up and seems to be a pain to get working.

**Comment by sebastienvercammen** [comment]
This is not customer support, not a code issue and our Discord is actively helping others.

The error BadHashRequestException is related to the hashing servers, not to RocketMap, and the details are clear: they couldn't verify your hashing authentication details.

For help, either contact BossLand or ask more specific questions on Discord.
