### ISSUE TITLE
after npm install and running npm run build it is stuck

### ISSUE THREAD

**Issue by PeshBG** [RocketMap/RocketMap#2217]
DDiCk@WIN-QPHFVT3R5N8 MINGW64 ~/Desktop/RocketMap/RocketMap-develop
$ npm run build

> pogomap@0.1.0 build C:\Users\DDiCk\Desktop\RocketMap\RocketMap-develop
> npm run unzip && grunt build

> pogomap@0.1.0 unzip C:\Users\DDiCk\Desktop\RocketMap\RocketMap-develop
> cross-unzip static01.zip static/

**Comment by friscoMad** [comment]
Update to latest RM, and repeat npm install & npm run build
That issue is already fixed.

**Comment by sebastienvercammen** [comment]
Author not on latest commit.

**Comment by PeshBG** [comment]
thanks. that fixed it :) on time of writing i was on the latest commit
