### ISSUE TITLE
Flickering sprites frontend/map

### ISSUE THREAD

**Issue by Toetje585** [RocketMap/RocketMap#2218]
Pokemon icons seems to be flickering, happens in all browser, chrome, firefox and even edge.

See this GIF:

http://i.imgur.com/scl1PoW.gifv

## Expected Behavior

No flickering

## Current Behavior

Flickering sprites

## Steps to Reproduce (for bugs)

1. Install RocketMap
2. Replace static folder with the one from https://stuff.notfurprofit.org/static05.zip
3. Run the map

## Context

Trying to get rid of the flickering, I can't see anything using chrome dev tools.

## Your Environment

* Version used: Latest Pull
* Environment name and version (e.g. Python 2.7): Docker Version
* Operating System and version (desktop or mobile): Synology DSM 6.2

**Comment by sebastienvercammen** [comment]
I'm already on this. Fix to be merged soon.

**Comment by Toetje585** [comment]
@sebastienvercammen Thanks for the fast response.

**Comment by sebastienvercammen** [comment]
Tiny delay in merge of the fix because I'm travelling (currently in Vienna), but it has been fixed and is almost ready for a PR, I just need to find the time.

**Comment by Toetje585** [comment]
@sebastienvercammen Is this something we can expect to see this weekend?

I'm having a few docker containers that need the fix, my eyes hurt looking at the map :D

**Comment by darkelement1987** [comment]
Same problem here

**Comment by Shokoboko** [comment]
Same, fresh installation... plx fix it :)

**Comment by sebastienvercammen** [comment]
@Toetje585 This weekend, yes.

I'm back in Belgium and I can continue my work. :)

**Comment by Toetje585** [comment]
@sebastienvercammen Don't feel forced imao that's not my intention but many thanks!
