### ISSUE TITLE
Pokémon reappearing on the map after being removed

### ISSUE THREAD

**Issue by ps-gunkie** [RocketMap/RocketMap#2221]
## Expected Behavior
After clicking 'Remove' on a Pokémon's tooltip, the Pokémon should be removed from the map.

## Current Behavior
After clicking 'Remove' on a Pokémon's tooltip, the Pokémon disappears and reappears a few seconds later.

## Possible Solution
This probably got broken with one of the marker updates made in the past week. It worked fine before.

## Steps to Reproduce (for bugs)
1. Click on a Pokémon.
2. Click 'Remove' in the Pokémon's tooltip.

## Your Environment

* Version used: Latest current version (July 30th, 2017)
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Chrome 60 on Windows 10 Pro, Chrome 59 on Android 7.1.1

**Comment by Matzexxxxx** [comment]
Got the same issue.
For me, they reappear when i zoom in/out. The map isnt reloading and they are reappearing after zooming.
Removing them was pretty nice to use the map with nests, but now at the moment its pretty useless :( i hope it will be fixed very soon

**Comment by ChrisSsSsSsS** [comment]
This problem occurrs due to the call of `markerCluster.repaint()`, because if a marker is not clustered the `markerclusterer.js` will display it on the map, regardless on any action we took prior to that to hide the marker

I fixed this in my PR with a "hidden" flag #2310
