### ISSUE TITLE
on-demand mode does not start scanning even after webclient connects

### ISSUE THREAD

**Issue by 29988122** [RocketMap/RocketMap#2224]
## Expected Behavior
Start server in on-demand mode. Soon after client connects, it will start searching.

## Current Behavior
Server will not start searching even after web client connects.(neither via localhost:5000 nor remoteip:5000)

## Possible Solution
No idea

## Steps to Reproduce (for bugs)
1. Set on-demand_timeout in config.ini.
2. CMD would stop at [   search-overseer][        search][    INFO] Enabling new API force Watchdog.
After that, it periodically doing the following two tasks ONLY:
[        db-cleaner][        models][    INFO] Regular database cleaning complete.
[  account-recycler][        search][    INFO] Account recycler running. Checking status of 0 accounts.
3. Worker won't do anything even after someone connected via web.

## Your Environment
PY 2.7, maria db, windows 10
The rest are as recommended by the latest rocketmap documentation.

**Comment by friscoMad** [comment]
Fixed by #2250
