### ISSUE TITLE
API/Proxy connection error

### ISSUE THREAD

**Issue by Flackguy** [RocketMap/RocketMap#2227]
Hello
I try to run rocketmap on a dedicated server but i have this following warnings/errors when running the command "python runserver.py -st 5":
http://hpics.li/1116b72

Then i tested the same command with a proxy and i have this proxy error:
http://hpics.li/6fd1187

**Environment:**
Ubuntu 16.04.2 LTS
python 2.7.12
pip 9.0.1 from /usr/local/lib/python2.7/dist-packages (python 2.7)
npm 3.10.10
node v6.11.1

I tried to run it on my computer under Win10 and it works properly without proxy but i don't know why i can't do it on this dedicated server.
If anyone had the same error type a little help will be welcomed. :)
be welcomed.

**Comment by boby361** [comment]
Is this dedicated server professionally hosted? My assumption is that the IP range would be banned. (as almost all hosting company IP ranges are)

**Comment by pogo-excalibur** [comment]
@Flackguy you have an issue with your proxy setup
If you have any further queries, please direct them to the `#help` channel on our [discord server](https://discord.gg/rocketmap).

**Comment by sebastienvercammen** [comment]
First error is most likely a banned IP from your host, second is because your proxy failed the proxy test (timed out, banned, ...).
