### ISSUE TITLE
Pokemon markers constantly flickering

### ISSUE THREAD

**Issue by l1bbcsg** [RocketMap/RocketMap#2229]
## Expected Behavior
Map is rendered without visual glitches.

## Current Behavior
Most Pokemon icons on the map blink frequently even while idle: icon despawns and reappears shortly after.

## Steps to Reproduce (for bugs)
1. Open map
2. ???

## Context
This probably started happening after https://github.com/RocketMap/RocketMap/pull/2197 added a call to `markerCluster.repaint()` in `updateMap` which is causing visual stuttering at least every 500ms. With `redraw` in its place in previous version icons did not blink.
 
## Possible Solution
Updating MarkerClusterer might be a good first step. Otherwise refactor map redrawing.

As a workaround and a general improvement it would be a great idea to allow users configure clustering.

## Your Environment
Latest WebKit browsers.

**Comment by pogo-excalibur** [comment]
Repeat of #2218.
