### ISSUE TITLE
Empty RAIDs/Eggs keep getting put into database and sent over webhooks

### ISSUE THREAD

**Issue by tomballgithub** [RocketMap/RocketMap#2235]
## Expected Behavior

The only items in the 'raid' database table should be active and/or have valid information.

## Current Behavior

I am seeing 100's of empty rows show up in the 'raid' database table.  If you delete them then they return immediately.  They came back even after clearing the database.

![image](https://user-images.githubusercontent.com/15407947/28951344-0003edf4-7890-11e7-9488-c84b3ccc495c.png)

I am seeing this information constantly send to webhooks:

![image](https://user-images.githubusercontent.com/15407947/28951439-9d08fcb6-7890-11e7-982d-d309b107db75.png)

## Possible Solution

Make sure that empty raids/eggs are not tracked/stored during runtime
Make sure that empty raids/eggs are not written to database

## Steps to Reproduce (for bugs)

1. Ran a map with gym info enabled

## Context

It's a performance impact because Rocketmap seems to be constantly writing this info to database (it reappears right after you delete it) and it is sending the information to webhooks

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):
Ubuntu 16.04

**Comment by dongemus** [comment]
I believe this is the time since last egg? Maybe I'm wrong. But if that is it then we need that info for when eggs come back (presumably after Zapdos). 
Does turning off wh-type:eggs stop it from going to webhooks?

**Comment by tomballgithub** [comment]
The huge negative times @ PokeAlarm from the webhook are that way because if you look at the information in the database all of these invalid entries have a timestamp of 00:00:00 Coordinated Universal Time (UTC) and that is getting passed over the webhook
