### ISSUE TITLE
Failure to connect to Webhook server has very cryptic log messages

### ISSUE THREAD

**Issue by fosJoddie** [RocketMap/RocketMap#2279]
The log when RM fails to connect to a webhook server does not mention that it is a webhook that fails to connect and does not mention the server in question.

## Expected Behavior
something along the lines of
`unable to connect to {WH_ip}:{port} Retries(4)`

`unable to connect to {WH_ip}:{port} Giving up`

## Current Behavior
Current log message:
Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x1A205170>: Failed to establish a new connection: [Errno 10061] No connection could be made because the target machine actively refused it',)': /

## Steps to Reproduce (for bugs)

1. Set up a WH in config to ip/port that do not accept connections
2. Start scanning
3. See the message

## Context
Hours of sleep lost because of failing to understand that this message is from PokeAlarm stopped.

## Your Environment
North European enviroment, cold and harsh, 10-15 degrees C

**Comment by sebastienvercammen** [comment]
👍 On it.

**Comment by boby361** [comment]
Surprised this finally got reported xD. Ontop of this iv noticed when one of two webhook servers is down it doesn't push to the webhook thats enabled. If you want to test it. mabye give it half an hour or so.

**Comment by sebastienvercammen** [comment]
@fosJoddie Could you run #2304 (and approve if it works for you), then get it to log the retry exception details? It might not log it if the retries aren't logged in the generic handler, but I'm curious.

**Comment by fosJoddie** [comment]
after running for 10 minutes with my Webhook server off, the only messages I get is the same

`
2017-09-22 00:24:58,730 [         Thread-23][connectionpool][ WARNING] Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x0598FFB0>: Failed to establish a new connection: [Errno 10061] No connection could be made because the target machine actively refused it',)': /
`

It seems to never throw any critical log lines after the connection attempts has been exceeded.

@sebastienvercammen
