### ISSUE TITLE
Various errors under Chrome developer pane

### ISSUE THREAD

**Issue by tomballgithub** [RocketMap/RocketMap#2283]
There are syntax errors and a deprecation warning showing up in the developer pane of Chrome (61.0.3163.59 (Official Build) beta (64-bit)).  I see this behavior on builds with pulls from Aug 12 and Aug 29.  I believe it was there previously

![image](https://user-images.githubusercontent.com/15407947/29849552-366a3d3c-8ced-11e7-8b43-a185d84040a4.png)

## Expected Behavior

No such errors

## Current Behavior

There are unexpected errors and warnings.  Clicking them does not clearly indicate what is causing them so I was unable to debug further

## Steps to Reproduce (for bugs)

1. Pull Aug29 Rocketmap
2. Launch -os instance
3. Load map
4. View developer pane

## Your Environment

Ubunto 16.04 VPS as the server host
Windows Chrome 61.0.3163.59 (Official Build) beta (64-bit) as the client viewing map

**Comment by sebastienvercammen** [comment]
"VM" is noted when there's no information about filename, such as `eval()`'d code. We don't do that, so this might be a Chrome browser extension problem.

Clicking the line numbers might give us more information.

The deprecation warning is indeed ours.

**Comment by tomballgithub** [comment]
I agree that the issue is related to a Chrome extension.  I apologize for bringing up this errant issue.  For reference, I was able to immediately see the issue go away via incognito mode, but as I disabled/enabled extensions to try and figure out the source of the problem, the issue went away completely
