### ISSUE TITLE
Forced API check got no or invalid response. Possible bad proxy.

### ISSUE THREAD

**Issue by veygr** [RocketMap/RocketMap#2297]
## Expected Behavior
Start a scan.

## Current Behavior

`2017-09-14 17:31:13,650 [   search-overseer][        search][ WARNING] Forced API check got no or invalid response. Possible bad proxy.`
`2017-09-14 17:31:13,650 [   search-overseer][        search][ WARNING] Scanner paused due to failed API check.`
I dont use proxy. 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Debian 8.9
* npm 5.4.1
* Python 2.7.12

**Comment by pogo-excalibur** [comment]
For help setting up and using RocketMap please use the `#help` channel on our [Discord server](https://discord.gg/rocketmap).

**Comment by veygr** [comment]
I have not seen any information about this so I wrote here.
