### ISSUE TITLE
Printing status to the console eventually crashes Python.

### ISSUE THREAD

**Issue by silverx69** [RocketMap/RocketMap#2328]
Python 2.7
Windows 10

** also confirmed on **

Python 2.7
Windows Server 2012

When printing the worker status to the console window python.exe will eventually stop working. Visual Studio claims there is an access violation exception but I was unable to determine where. 

The way I am **avoiding** this bug is to constantly print the logs to the console instead of letting it keep refreshing the status.

**Comment by sebastienvercammen** [comment]
Please resubmit this Issue by filling in the template we've provided and including relevant details (logs, screenshots).
