### ISSUE TITLE
Scalingo Deployment Failing

### ISSUE THREAD

**Issue by AdinathJain** [RocketMap/RocketMap#2335]
## Expected Behavior
I tried to deploy RocketMap directly to Scalingo but the deployment fails because 
it asks for **npm install && npm run build** before starting the server. This should be 
part of the script itself.

## Current Behavior
Deployment fails due to Missing Front-end assets for which npm install && npm run build is required

## Possible Solution
Before starting the script, Python Script should run npm install && npm run build so that assets could be build itself.

## Steps to Reproduce (for bugs)

1. Go to [(https://github.com/RocketMap/RocketMap)]
2.Scroll to bottom and click on Deploy to Scalingo Button
3.Fill your details in scalingo form and start deployment 
4. Deployment Fails

## Context
I was trying to deploy rocketmap directly to scalingo

## Your Environment
I am using Scalingo App Container
<img width="517" alt="screen shot 2017-10-09 at 10 35 19 pm" src="https://user-images.githubusercontent.com/32661486/31368122-553c5df4-ad99-11e7-850f-2c425158a2ec.png">

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by FrostTheFox** [comment]
From the deployment section of the readme:
`Please note, deployments are not supported officially. You are using these deployment links at your own risk.`
