### ISSUE TITLE
Account-max-spins is not working

### ISSUE THREAD

**Issue by urinella** [RocketMap/RocketMap#2412]
This is my 5th issue. Sorry guys but the last days I'm studying every log.

I started the scanner 24 hours ago. The first spins are done and the log says: 

`Account ACCOUNT1 has reached its Pokestop spinning limits.`

But after some time the account is spinning stops again and never stops spinning until soft-/shadowban. Account-max-spins is at 10.
I have uploaded a part of my logfile here:

https://gist.github.com/urinella/19297257504fa888266101f9df2043cc

## Expected Behavior

Accounts are spinning some Pokéstops and stopping after Account-max-spins is reached.
## Current Behavior

Accounts are never stopping spinning Pokéstops.
## Possible Solution

No idea yet. Everyone should disable spinning before softbans are caused.
## Steps to Reproduce (for bugs)

1. Enable spinning
2. Start scanner for > 24 hours
3. Read log after account is fully softbanned

**Comment by crhbetz** [comment]
https://github.com/RocketMap/RocketMap/blob/develop/config/config.ini.example#L88

> #account-max-spins: # Maximum number of Pokestop spins **per hour** (default=20)

I'd like to emphasize the "per hour" part.

**Comment by urinella** [comment]
Omg yes, you're correct. Sorry, too many logs :D
