### ISSUE TITLE
Possible memory leak?

### ISSUE THREAD

**Issue by PoGoReporter** [RocketMap/RocketMap#245]
I noticed that pretty quickly (~30mins) the docker instance of my Pokemon Go Map is eating a lot of memory and continues to grow until my server starts killing other processes. Below you can see the container is using 1.24GB of memory(!) and it's not even using its own database, I have a mysql db running in a separate container.

![](http://i.imgur.com/TQv4jC4.png)
## Expected Behavior

Memory usage to stay constant or slowly increase

## Current Behavior

Memory usage quite quickly increases

## Steps to Reproduce (for bugs)

1. Run docker container for app.
## Context

Making it unfeasible to run anything else on a server with 2GB of RAM, which should be plenty.

## Your Environment

- Version used: 493f7e7d28c42fd27eb6053ddbfde75c26d7e5c3
- Environment name and version (e.g. Python 2.7): Provided docker container
- Operating System and version (desktop or mobile): ubuntu 16.04, 2GB RAM

**Comment by BaIthamel** [comment]
How many workers how many threads?

**Comment by PoGoReporter** [comment]
@BaIthamel 20 workers and (I assume) 20 threads

**Comment by BaIthamel** [comment]
@chuyskywalker fixing a memory leak is a feature request?

**Comment by schadis** [comment]
same problem for me

**Comment by chuyskywalker** [comment]
Does it constantly increase forever? Do you have to keep restarting it? How long does it take? 

You've only shown that it uses a lot at one time point; not that it's leaking over time.

Every instance I've run only hits about 182mb of memory and just hovers around that; but I'm only using 3 accounts, so perhaps that's a key difference.

**Comment by schadis** [comment]
i am running it on jelastic and everytime i start it with 20 workers its growing and growing until it kills itself  when it reacher maximum of 10gb .. that takes about 20 minutes

**Comment by Becold** [comment]
My monitoring might confirm a memory leak. I'm using Munin (Master + node) on a Debian 64 bits (i3, 8Go Ram). Nginx as reverse proxy and Server caching for Static folder. The server is online since 1.5 day.
http://puu.sh/qvHCs/0a83528afc.png
It keep to increase from 0.9Go to 1.6Go+ Ram

**Comment by chuyskywalker** [comment]
Conversely (and granted, only one day of data) mine is steady as a rock:

![2016-08-09 20_23_22-metric explorer _ datadog](https://cloud.githubusercontent.com/assets/131800/17540889/34670838-5e6f-11e6-84af-c5aa40e5eacc.png)

Perhaps # of accounts or some config difference is important.

**Comment by Becold** [comment]
With the command : `ps auxf`, i got this : http://puu.sh/qwhme/266a7df1b0.png
I'll check tonight which threads keep groing

PS : Got 7 accounts per worker

**Comment by SamuelMoraesF** [comment]
I'm having the same problem with 25 workers with just 1 account per worker, I'm reaching server's memory limit(1gb)

**Comment by schadis** [comment]
my mamory is stable between 120-130 mb with 30 workers but my storage space is growing and growing. my cpu use is really strange now with the latest dev build.
it was @ 100% bevore and now it goes up to 100% for 15 mins then to 10% and 20mins later to 100%.
for me that happens only on jelastic... lokal build is running fine

**Comment by Becold** [comment]
Sorry, i had to quickly reboot my server. And my test become useless now.
But on Munin, we see a BIG difference before and after the reboot :
![image](https://cloud.githubusercontent.com/assets/12863317/17571260/c5f852b2-5f4f-11e6-8af6-76f7c3f3a257.png)

**Comment by SamuelMoraesF** [comment]
Now I'm using 2,3Gb with 19 workers and 10 accounts each.

**Comment by Becold** [comment]
OH, i forgot about that issue. My solution is to reboot the server everyday, at 4am.
![image](https://cloud.githubusercontent.com/assets/12863317/17798052/695640de-65ce-11e6-9021-0296d1dad647.png)

**Comment by justsomedudeonthenet** [comment]
Are people still having this issue?

**Comment by Becold** [comment]
![image](https://cloud.githubusercontent.com/assets/12863317/18322733/73fb4320-7534-11e6-9ab8-58e2e7e7c339.png)
With my reboot every day

**Comment by johnscancella** [comment]
I am also seeing this issue, with just a single user. On Mac OS X

**Comment by schadis** [comment]
i am still on the genvent comit cause of this
dont wanna back to flask

**Comment by johnscancella** [comment]
When I upgraded to the latest version of Mac OS X the problem went away for me. Perhaps it is a specific version of one or more of the dependencies? I was previously on mavericks

**Comment by Becold** [comment]
Someone on the discord said : "It only happen when lauching multiple instances"

**Comment by sebastienvercammen** [comment]
Issue is no longer related to the current codebase, so we're closing the issue. If anyone still has the problem, please post additional data on latest commit and we'll reopen.
