### ISSUE TITLE
Manual captchasolving causes error in instance

### ISSUE THREAD

**Issue by tolukolvi** [RocketMap/RocketMap#2451]
I use manual captchasolving only. Solver sends the captcha token to instance, but it always causes an error. The account is marked as 'solved' in bookmarklet but when looking at statuspage I can still see that none of the accounts are in use but still says they are captcha'd. The account is not returned to work.

## Steps to Reproduce (for bugs)
1. take new account
2. use it until captcha'd
3. solve captcha
4. check error in instance

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

Python 2.7, Windows 10
![untitled](https://user-images.githubusercontent.com/22489426/35140814-4db2fb62-fd01-11e7-95d2-caf5b2be0408.png)

**Comment by pki0** [comment]
I don't have this issue on my map. Captcha Solving works well.

Can you check your `manual-captcha-domain:` and be sure you have a domain entry with: `https://domain.com/` ?
And is `captcha-solving: True` in your -os instance ?

**Comment by tolukolvi** [comment]
Of couse I do, otherwise I wouldn't be able to solve captchas at all. I even reinstalled RocketMap completely and I still get that same error every single time I manually enter a captcha.

**Comment by sebastienvercammen** [comment]
@tolukolvi That error happens on banned accounts. Please try logging into the account on the Pokémon Go app on your mobile phone and let us know if it worked.

**Comment by tolukolvi** [comment]
@sebastienvercammen I tried 10 accounts. All login. All have captcha waiting. Once completed they are all playable.

**Comment by sebastienvercammen** [comment]
Duplicate of #2267.
