### ISSUE TITLE
Geofence 2nd area not scanned

### ISSUE THREAD

**Issue by ETgohomes** [RocketMap/RocketMap#2478]
## Expected Behavior

In Config.ini,
geofence-file: geofence1.txt

Content of geofence1.txt:
[area1]
lat.., lng..
lat.., lng..

[area2]
lat.., lng..
lat.., lng..

Expect both area1 and area2 to be scanned.

## Current Behavior

RocketMap only scanned area1. After 100% (6hours), only area1 has scanned marks, but area2 untouched.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by wfcook** [comment]
Try removing the blank line. I seem to recall that being a problem

**Comment by ETgohomes** [comment]
Removed the blank line and restarted.
Still only scanned area1 but ignore area2. Even though the log screen said "Loaded 2 geofenced and 0 excluded areas"

**Comment by FrostTheFox** [comment]
Are you sure your -st is big enough to cover the 2nd geofenced area?

**Comment by sebastienvercammen** [comment]
Closing because author unresponsive and this issue has never been encountered before or after by anyone else.
