### ISSUE TITLE
Scanned genders are inaccurate

### ISSUE THREAD

**Issue by drfsupercenter** [RocketMap/RocketMap#2480]
Long story short, there is a discrepancy between the gender returned by GetMapObjects, and the actual gender you get when starting the encounter.

When using IV scanning accounts, the proper gender should easily be retrieved and the record updated - however, it is still using the original gender from the GMO response.

For non-IV scanned species there's no way to ensure accuracy, but when our local Discord server posts scanned results from the RM database, it's still using the original genders as returned by GMO, and not the true ones.

More information not pertinent to RM can be found at my initial write-up [here](https://www.reddit.com/r/TheSilphRoad/comments/7vl7ve/observation_pokémon_change_genders_when/)

**Comment by FrostTheFox** [comment]
Flagging to be checked for now, this definitely does seem to be happening but I'd like a deeper look in the context of the RM code.

**Comment by tomballgithub** [comment]
A solution could be to use the 'fresh' data from encounters to overwrite the data originally received via GMO.  There seems to be a belief that the encounter data is accurate for gender.

**Comment by drfsupercenter** [comment]
Correct. When you encounter the Pokémon (to get its IVs, for example) you will get the correct gender.  This is pertinent in the official game for species with visible form differences, e.g. Magikarp, Sneasel, Scyther and so on.

You can also encounter it with the level 1s and get the same gender data, but that would waste a lot more hashing requests, and is probably unnecessary.  I would vote to just overwrite the gender value with the data returned by the IV scanning accounts - if you don't scan IVs the gender might not match and/or just not known at all in that case.

**Comment by sebastienvercammen** [comment]
Tagged as "help wanted" instead of "to be checked": overwriting the gender data is a good middle ground for this problem, especially since encountering with lv1's would immensely increase the request count, and nothing guarantees that gender will stay the same for all levels.
