### ISSUE TITLE
TTH Search Never Finishes

### ISSUE THREAD

**Issue by Kneckter** [RocketMap/RocketMap#2507]
In January, PR #2416 changed the constraint for recording spawn timers in the RM DB. Since then, the TTH calculations on the Status page were not accurate. If you look, there may be a few TTHs that are yet to be found. This is caused by a spawn that has 'latest_seen' = '3600' and 'earliest_unseen' = '0' instead of being equal to each other.

The calculations done in schedulers.py would count that as a missing TTH because it is looking for spawns that have 'latest_seen' = 'earliest_unseen' but it shows in the DB as an hour long spawn ('kind' = 'ssss'). The log file notes them as 0 minute spawns "[   search-overseer][    schedulers][    INFO] Spawnpoints with a 0m range to find TTH: xx". 

Also noticed that the the spawnpointdetectiondata table does not record a tth_secs vaule for these spawnpoints. I looked through most of mine and saw that they stopped checking for a tth after 5 scans. I have reset the missed_count before noticing this so I am not sure if that is related. There is a mismatch between the last scan time in spawnpoints and spawnpointdetectiondata. So it probably stopped checking for a TTH once it marked 'latest_seen' = '3600' and 'earliest_unseen' = '0'.

Pokemon do show in these spots on the map every hour (I haven't verified if they are there in person yet). The spawnpoint does not note "Spawn times not yet determined. Current guess...". I once saw two pokemon on the same spawnpoint meaning these are still missing TTH.

![image](https://user-images.githubusercontent.com/16466177/36912871-26802142-1e16-11e8-9955-de691e0545e3.png)

![image](https://user-images.githubusercontent.com/16466177/36912603-3149a1da-1e15-11e8-970d-9f250ae14d81.png)

![image](https://user-images.githubusercontent.com/16466177/36913358-b06dbd3c-1e17-11e8-9093-bf651adbaef1.png)

![image](https://user-images.githubusercontent.com/16466177/36913651-a4966d5a-1e18-11e8-91c9-d95065982464.png)

![image](https://user-images.githubusercontent.com/16466177/36912549-0a69e5fc-1e15-11e8-9613-8625cc495cd1.png)

I would like to hear if other people noticed this behavior also.

## Expected Behavior
The status page should show 100% TTH found once the TTH search is completed. The spawnpoint data for 'latest_seen' and 'earliest_unseen' should be equal once a TTH is found.

## Current Behavior
The status page should show < 100% TTH found because of the mismatching 'latest_seen' and 'earliest_unseen' variables. RM no long checks for a TTH on these spawns once 'latest_seen' = '3600' and 'earliest_unseen' = '0'.

## Possible Solution
Not sure of the best way to correct this. The issue could be that the tth_secs vaule is not being recorded before the spawn is marked with 'kind'='ssss'. Or that the 'kind' should be 'hhhs' since the log notes this as a spawn with less than 1 minute.

## Steps to Reproduce (for bugs)
1. Rescan an area that used to suffer from the u_constraint error.
2. Wait to finish the initial and TTH scans (TTH may show a few missing and never complete).
3. Query the spawnpoints within that area for 'latest_seen' = '3600' and 'earliest_unseen' = '0'.
4. Query the spawnpointdetectdata table for those spawn IDs to see the last time to see if it stopped checking for a TTH.

## Context
Spawns still show in those areas but I am not sure if their timers are accurate. I rarely have people report that the timers are off but there was one case that a spawn was on my map with 20 minutes left and it had already despawned. I did not check into this since it was only one time but it could have been on one of these spots.

My current scanners do not schedule TTH searches anymore so these spots are just stuck in their current state.

This affects 46 out 58,000 spawnpoints (0.1%) in my database to give you an idea of how rare these outcomes are.

## Your Environment
RM pull to PR #2505 (latest)
MariaDB-10.2.11
Schema version 28
HiediSQL 9.4.0.5215
Ubuntu 17.04

**Comment by sebastienvercammen** [comment]
> Spawns still show in those areas but I am not sure if their timers are accurate. I rarely have people report that the timers are off but there was one case that a spawn was on my map with 20 minutes left and it had already despawned.

Despawns/respawns/spawn changes (even attribute changes) are known to happen on weather-related changes. Since RM doesn't currently rescan scanned Pokémon (there was no need to before weather changes, and it would be a massive increase in amount of requests/hashing required), there will be inconsistencies between the Pokémon Go app and the scanned map.

> The calculations done in schedulers.py would count that as a missing TTH because it is looking for spawns that have 'latest_seen' = 'earliest_unseen'

https://github.com/RocketMap/RocketMap/blob/develop/pogom/models.py#L1290

```
def tth_found(sp):
    latest_seen = (sp['latest_seen'] % 3600)
    earliest_unseen = (sp['earliest_unseen'] % 3600)
    return latest_seen - earliest_unseen == 0
```

In #2416, all references were updated to include `% 3600` ([modulo](https://en.wikipedia.org/wiki/Modulo_operation)), which makes the distance between `a % 3600` and `b % 3600` equal to `0` for the numbers `0` and `3600`.

Are you sure your reasoning was correct?

**Comment by Kneckter** [comment]
You are right, the math in models.py works out to be 0 when the 'latest_seen' = '3600' and 'earliest_unseen' = '0'. That is probably why they are not being scanned anymore.

In schedulers.py, it process would set 'tth_found' to '1' if the two values were the same. Since they are different, it is set to '0'. So the status page shows a missing TTH.
https://github.com/RocketMap/RocketMap/blob/develop/pogom/schedulers.py#L774

I am not that great with python so let me know if that doesn't sound right. 

I changed one of the 3600s to a different number (based on the time seen in spawnpointdetectiondata) and it was rescanned. That happened because of the code you pointed out, I made the mod value not equal to 0 anymore. But once that one had a new 'latest_seen' and 'earliest_unseen' value saved, the status page showed one less TTH to find and the spawnpointdetectiondata recorded a tth_secs value for that spawnpoint. 

That value probably wasn't accurate because of my manual manipulation but it was worth a test.

**Comment by sebastienvercammen** [comment]
@Kneckter You're correct, line 774 of schedulers.py doesn't make use of `tth_found(sp)` for some reason. Legacy code. This will cause the issue you're describing. I'll push a fix.

**Comment by sebastienvercammen** [comment]
@Kneckter Can you please run #2512 and let me know if that fixed it for you?

**Comment by Kneckter** [comment]
The code changes in #2512 worked to show 100% on the status page. Thanks for making the update for this issue @sebastienvercammen 
![image](https://user-images.githubusercontent.com/16466177/36935535-0ac2be22-1ec7-11e8-8092-efbf99abf523.png)
