### ISSUE TITLE
Cant start after clear reinstall

### ISSUE THREAD

**Issue by Inspekt0r** [RocketMap/RocketMap#2511]
Hi guys when i try to start main RM, this error showed:

Full re-install cant helped

![image](https://user-images.githubusercontent.com/37010965/36931452-8d1eb08e-1ec6-11e8-8a6e-877a98f55b9f.png)

**Comment by sebastienvercammen** [comment]
From our FAQ:

![image](https://user-images.githubusercontent.com/4874269/36933220-97dc3e06-1ed5-11e8-99a9-85b5eb85afc9.png)

Please read installation instructions before submitting an issue request.
