### ISSUE TITLE
Map 'forgets' (ex)raid filters when you switch on gyms

### ISSUE THREAD

**Issue by darkelement1987** [RocketMap/RocketMap#2541]
## Expected Behavior

 Even with gym switch to on, map should remember what you've set the raid switches to, why are the egg icons showing on the gyms when you've set the raid switch 'Show active raids only' to on?

## Current Behavior
When you enable 'Active raids only' and then turn on gyms, it will show eggs as well. Same happens with 'Park gyms only', that will show 'Non park raids' as well.

## Possible Solution

I don't know

## Steps to Reproduce (for bugs)

1. Turn on raids and turn off gyms
2. Flip the switch for 'Show active raids only' to ON
3. Now activate gyms

**This looks good:**
![image](https://user-images.githubusercontent.com/21128187/37556936-75432bba-29fd-11e8-9c70-1159715f370c.png)

**This doesn't:**
![image](https://user-images.githubusercontent.com/21128187/37556945-987b2736-29fd-11e8-8b76-b8cf8bed75af.png)

## Context

Why does it show 'Non park raids' and 'eggs'?

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):
Someone else's map (latest dev build)

**Comment by pogo-excalibur** [comment]
I can replicate the issue.

I'll take a look at this. I simplified the logic that's used in `updateGymMarker()` in the spritesheet rework (#2348), so I'll see if I can make use of some of that code to fix this.

**Comment by pogo-excalibur** [comment]
This should be fixed when #2551 gets merged.

**Comment by darkelement1987** [comment]
Very nice. Gonna close this issue.
