### ISSUE TITLE
Can not sucessfully edit js files

### ISSUE THREAD

**Issue by Inuyasha22** [RocketMap/RocketMap#2553]
So here goes the problem:

I'm trying to remove some features for .. reasons (my users don't need to know CP, moves, etc so I thought it'd be a little cleaner without these stats). Since hashing is down, I add the needed data manually via SQL. 

Now I go to map.js and disable certain lines (or remove them), save the file, start the server. 

Unless I overwrite the js-files with a backup it'll complain there'd be missing files. 
It demands I run "npm install" and "npm run build" before booting the server the *first time*.

I'm using Notepad++ to edit the js-files. Also tried good old notepad (windows text editor) with the same results. Server is *not* running when I save the scripts. 

EDIT: 
Same situation, new problem. Changes don't show up. 
Even if "npm run watch" is exectued *after* saving and *before* running the server.

**Comment by ghost** [comment]
Problem solved itself. 

Turns out I broke the syntax. That was the whole problem.
