### ISSUE TITLE
Geoloc stops working when host is not Localhost

### ISSUE THREAD

**Issue by Inuyasha22** [RocketMap/RocketMap#2554]
Problem:
- Button for jumping to your location stops working when host in "config.ini" is set to anything else than localhost.

Updated recently?
- Yes

Consequences:
- When host is left at "localhost", map is unreachable to the outside web.

**Comment by sebastienvercammen** [comment]
- Issue template not used.
- Geolocation requires HTTPS on some modern browsers. `localhost` is an exception and is considered a secure origin.
