### ISSUE TITLE
Invalid Rocketmap Discord Invite

### ISSUE THREAD

**Issue by njrhoades98** [RocketMap/RocketMap#2556]
## Expected Behavior

The discord invite provided should allow access to the discord server
## Current Behavior

The discord invite provides a message stating it is invalid.
## Possible Solution

Put a new, non-custom invite url into the readme, I'm guessing the custom invite expired due to not having enough discord nitro boosts

**Comment by birdstream** [comment]
> ## Expected Behavior
> The discord invite provided should allow access to the discord server
> 
> ## Current Behavior
> The discord invite provides a message stating it is invalid.
> 
> ## Possible Solution
> Put a new, non-custom invite url into the readme, I'm guessing the custom invite expired due to not having enough discord nitro boosts

This whole project has expired, unfortunately. There has not been any activity here for at least 2 yrs. If there ever will be depends largely on if there is anyone that can/will take a crack at PoGo's encryption since the BossLand takedown. But I doubt that TBH...
