### ISSUE TITLE
Incorrect pokemon expiration timer resulting in duplicate entries in DB

### ISSUE THREAD

**Issue by diputz42** [RocketMap/RocketMap#722]
## Expected Behavior

Pokemon should display correct timer until expiration.
## Current Behavior

Expiration timer counts down to expiry, pokemon disappears, and then seemingly respawns with a new timer for approximately 1-3 minutes. Timer counts down again until expiry, until pokemon respawns again with a new timer for approximately 1-3 minutes. This repeats until the pokemon truly disappears. Database is logged with multiple entries of same encounter id, but with different disappear times.
## Steps to Reproduce (for bugs)

1. PoGoMap running with 5 accts on 1 worker -st 4 -sd 15.
2. MariaDB MySQL.
3. Pogom is running alongside PoGoMap both writing to same DB.
4. http://imgur.com/a/PZz2j
## Context

I keep going back to the spot where I've already caught said pokemon, only to find it's disappeared and my hopes and dreams shattered.
## Your Environment

- Version used: 3.1.0
- Environment name and version (e.g. Python 2.7): Python 2.7 x86
- Operating System and version (desktop or mobile): Win7 a64
  ![duplicate encounters](https://cloud.githubusercontent.com/assets/20994910/17681635/32c327c8-6347-11e6-8186-53c1f75781cd.png)

**Comment by BaIthamel** [comment]
yeaaah that's a sideeffect of the 595 bugfix...

**Comment by BaIthamel** [comment]
Please run this without pogom. If the issue goes away then that's the problem. We can't support that kind of use. if the issue persists please let us know.

**Comment by Xcelled** [comment]
Couldn't this be a spawnpoint issue? Maybe it's a 1/60 spawnpoint and the code is merely reinterpreting the spawn to a new 15 minutes every time it 'sees' it. A side effect of the 595 fix.

**Comment by matpag** [comment]
For me it's happening with the release version.
Pogo Map continued to notify of dewgong's spawn every 15 minutes (immediately after he despawn he is appearing again in the map in the same spot even if the full stats showed me that he appeared only 1 time)

I've solved restarting the server

**Comment by diputz42** [comment]
@Balthamel I've tested this over the past week running solely PoGoMap and can confirm this issue persists.

**Comment by majuss** [comment]
@BaIthamel I can also confirm this issue is still present! Using pure mysql DB and debian.

**Comment by sebastienvercammen** [comment]
Closed, this is a very old issue. Any feature requests are now handled via http://vote.devkat.org and if any issue reported in the issue is still related to current code, a new GitHub issue should be opened.
