### ISSUE TITLE
High process count causes mysql to deadlock often

### ISSUE THREAD

**Issue by Dagothur** [RocketMap/RocketMap#766]
When using a high number of processes mysql will deadlock frequently:

http://pastebin.com/adrFACgs

**Comment by Okumba** [comment]
Some problem, not that much though.
Running 120 worker (st 3 sd 10) to cover most parts of small to medium size city.
VM is using Win7, mysql connections increased to 5000 (in my.ini), didn't help though.

**Comment by Dagothur** [comment]
I have 11 different servers connecting to the one DB so I imagine this exacerbates the issue.

**Comment by hklcf** [comment]
more ram = more connections

**Comment by Okumba** [comment]
apparently 32GB ram isn't enough to run 120 workers ;)

**Comment by majuss** [comment]
I have 32 workers and only 2 of 4 GB of RAM is used (debian vm). So how should more RAM help?! I'am getting a lots of deadlocks too..

**Comment by Xcelled** [comment]
This is probably our fault, not mysql's. I suspect a connection isn't getting closed or something like that. The whole db end of things should be looked at again, we do some weird stuff.

**Comment by BaIthamel** [comment]
I agree, the db gets opened and held open sometimes. People fix it as they spot them.

**Comment by STEX20** [comment]
Hi, just for the record: I just tried to update my map to the current version, and got these mentioned deadlock messages. Before the update i was using 1556844f63c0f0be0cc42b0751d24737472481dc 
(2016-08-14 by FrostTheFox) without theses problems. The deadlocks have appeared between that commit and the current version, so i guess to start the search for the problem between the mentioned commit and the head.

**Comment by Xcelled** [comment]
@BaIthamel what about implementing our own context manager for DBs, so instead of doing DB connections manually, you do a simple `with get_db() as db:` and that takes care of everything for you. Or, we could use contextlib to avoid having to wrap the db classes: http://stackoverflow.com/a/3774934/1163742

**Comment by chuyskywalker** [comment]
There's a huge amount of database fix up in #582; but specifically not opening/closing the connection all the time.

When talking about MySQL, we're also using `REPLACE INTO` which is very, very under performant for mysql. It's on my list to figure out how to make that not the case.

**Comment by majuss** [comment]
I switched from mariaDB to pure mySQL and the locks are gone (debian stable)!

**Comment by Dagothur** [comment]
@majuss +1 no more dead locks with mariadb gone

**Comment by pyr0ball** [comment]
Might be a red herring. Do you know what the max db connections setting was configured at?

**Comment by Dagothur** [comment]
@pyr0ball looks like you were correct. Still getting deadlocks with basic mysql, although much less than when using mariadb.

**Comment by sebastienvercammen** [comment]
Issue is no longer related to the current codebase, so we're closing the issue. If anyone still has the problem, please post additional data on latest commit and we'll reopen.
