### ISSUE TITLE
IP change after ban results in scan requests spam

### ISSUE THREAD

**Issue by PenguinsFlyGood** [RocketMap/RocketMap#801]
## Expected Behavior

every scan should have a delay of 10 seconds -sd 10 even if the ip changes after an ip ban
## Current Behavior

resume scanning after an ip ban, has no delay.
## Steps to Reproduce (for bugs)

1. start scan on unbanned ip
2. get a banned ip(must get banned ip message, not the 0 pokemon 0 gyms 0 pokestops ban)
3. change ip to unbanned ip
4. it starts spamming requests and ignores the scan delay
## Context

My setup has multiple proxies that change ips every 15 minutes, everytime one of them lands on a banned ip and then changes to an unbanned ip, it ignores the scan delay.

i've only witnessed it happening with the --spawnpoints-only arguement.
## Your Environment

- Version used:
- Environment name and version (e.g. Python 2.7):
- Operating System and version (desktop or mobile):

**Comment by BaIthamel** [comment]
This is related to #683 i think.

**Comment by sebastienvercammen** [comment]
Issue is no longer related to the current codebase, so we're closing the issue. If anyone still has the problem, please post additional data on latest commit and we'll reopen.
