### ISSUE TITLE
Unable to retrieve altitude from Google APIs

### ISSUE THREAD

**Issue by slideup-benni** [RocketMap/RocketMap#841]
## Expected Behavior

All requests have a altitude
## Current Behavior

"Unable to retrieve altitude from Google APIs; setting to 0" in the log files
## Possible Solution

store known altitudes in database / to reduce google requests we could calculate own altitudes with using near known altitudes
## Your Environment

- Version used: 471798a
- Environment name and version (e.g. Python 2.7):
- Operating System and version (desktop or mobile): debian7

**Comment by sebastienvercammen** [comment]
This functionality was already merged. Closing.
