### ISSUE TITLE
disappear_time for 30 minute spawns is 15 instead of 30

### ISSUE THREAD

**Issue by hagehg** [RocketMap/RocketMap#855]
I have a spawnpoint in my area where Pokemon will remain for 30 minutes every hour. (from ~xx:45:57 to xx:15:57)

During the first 15 minutes of the spawn, each scan will reset the disappear time to 15 minutes into the future and overwrite the row in the database.

For example:

| encounter_id | pokemon_id | disappear_time |
| --- | --- | --- |
| MTY3MDczMTc5ODYzMzU5OTYxNDE= | 54 | 2016-08-19 22:02:41 |

will be overwritten with:

| encounter_id | pokemon_id | disappear_time |
| --- | --- | --- |
| MTY3MDczMTc5ODYzMzU5OTYxNDE= | 54 | 2016-08-19 22:06:15 |

Starting from xx:00:57 each scan will have the correct disappear_time xx:15:57 untill the pokemon eventually disappears.
## Expected Behavior

30 minute spawns should have the correct disappear_time from the moment they first appear
## Current Behavior

30 minute spawns are reset to disappear 15 minutes into the future with each scan
## Steps to Reproduce (for bugs)

1. Identify a 30 minute spawn
2. Scan it repeatedly
3. Watch the disappear_time in your database change constantly
## Your Environment

- Version used: dev branch from ~24h ago
- Environment name and version (e.g. Python 2.7): 2.7.12
- Operating System and version (desktop or mobile): Ubuntu 16.04 LTS

**Comment by GreenSlime96** [comment]
This same issue affects me too and causes trouble especially when using spawnpoint-scanning.

**Comment by koljanowak** [comment]
I see the same issue.

**Comment by pyr0ball** [comment]
@chuyskywalker could you take a look at this?

**Comment by GreenSlime96** [comment]
@pyr0ball it's a known bug.

**Comment by matpag** [comment]
yeah, same problem for me

**Comment by Saprophator** [comment]
Here is a useful thread with some data to the different spawn times and their behavior[reddit](https://www.reddit.com/r/pokemongodev/comments/4yzqc2/spawn_point_types_clearing_confusion/)

**Comment by matpag** [comment]
@Saprophator really usefull link

**Comment by Xcelled** [comment]
A possible fix is to store our own magic value in the DB. So when we get an (obviously) invalid time from the API, we store, say, Jan 1st, 2999. Then, when these Pokemon are shown, their disappear time can be displayed as ">15 minutes" until eventually their timer kicks down below 15 and we get the actual time.

It would require a little bit of extra care for anyone querying the Pokemon table, but it's probably the least complicated solution.

**Comment by khag7** [comment]
There's a solution (though poorly described) solution in that reddit thread. OP and I went back and forth and I think the method we discussed would be very successful.

The gist is this:
New spawnpoint found. Log it in a table, spawnpoint. Based on whether a valid or invalid timestamp was received, you store V or I in the "type" column. In the "check_at" column you store the despawn time + 15 minutes if a valid timestamp was given, or store right now plus 10 minutes if an invalid timestamp was given. Workers need to pull from this db and search based on "check_at".

On the next check, you might find a spawn there, you might not. If you do, you willl be able to determine spawn type (details in that reddit thread). If you were able to determine the type, store that in the "type" column and store "check_at" as the now known spawn time. In other cases, you'll change the type from V or I to V0 or I0. We used 0 to indicate nothing found on that check. Update "check_at" to check again in 15 minutes. On the 3rd check you will be able to determine the type. You'll have enough information now to definitively say what type the spawnpoint is. Store the type and the spawn time and now every time that point is shown on the map in the future we can use the correct time.

**Comment by BaIthamel** [comment]
this is because we did a smaller hack fix to remove 595 bug. the solution was to make it 15mins if the spawn was too big.

**Comment by khag7** [comment]
I remember. I'm just frustrated because I understand in my head the logic of how this should go, but my python skills aren't there yet. I'll keep working on it until i get it, but i really think if someone who knows what they're doing reads that post carefully they'll have a moment of clarity and say "oh my god this is incredible we can now recognize 45 minute spawns"

**Comment by GreenSlime96** [comment]
It involves modifying the database schema to accommodate for the search
times or having a separate table for the spawnpoint_ids to identify their
types.

**Comment by khag7** [comment]
Yup. I've described a pretty usable set up for this but never worked with database queries through python. I've been slowly chipping away at it though, finally got some working code, but I'm sure its not as good as what someone already here would write and will get thrown to the side anyway, so I'll be keeping it for personal use only I think. It's nice though, at least now I can log the type of each spawnpoint (1x15, 1x30, etc) and display the correct despawn times on my scans :)

**Comment by Saprophator** [comment]
more research on the matter [reddit](https://www.reddit.com/r/pokemongodev/comments/50b2go/reason_for_spawn_point_types_found/)

**Comment by sebastienvercammen** [comment]
Issue is no longer related to the current codebase, so we're closing the issue.
