### ISSUE TITLE
Unsuccessful login not caught

### ISSUE THREAD

**Issue by springjools** [RocketMap/RocketMap#880]
## Expected Behavior

Login with a wrong username should yield a clear error
## Current Behavior

auth_ptc responds with this:

auth_ptc][   ERROR] Could not retrieve token: Your username or password is incorrect

but still you get this from search.py:
 search][    INFO] Login for account asssasa successful
## Possible Solution

I'll work on it, but:

https://github.com/PokemonGoMap/PokemonGo-Map/blob/develop/pogom/search.py#L656

This does not work. The exception needs to be caught better somehow.
## Steps to Reproduce (for bugs)

Just run the runserver.py like this:
python runserver.py -l "lat lon" -u nonexistentuser1 -p somepasswd
## Your Environment

python 2.7.11
latest dev build: pulled 1 hr ago
win 7 x64

**Comment by springjools** [comment]
Note: I changed L664 to log.info (in case you wonder)

**Comment by onilton** [comment]
@springjools is this still valid?

**Comment by springjools** [comment]
It's from August, searchy.py has been refactored many times since.

Now the output is like this:

2017-03-24 12:26:12,470 [   search-worker-0][        search][   ERROR] Exception in search_worker under account asasa Exception message: TooMa
LoginAttempts('Exceeded login attempts.',).
Traceback (most recent call last):
  File "U:\bin\github\RocketMap\pogom\search.py", line 927, in search_worker_thread
    status['proxy_url'])
  File "U:\bin\github\RocketMap\pogom\account.py", line 60, in check_login
    raise TooManyLoginAttempts('Exceeded login attempts.')
TooManyLoginAttempts: Exceeded login attempts.

Which I think is acceptable.
