### ISSUE TITLE
Blurred jumping Pokemon sprite's resolution

### ISSUE THREAD

**Issue by Spacehug** [RocketMap/RocketMap#892]
## Expected Behavior

Jumping sprites should be sharp and clear
## Current Behavior

Blurred af.
## Possible Solution

Unknown
## Steps to Reproduce (for bugs)
1. Options - Select HQ sprites for pokemons and make them Large or X-Large
2. Set notification for any pokemon
3. Wait for it
4. Zoom out.
## Your Environment

Latest map build, Latest Google Chrome, Latest Ubuntu 16.04 with the latest updates, everything latest, even my mum, even the sky, even Allah.

**Comment by BaIthamel** [comment]
I think it's just screen refresh rate, if i zoom in far enough it stops blurring.

**Comment by sebastienvercammen** [comment]
Icons/sprites no longer in the codebase, so this is no longer relevant.
