### ISSUE TITLE
Fix handling of invalid responses of spawn points.

### ISSUE THREAD

**Issue by TheNewDarkOne** [RocketMap/RocketMap#937]
Current Handling:
ERROR] Invalid response at <coords>, abandoning location

Correct handling:
Don't ignore responses that aren't understood!

Reference to spawn types and how to handle:
https://www.reddit.com/r/pokemongodev/comments/4yzqc2/spawn_point_types_clearing_confusion/

Also useful:
https://www.reddit.com/r/pokemongodev/comments/4ui7um/pokemon_go_mapscan_optimized_code/

**Comment by SoonDead** [comment]
During spawnpoint scanning valid locations are removed over time because of this.

**Comment by sebastienvercammen** [comment]
Closed, this is a very old issue. Any feature requests are now handled via http://vote.devkat.org and if any issue reported in the issue is still related to current code, a new GitHub issue should be opened.
