### ISSUE TITLE
Altitude is hardcoded in spawnpoint scanning

### ISSUE THREAD

**Issue by joberembt** [RocketMap/RocketMap#991]
In search.py, line 408, the altitude is hardcoded to 40.32:
'retset.append(((location['lat'], location['lng'], 40.32), location['appears'], location['leaves']))'
## Expected Behavior

The altitude should be pulled from the google API for the given spawnpoint

## Current Behavior

The value is hardcoded, creating a red-flag for bot activity (not that there aren't others)

## Possible Solution

Use a call to the google altitude API like is done in runserver.py

## Context

Having everyone that is using spawnpoint scanning using the same altitude for their request should be avoided.
## Your Environment

- Version used: latest develop
- Environment name and version (e.g. Python 2.7): Python 2.7.10
- Operating System and version (desktop or mobile): Win 8.1

**Comment by pyr0ball** [comment]
Shouldn't the behavior be that each spawnpoint should have the same altitude every time, since they don't move? If the altitude reported for a static location is different between different accounts, that would seem to be incorrectly reported data.

**Comment by rp000** [comment]
Using the google altitude API would ensure we get the same altitude for the same spawnpoint every time right? 

Incidentally hex scan mode sets altitude to 0. Wonder if Niantic checks this?

**Comment by n3cr0cr0w** [comment]
I would store the result in the DB, we don't want to hammer google with a request every time.

**Comment by slideup-benni** [comment]
When you store the altitude in the db, then store the base lat and lon and not the jittered ones, please

**Comment by angrymoose** [comment]
@slideup-benni I would expect them to store the true altitude and then add jitter to the data pulled from the database.

**Comment by sebastienvercammen** [comment]
Altitude has since been reworked. Closing.
