### ISSUE TITLE
Some required arguments aren't really required under certain conditions

### ISSUE THREAD

**Issue by gabrielsoldani** [RocketMap/RocketMap#999]
`--no-server` mode doesn't need a Google Maps key, but we require one anyway.
`--only-server` mode doesn't need account data, but we require it anyway.

**Comment by Xcelled** [comment]
Imo this is another reason for splitting this project up into sub-commands or sub-programs, such as a webserver, an overseer, and a worker process.

**Comment by arivero** [comment]
That is minor bug, not feature request

**Comment by sebastienvercammen** [comment]
Closing because the issue is much older than the current codebase. If you feel this functionality should still be changed, please make a new issue, mention me in it (@sebastienvercammen) and we'll get on it.
